Return-Path: <MAILER-DAEMON@somehost.example.com>
Received: from omr-m07.mx.aol.com (omr-m07.mx.aol.com [64.12.138.19])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k71I0oIf010718
	for <address@example.com>; Tue, 1 Aug 2006 11:00:50 -0700
Received: from  air-yi01.mail.aol.com (air-yi01.mail.aol.com [172.18.180.135]) by omr-m07.mx.aol.com (v107.10) with ESMTP id RELAYIN7-844cf96c82d4; Tue, 01 Aug 2006 14:00:40 -0400
from: Mail Delivery Subsystem <MAILER-DAEMON@aol.com>
Date: Tue, 1 Aug 2006 13:58:02 EDT
To: <address@example.com>
Subject: Mail Delivery Problem
Mailer: AIRmail [v110.15]
X-AOL-IP: 172.18.180.135
Message-ID: <200608011400.844cf96c82d4@omr-m07.mx.aol.com>


Sorry address@example.com. Your mail to the following recipients could not be delivered because they are not accepting mail with attachments or embedded images:
	mykewlaolacct

