Delivered-To: automated-bounces@example.com
Received: by 10.204.119.15 with SMTP id x15cs341259bkq;
        Wed, 14 Oct 2009 02:42:35 -0700 (PDT)
Received: by 10.220.79.9 with SMTP id n9mr12559077vck.4.1255513352794;
        Wed, 14 Oct 2009 02:42:32 -0700 (PDT)
Return-Path: <>
Received: from omr-d25.mx.aol.com (omr-d25.mx.aol.com [205.188.249.69])
        by mx.google.com with ESMTP id 37si4805656vws.126.2009.10.14.02.42.32;
        Wed, 14 Oct 2009 02:42:32 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of omr-d25.mx.aol.com designates 205.188.249.69 as permitted sender) client-ip=205.188.249.69;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of omr-d25.mx.aol.com designates 205.188.249.69 as permitted sender) smtp.mail=
Received: from air-de07.mail.aol.com (air-de07.mail.aol.com [172.19.170.135]) by omr-d25.mx.aol.com (v117.7) with ESMTP id MAILOMRD251-7d834ad59cf32db; Wed, 14 Oct 2009 05:42:11 -0400
from: Mail Delivery Subsystem <MAILER-DAEMON@aol.com>
Date: Wed, 14 Oct 2009 05:38:51 EDT
To: <automated-bounces@example.com>
Subject: Mail Delivery Problem
Mailer: AIRmail [v125.7]
X-AOL-IP: 172.19.170.135
Message-ID: <foo@omr-d25.mx.aol.com>


Sorry automated-bounces@example.com. Your mail to the following recipients could not be delivered because they are not accepting mail with attachments or embedded images:
	exampleuser
