Delivered-To: automated-bounces+2a5e0c38-900d-11df-8fb7-89d06df2b1bd@email.example.com
Received: by 10.224.28.133 with SMTP id m5cs238471qac;
        Thu, 15 Jul 2010 05:33:28 -0700 (PDT)
Received: by 10.223.110.83 with SMTP id m19mr527606fap.26.1279197207523;
        Thu, 15 Jul 2010 05:33:27 -0700 (PDT)
Return-Path: <>
Received: from mout-bounce.d.e.f (mout-bounce.d.e.f [212.227.15.21])
        by mx.google.com with ESMTP id n26si441733faa.176.2010.07.15.05.33.27;
        Thu, 15 Jul 2010 05:33:27 -0700 (PDT)
Received-SPF: pass (google.com: domain of mout-bounce.d.e.f designates 212.227.15.21 as permitted sender) client-ip=212.227.15.21;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of mout-bounce.d.e.f designates 212.227.15.21 as permitted sender) smtp.mail=
Received: from mx by mx.d.e.f id 0MQ2IJ-1OUAxY0Xhb-004njz;
	Thu, 15 Jul 2010 14:33:27 +0200
To: <automated-bounces+2A5E0C38-900D-11DF-8FB7-89D06DF2B1BD@email.example.com>
From: John Smith <john@a.b.c>
Subject: Thank you for your e-mail
Date: Thu, 15 Jul 2010 14:33:27 +0200
Message-Id: <0MQ2IJ-1OUAxY0Xhb-004njz@mx.d.e.f>
Precedence: bulk
X-Original-Id: 0Lm2uj-1P8RSp3erZ-00aGc1
X-Provags-Id: V01U2FsdGVkX180YyfsmTZhnWCeECtwIiKMPqYIokXNOfuBd9w
 kORxr4QOa5QrXjQB1nxq1dOC0VA7NaQBlT4mjBQMbokLlGvCQ

Thank you for you e-mail. 
I will endeavour to reply as soon as possible.

Regards

John Smith
john@a.b.c
