Delivered-To: automated-bounces+c769741a-932b-11df-af69-e1b922927a70@email.example.com
Received: by 10.224.45.67 with SMTP id d3cs109052qaf;
        Mon, 19 Jul 2010 04:50:09 -0700 (PDT)
Received: by 10.227.157.13 with SMTP id z13mr3921508wbw.184.1279540209023;
        Mon, 19 Jul 2010 04:50:09 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id c24si6318686wbc.97.2010.07.19.04.50.08;
        Mon, 19 Jul 2010 04:50:09 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 7F46F16582EE; Mon, 19 Jul 2010 12:50:08 +0100 (BST)
Date: Mon, 19 Jul 2010 12:50:08 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+C769741A-932B-11DF-AF69-E1B922927A70@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="4B69B16582C5.1279540208/server4.example.co.uk"
Message-Id: <20100719115008.7F46F16582EE@server4.example.co.uk>

This is a MIME-encapsulated message.

--4B69B16582C5.1279540208/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mx.example.net[131.111.8.146] said: 550-<recipient@example.net>
    is not a known user on this system; 550 see
    http://www.example.net/cs/email/bounce.html (in reply to RCPT TO command)

--4B69B16582C5.1279540208/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 4B69B16582C5
X-Postfix-Sender: rfc822; automated-bounces+C769741A-932B-11DF-AF69-E1B922927A70@email.example.com
Arrival-Date: Mon, 19 Jul 2010 12:50:08 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx.example.net
Diagnostic-Code: smtp; 550-<recipient@example.net> is not a known user on this
    system; 550 see http://www.example.net/cs/email/bounce.html

--4B69B16582C5.1279540208/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by server4.example.co.uk (Postfix, from userid 505)
	id 4B69B16582C5; Mon, 19 Jul 2010 12:50:08 +0100 (BST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1279540208;
	bh=qFKZ/hvwahVJ6Io61UyyuF2gRDG3hZ1XA647W7lsk2Q=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=rTfGlA3hcwLArmjavo3tT4EQ1/zg6b831Q//iR5Wuzr+DJyf3bOMcZrZcsPmQFJwT
	 81HJFZrQ1PwrRwju9Rpt8Epzx4Uo3i4ZrTLyoJWb+UYZ0kNIeV0OhOAAY35LYXUhGc
	 hFy166wn1Z4Q/v9r0Na7dhsKRM3OaPpme8AsoRq8=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_127954020820863890"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 19 Jul 2010 12:50:08 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100129.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=C769741A-932B-11DF-AF69-E1B922927A70>
To: John Smith <recipient@example.net>
Message-Id: <20100719115008.4B69B16582C5@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_127954020820863890
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML here.

--_----------=_127954020820863890--


--4B69B16582C5.1279540208/server4.example.co.uk--
