Delivered-To: automated-bounces+6d4df878-a7dc-11df-a9cc-e7a9dd31f8f5@email.example.com
Received: by 10.220.190.129 with SMTP id di1cs35660vcb;
        Sat, 14 Aug 2010 12:45:20 -0700 (PDT)
Received: by 10.142.172.6 with SMTP id u6mr2768790wfe.52.1281815119446;
        Sat, 14 Aug 2010 12:45:19 -0700 (PDT)
Return-Path: <>
Received: from c9mailgw02.example1.com (c9outbound210.example2.com [216.163.188.210])
        by mx.google.com with ESMTP id l15si10125747wfa.37.2010.08.14.12.45.19;
        Sat, 14 Aug 2010 12:45:19 -0700 (PDT)
Received-SPF: neutral (google.com: 216.163.188.210 is neither permitted nor denied by best guess record for domain of c9mailgw02.example1.com) client-ip=216.163.188.210;
Authentication-Results: mx.google.com; spf=neutral (google.com: 216.163.188.210 is neither permitted nor denied by best guess record for domain of c9mailgw02.example1.com) smtp.mail=
Received: from c2mailgw10.example1.com (unknown [10.2.14.10])
	by c9mailgw02.example1.com (Postfix) with ESMTP id A411D586A5894
	for <automated-bounces+6D4DF878-A7DC-11DF-A9CC-E7A9DD31F8F5@email.example.com>; Sat, 14 Aug 2010 12:45:09 -0700 (PDT)
Received: by c2mailgw10.example1.com (Postfix)
	id 562976BAF4164; Sat, 14 Aug 2010 12:45:09 -0700 (PDT)
Date: Sat, 14 Aug 2010 12:45:09 -0700 (PDT)
From: MAILER-DAEMON@mail2world.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+6D4DF878-A7DC-11DF-A9CC-E7A9DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="800006BAF3EA4.1281815109/c2mailgw10.example1.com"
Message-Id: <20100814194509.562976BAF4164@c2mailgw10.example1.com>
X-CTASD-RefID: str=0001.0A090205.4C66F24C.0006,ss=1,fgs=256
X-CTASD-IP: 10.2.14.10
X-CTASD-Sender: MAILER-DAEMON@mail2world.com 
x-ctasd: uncategorized
x-ctasd-vod: uncategorized
x-ctasd-station:

This is a MIME-encapsulated message.

--800006BAF3EA4.1281815109/c2mailgw10.example1.com
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host c2mailgw10.example1.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host m2w-in1.example2.com[74.202.142.24] said: 551
    <recipient@example.net> is a deactivated mailbox (in reply to RCPT TO
    command)

--800006BAF3EA4.1281815109/c2mailgw10.example1.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; c2mailgw10.example1.com
X-Postfix-Queue-ID: 800006BAF3EA4
X-Postfix-Sender: rfc822; automated-bounces+6D4DF878-A7DC-11DF-A9CC-E7A9DD31F8F5@email.example.com
Arrival-Date: Sat, 14 Aug 2010 12:45:02 -0700 (PDT)

Final-Recipient: rfc822; recipient@example.net
Original-Recipient: rfc822;recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; m2w-in1.example2.com
Diagnostic-Code: smtp; 551 <recipient@example.net> is a deactivated mailbox

--800006BAF3EA4.1281815109/c2mailgw10.example1.com
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: from server4.example.co.uk (unknown [94.236.45.212])
	by c2mailgw10.example1.com (Postfix) with ESMTP id 60CB26BAF22F0
	for <recipient@example.net>; Sat, 14 Aug 2010 12:45:02 -0700 (PDT)
Received: by server4.example.co.uk (Postfix, from userid 507)
	id 59E751658201; Sat, 14 Aug 2010 20:45:01 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1281815101279350"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Sat, 14 Aug 2010 20:45:01 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=6D4DF878-A7DC-11DF-A9CC-E7A9DD31F8F5>
To: John Smith <recipient@example.net>
Message-Id: <20100814194501.59E751658201@server4.example.co.uk>
X-CTASD-RefID: str=0001.0A02020A.4C66F241.00A4:SCGSTAT654533,ss=1,pt=SMP_0_RSA_2206166,fgs=1024
X-CTASD-IP: 94.236.45.212
X-CTASD-Sender: fred.bloggs@email.example.com
x-ctasd: uncategorized
x-ctasd-vod: uncategorized
x-ctasd-station:

This is a multi-part message in MIME format.

--_----------=_1281815101279350
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_1281815101279350--


--800006BAF3EA4.1281815109/c2mailgw10.example1.com--
