Return-Path: <MAILER-DAEMON@somehost.example.com>
Received: from mail5.example.net (mail5.example.net [162.95.80.157])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k71J33u5027058
	for <sender@somehost.example.com>; Tue, 1 Aug 2006 12:03:04 -0700
Received: from mail5.example.net (ZixVPM [127.0.0.1])
	by Outbound.example.net (Proprietary) with ESMTP id 8D5FB4C170
	for <sender@somehost.example.com>; Tue,  1 Aug 2006 15:03:03 -0400 (EDT)
Received: from inw2kmr03.corp.example.net (inw2kmr03.corp.example.net [30.37.205.100])
	by mail5.example.net (Proprietary) with ESMTP id 5BB144C16E
	for <sender@somehost.example.com>; Tue,  1 Aug 2006 15:03:03 -0400 (EDT)
Date: Tue, 1 Aug 2006 10:54:01 -0700
MIME-Version: 1.0
X-Mailer: MIME-tools 5.415 (Entity 5.415)
From: Postmaster@example.net
To: Sender Address <sender@example.com>
Subject: DELIVERY FAILURE: User some.name (recipient@example.net) not listed in
 Domino Directory
X-PMX-Version: 4.7.1.128075, Antispam-Engine: 2.4.0.264935, Antispam-Data: 2006.8.1.105433
X-OriginalArrivalTime: 01 Aug 2006 19:02:59.0038 (UTC) FILETIME=[1AC6FFE0:01C6B59D]
X-MIMETrack: Itemize by SMTP Server on INW2KMR03/AICI/US(Release 6.5.5 HF30|January 10, 2006) at
 08/01/2006 03:03:02 PM,
	Serialize by Router on INW2KMR03/AICI/US(Release 6.5.5 HF30|January 10, 2006) at
 08/01/2006 03:03:03 PM,
	Serialize complete at 08/01/2006 03:03:03 PM
Message-ID: <OF3B2E9B90.C44450A0-ON852571BD.0068A601-852571BD.0068A654@Anthem.com>
Content-Type: Text/Plain
Content-Transfer-Encoding: 8bit
X-MIME-Autoconverted: from base64 to 8bit by somehost.example.com id k71J33u5027058

Your message

  Subject: Test Bounce

was not delivered to:

  recipient@example.net

because:

  User some.name (recipient@example.net) not listed in Domino Directory


