Return-Path: <MAILER-DAEMON@somehost.example.com>
Received: from smtp2.dnb.com (smtp2.dnb.com [204.254.175.103])
	by somehost.example.com (8.12.11/8.12.11) with ESMTP id k1F9PaLe021541
	for <sender@example.com>; Wed, 15 Feb 2006 01:25:36 -0800
Received: from unknown (HELO relay.us.dnb.com) ([159.137.225.58])
  by smtp2.dnb.com with ESMTP; 15 Feb 2006 04:32:09 -0500
Received: from smtp-gw.us.dnb.com (smtp-gw.us.dnb.com [10.158.22.127])
	by relay.us.dnb.com (8.12.9/8.12.9) with SMTP id k1F9PRKr042136
	for <sender@example.com>; Wed, 15 Feb 2006 04:25:34 -0500 (EST)
Received: from exbhbhbh04.us.dnb.com ([159.137.224.39])
 by smtp-gw.us.dnb.com (SAVSMTP 3.1.0.29) with SMTP id M2006021504253404247
 for <sender@example.com>; Wed, 15 Feb 2006 04:25:34 -0500
Received: by exbhbhbh04.us.dbisna.com with Internet Mail Service (5.5.2657.72)
	id <C5C0P4JG>; Wed, 15 Feb 2006 04:25:33 -0500
Message-ID: <71DFAC6F3166D711B6DB0008C74CCDF2391EBE34@exbhbhbh01.us.dbisna.com>
From: System Administrator <postmaster@example.net>
To: sender@example.com
Subject: Undeliverable: Some test message
Date: Wed, 15 Feb 2006 04:25:33 -0500
MIME-Version: 1.0
X-Mailer: Internet Mail Service (5.5.2657.72)
X-MS-Embedded-Report: 
Content-Type: multipart/mixed;
	boundary="----_=_NextPart_000_01C63211.C564A2DC"

This message is in MIME format. Since your mail reader does not understand
this format, some or all of this message may not be legible.

------_=_NextPart_000_01C63211.C564A2DC
Content-Type: text/plain;
	charset="iso-8859-1"

Your message

  To:      recipient
  Subject: Some test message
  Sent:    Wed, 15 Feb 2006 03:53:57 -0500

did not reach the following recipient(s):

RECIPIENT@EXAMPLE.NET on Wed, 15 Feb 2006 04:25:29 -0500
    The recipient name is not recognized
	The MTS-ID of the original message is: c=us;a=
;p=dnb;l=EXBHBHBH0106021509251DBVZ38X
    MSEXCH:IMS:DNB:USEAST:EXBHBHBH01 0 (000C05A6) Unknown Recipient



------_=_NextPart_000_01C63211.C564A2DC
Content-Type: message/rfc822

Message-ID: <200602150853.k1F8rvvX006268@somehost.example.com>
From: Sender <noreply@example.com>
To: recipient <recipient@example.net>
Subject: Some test message
Date: Wed, 15 Feb 2006 03:53:57 -0500
MIME-Version: 1.0
X-Mailer: Internet Mail Service (5.5.2657.72)
X-MS-Embedded-Report: 
X-BrightmailFiltered: true
X-Brightmail-Tracker: AAAAAA==
Errors-To: noreply@example.com
Content-Type: text/plain;
	charset="iso-8859-1"

Text here

------_=_NextPart_000_01C63211.C564A2DC--
