Delivered-To: automated-bounces+a3b9144e-89c6-11df-bd3f-fea09e3e4bb4@email.example.com
Received: by 10.224.28.133 with SMTP id m5cs120102qac;
        Wed, 7 Jul 2010 05:53:37 -0700 (PDT)
Received: by 10.227.135.66 with SMTP id m2mr4962129wbt.187.1278507216621;
        Wed, 07 Jul 2010 05:53:36 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id k17si14625328wbp.82.2010.07.07.05.53.36;
        Wed, 07 Jul 2010 05:53:36 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 0DBC816586A2; Wed,  7 Jul 2010 13:53:36 +0100 (BST)
Date: Wed,  7 Jul 2010 13:53:36 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+A3B9144E-89C6-11DF-BD3F-FEA09E3E4BB4@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="CFE3F165869A.1278507216/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100707125336.0DBC816586A2@server4.example.co.uk>

This is a MIME-encapsulated message.

--CFE3F165869A.1278507216/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred@test.co.uk>: host mx.junkemailfilter.com[65.49.42.61] said:
    550-REJECTED - Server at [test.co.uk] (NOT JUNKEMAILFILTER) rejected
    message - 550 550 65.49.42.68 is not allowed to send mail from
    email.example.com (in reply to RCPT TO command)

--CFE3F165869A.1278507216/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: CFE3F165869A
X-Postfix-Sender: rfc822; automated-bounces+A3B9144E-89C6-11DF-BD3F-FEA09E3E4BB4@email.example.com
Arrival-Date: Wed,  7 Jul 2010 13:53:28 +0100 (BST)

Final-Recipient: rfc822; fred@test.co.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx.junkemailfilter.com
Diagnostic-Code: smtp; 550-REJECTED - Server at [test.co.uk] (NOT
    JUNKEMAILFILTER) rejected message - 550 550 65.49.42.68 is not allowed to
    send mail from email.example.com

--CFE3F165869A.1278507216/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 508)
	id CFE3F165869A; Wed,  7 Jul 2010 13:53:28 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_12785072081058321"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 7 Jul 2010 13:53:28 +0100
From: John Smith <john.smith@email.example.com>
Subject: fred
X-Campaignid: example20100423.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=A3B9144E-89C6-11DF-BD3F-FEA09E3E4BB4>
To: Fred Blogs <fred@test.co.uk>
Message-Id: <20100707125328.CFE3F165869A@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_12785072081058321
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text goes here. 
 
--_----------=_12785072081058321
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here

--_----------=_12785072081058321--


--CFE3F165869A.1278507216/server4.example.co.uk--
