Delivered-To: automated-bounces+0b3e8a94-a6e2-11df-a9cb-fe43b3a13c11@email.example.com
Received: by 10.220.190.129 with SMTP id di1cs220767vcb;
        Fri, 13 Aug 2010 10:10:19 -0700 (PDT)
Received: by 10.213.3.83 with SMTP id 19mr1925362ebm.49.1281719417811;
        Fri, 13 Aug 2010 10:10:17 -0700 (PDT)
Return-Path: <>
Received: from server2.example.co.uk (server2.example.co.uk [94.236.45.210])
        by mx.google.com with ESMTP id v44si7576420eeh.57.2010.08.13.10.10.17;
        Fri, 13 Aug 2010 10:10:17 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server2.example.co.uk designates 94.236.45.210 as permitted sender) client-ip=94.236.45.210;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server2.example.co.uk designates 94.236.45.210 as permitted sender) smtp.mail=
Received: by server2.example.co.uk (Postfix)
	id 3DB0FB581A5; Fri, 13 Aug 2010 18:10:17 +0100 (BST)
Date: Fri, 13 Aug 2010 18:10:17 +0100 (BST)
From: MAILER-DAEMON@server2.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+0B3E8A94-A6E2-11DF-A9CB-FE43B3A13C11@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="A11DDB5819F.1281719417/server2.example.co.uk"
Message-Id: <20100813171017.3DB0FB581A5@server2.example.co.uk>

This is a MIME-encapsulated message.

--A11DDB5819F.1281719417/server2.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server2.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mxin.name-services.com[69.64.157.73] said: 550 5.7.1 No
    mailbox found (in reply to RCPT TO command)

--A11DDB5819F.1281719417/server2.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server2.example.co.uk
X-Postfix-Queue-ID: A11DDB5819F
X-Postfix-Sender: rfc822; automated-bounces+0B3E8A94-A6E2-11DF-A9CB-FE43B3A13C11@email.example.com
Arrival-Date: Fri, 13 Aug 2010 14:52:42 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.7.1
Remote-MTA: dns; mxin.name-services.com
Diagnostic-Code: smtp; 550 5.7.1 No mailbox found

--A11DDB5819F.1281719417/server2.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by server2.example.co.uk (Postfix, from userid 507)
	id A11DDB5819F; Fri, 13 Aug 2010 14:52:42 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_128170756219470"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Fri, 13 Aug 2010 14:52:42 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=0B3E8A94-A6E2-11DF-A9CB-FE43B3A13C11>
To: John Smith <recipient@example.net>
Message-Id: <20100813135242.A11DDB5819F@server2.example.co.uk>

--A11DDB5819F.1281719417/server2.example.co.uk--
