Delivered-To: automated-bounces+84786f9c-7c4e-11df-bdf4-7d4cdd31f8f5@email.example.com
Received: by 10.216.157.72 with SMTP id n50cs38472wek;
        Sun, 20 Jun 2010 02:30:53 -0700 (PDT)
Received: by 10.227.133.132 with SMTP id f4mr3200660wbt.189.1277026253410;
        Sun, 20 Jun 2010 02:30:53 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id o42si32496522wbv.72.2010.06.20.02.30.53;
        Sun, 20 Jun 2010 02:30:53 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 43C7F16585EA; Sun, 20 Jun 2010 10:30:53 +0100 (BST)
Date: Sun, 20 Jun 2010 10:30:53 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+84786F9C-7C4E-11DF-BDF4-7D4CDD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="9D90616585E9.1277026253/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100620093053.43C7F16585EA@server4.example.co.uk>

This is a MIME-encapsulated message.

--9D90616585E9.1277026253/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<f.b@a.b.c>: Name service error for name=a.b.c
    type=MX: Malformed or unexpected name server reply

--9D90616585E9.1277026253/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 9D90616585E9
X-Postfix-Sender: rfc822; automated-bounces+84786F9C-7C4E-11DF-BDF4-7D4CDD31F8F5@email.example.com
Arrival-Date: Sun, 20 Jun 2010 10:30:51 +0100 (BST)

Final-Recipient: rfc822; f.b@a.b.c
Action: failed
Status: 5.4.4
Diagnostic-Code: X-Postfix; Name service error for name=a.b.c
    type=MX: Malformed or unexpected name server reply

--9D90616585E9.1277026253/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 9D90616585E9; Sun, 20 Jun 2010 10:30:51 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_12770262514021318"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Sun, 20 Jun 2010 10:30:51 +0100
From: John Smith <john.smith@email.example.com>
Subject: test
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=84786F9C-7C4E-11DF-BDF4-7D4CDD31F8F5>
To: f.b <f.b@a.b.c>
Message-Id: <20100620093051.9D90616585E9@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_12770262514021318
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html

HTML goes here
--_----------=_12770262514021318--


--9D90616585E9.1277026253/server4.example.co.uk--
