Delivered-To: automated-bounces+96bfaba2-9341-11df-b62f-b3f1baa35b08@email.example.com
Received: by 10.224.45.67 with SMTP id d3cs114412qaf;
        Mon, 19 Jul 2010 07:26:18 -0700 (PDT)
Received: by 10.227.153.211 with SMTP id l19mr4073143wbw.224.1279549577365;
        Mon, 19 Jul 2010 07:26:17 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id l6si6543356wba.23.2010.07.19.07.26.16;
        Mon, 19 Jul 2010 07:26:17 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id ACDE7165835E; Mon, 19 Jul 2010 15:26:16 +0100 (BST)
Date: Mon, 19 Jul 2010 15:26:16 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+96BFABA2-9341-11DF-B62F-B3F1BAA35B08@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="A7B931658352.1279549576/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100719142616.ACDE7165835E@server4.example.co.uk>

This is a MIME-encapsulated message.

--A7B931658352.1279549576/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host smtp-mx006.example.net[17.148.17.16] said: 550 5.1.6 recipient
    no longer on server: recipient@example.net (in reply to RCPT TO command)

--A7B931658352.1279549576/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: A7B931658352
X-Postfix-Sender: rfc822; automated-bounces+96BFABA2-9341-11DF-B62F-B3F1BAA35B08@email.example.com
Arrival-Date: Mon, 19 Jul 2010 15:26:15 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.1.6
Remote-MTA: dns; smtp-mx006.example.net
Diagnostic-Code: smtp; 550 5.1.6 recipient no longer on server: recipient@example.net

--A7B931658352.1279549576/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 505)
	id A7B931658352; Mon, 19 Jul 2010 15:26:15 +0100 (BST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1279549575;
	bh=2rTlZd3Un4WZ03TTGcDmFJXCgKILGAVCbdo1KWxzl9g=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=JZpOHWM8dkDzZ8tV6pJlaM8Yui6fF58VUOJYMEBSLfOTZx/qt1uEpH68bO0djS/om
	 VFfwMnc4+JXFqNpUnfWP5PwZv+oh06kbUqszAlWK6PofhhpOLNi5c3pn87pKWOL9FC
	 jK0PIsHzcGTX9Nu2u9nPMTF58taPKpECHJXsC8Pc=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_127954957589061263"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 19 Jul 2010 15:26:15 +0100
From: Fred Bloggs <julia.stevens@email.example.com>
Subject: foo
X-Campaignid: example20100423.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=96BFABA2-9341-11DF-B62F-B3F1BAA35B08>
To: charlotte wilson <recipient@example.net>
Message-Id: <20100719142615.A7B931658352@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_127954957589061263
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

text

--_----------=_127954957589061263
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

html

--_----------=_127954957589061263--


--A7B931658352.1279549576/server4.example.co.uk--
