Delivered-To: automated-bounces+8060e386-35c1-11df-a7dc-90ebaee270fa@email.example.com
Received: by 10.216.178.78 with SMTP id e56cs128460wem;
        Mon, 22 Mar 2010 07:45:37 -0700 (PDT)
Received: by 10.204.175.9 with SMTP id v9mr1990768bkz.79.1269269136677;
        Mon, 22 Mar 2010 07:45:36 -0700 (PDT)
Return-Path: <>
Received: from server2.example.co.uk (server2.example.co.uk [94.236.45.210])
        by mx.google.com with ESMTP id 5si11375492bkn.0.2010.03.22.07.45.36;
        Mon, 22 Mar 2010 07:45:36 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server2.example.co.uk designates 94.236.45.210 as permitted sender) client-ip=94.236.45.210;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server2.example.co.uk designates 94.236.45.210 as permitted sender) smtp.mail=
Received: by server2.example.co.uk (Postfix)
	id 284D3B581E0; Mon, 22 Mar 2010 14:45:36 +0000 (GMT)
Date: Mon, 22 Mar 2010 14:45:36 +0000 (GMT)
From: MAILER-DAEMON@server2.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+8060E386-35C1-11DF-A7DC-90EBAEE270FA@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="7B0EBB581D3.1269269136/server2.example.co.uk"
Message-Id: <20100322144536.284D3B581E0@server2.example.co.uk>

This is a MIME-encapsulated message.

--7B0EBB581D3.1269269136/server2.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server2.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<a@b.c>: message size 8596800 exceeds size limit 5242880 of
    server mail9.d.e[216.185.34.5]

--7B0EBB581D3.1269269136/server2.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server2.example.co.uk
X-Postfix-Queue-ID: 7B0EBB581D3
X-Postfix-Sender: rfc822; automated-bounces+8060E386-35C1-11DF-A7DC-90EBAEE270FA@email.example.com
Arrival-Date: Mon, 22 Mar 2010 14:45:24 +0000 (GMT)

Final-Recipient: rfc822; a@b.c
Action: failed
Status: 5.3.4
Diagnostic-Code: X-Postfix; message size 8596800 exceeds size limit 5242880 of
    server mail9.d.e[216.185.34.5]

--7B0EBB581D3.1269269136/server2.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by server2.example.co.uk (Postfix, from userid 507)
	id 7B0EBB581D3; Mon, 22 Mar 2010 14:45:24 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1269269124;
	bh=FvFGwOXRZBsK129YN76Cwcp9YMKVYLLQBEIuNtfI4IE=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=LCB+09KMvXeT9eibfcCPJcmDoDUHUkgi+Tp9nWTciTj37hY0cBpPDwSpEGfMh8ppF
	 5M3MZlSPCz4iZN+QkPq9OLRHWEucl+UMRuYDJoRHlPEuk73igita6zAdKacVCKVTlc
	 Ygm7UqQOVEfUmJgR8nexEYtQIiPFKS91raYV0YD4=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_12692691043250"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 22 Mar 2010 14:45:04 +0000
From: Customer Services <customerservices@email.example.com>
Subject: blah
List-Unsubscribe: <http://www.example.co.uk/unsubscribe.epl?uuid=8060E386-35C1-11DF-A7DC-90EBAEE270FA>
To: a d <a@b.c>
Message-Id: <20100322144524.7B0EBB581D3@server2.example.co.uk>

--7B0EBB581D3.1269269136/server2.example.co.uk--
