Delivered-To: automated-bounces+452b07fa-a375-11e1-8718-8fa968fc6771@email.example.com
Received: by 10.52.101.202 with SMTP id fi10csp34095vdb;
        Mon, 21 May 2012 11:47:18 -0700 (PDT)
Received: by 10.180.74.68 with SMTP id r4mr27680726wiv.13.1337626038139;
        Mon, 21 May 2012 11:47:18 -0700 (PDT)
Return-Path: <>
Received: from mailout04.rmx.de (mailout04.rmx.de. [94.199.90.94])
        by mx.google.com with ESMTPS id g5si282460wel.159.2012.05.21.11.47.17
        (version=TLSv1/SSLv3 cipher=OTHER);
        Mon, 21 May 2012 11:47:18 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of mailout04.rmx.de designates 94.199.90.94 as permitted sender) client-ip=94.199.90.94;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of mailout04.rmx.de designates 94.199.90.94 as permitted sender) smtp.mail=
Received: from kdin02.retarus.de (kdin02.retarus.de [172.19.17.49] (may be forged))
	by mailout04.rmx.de (8.14.4/8.14.5/retarus.custom) with ESMTP id q4LIlCJH031609
	(version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-SHA bits=256 verify=OK)
	for <automated-bounces+452B07FA-A375-11E1-8718-8FA968FC6771@email.example.com>; Mon, 21 May 2012 20:47:13 +0200
Received: from DDE2ERLMI02E.res.tld ([193.99.42.56])
	by kdin02.retarus.de (8.14.5/8.14.2/retarus.custom) with ESMTP id q4LIl9Hp001520
	(version=TLSv1/SSLv3 cipher=AES128-SHA bits=128 verify=FAIL)
	for <automated-bounces+452B07FA-A375-11E1-8718-8FA968FC6771@email.example.com>; Mon, 21 May 2012 20:47:10 +0200
MIME-Version: 1.0
From: <postmaster@sample.net>
To: <automated-bounces+452B07FA-A375-11E1-8718-8FA968FC6771@email.example.com>
Date: Mon, 21 May 2012 20:47:09 +0200
Content-Type: multipart/report; report-type=delivery-status;
	boundary="750e84e3-a127-4bd8-800c-aee48611c03e"
Content-Language: en-US
Message-ID: <e7abc877-7bac-4b76-b8ee-22b65b0c4ec6@internal.sample.net>
In-Reply-To: <20120521184627.050AD154809F@admin1.example.co.uk>
References: <20120521184627.050AD154809F@admin1.example.co.uk>
Subject: Undeliverable: foo
X-RMX-ID: 20120521-204710-q4LIl9Hp001520-0@kdin02
X-RMX-TRACE: 2012-05-21 20:47:11 RmxMSO@kdin02/mailcc05 [0.4s] 20120521-204710-q4LIl9Hp001520-0@kdin02 0:00:01
X-RMX-TRACE: 2012-05-21 20:47:10 KdIn@kdin02/mailcc05 [0.2s] 20120521-204710-q4LIl9Hp001520-0@kdin02 0:00:00

--750e84e3-a127-4bd8-800c-aee48611c03e
Content-Type: multipart/alternative; differences=Content-Type;
	boundary="8301eb61-02a2-4e89-8bc7-511e98c6cd16"

--8301eb61-02a2-4e89-8bc7-511e98c6cd16
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

This message wasn't delivered to anyone because it's too large. The limit i=
s 14 MB. This message is 18 MB.

John Smith (john.smith@sample.net)<mailto:john.smith@demat=
ic.com>
This message won't be sent because it's too large.







Diagnostic information for administrators:

Generating server: internal.sample.net

john.smith@sample.net
#550 5.2.3 RESOLVER.RST.SendSizeLimit.Org; message too large for this organ=
ization ##

Original message headers:

Received: from kdout02.retarus.de (172.31.115.1) by DDE2ERLMV01E.res.tld
 (172.31.74.244) with Microsoft SMTP Server id 14.1.355.2; Mon, 21 May 2012
 20:46:59 +0200
Received: from [172.19.17.2] (HELO mailin02.retarus.de)  by kdout02.retarus=
.de
 (CommuniGate Pro SMTP 5.2.0 _community_)  with ESMTPS id 829880041 for
 john.smith@sample.net; Mon, 21 May 2012 20:46:55 +0200
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212]) =
     by
 mailin02.retarus.de (8.14.5/8.14.2/retarus.custom) with ESMTP id
 q4LIkb1K000686 for <john.smith@sample.net>; Mon, 21 May 2012 20:46:=
37
 +0200
Received: by admin1.example.co.uk (Postfix, from userid 507)    id 050AD154=
809F;
 Mon, 21 May 2012 19:46:26 +0100 (BST)
DKIM-Signature: v=3D1; a=3Drsa-sha256; c=3Drelaxed/relaxed; d=3Demail.diano=
mi.com;
        s=3Ddefault10; t=3D1337625987;
        bh=3DqzUop7WCbFQyE0hjGM2a5b9G6Jn86Gj3lQ3ToIgyW8k=3D;
        h=3DMIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
         Subject:List-Unsubscribe:To:Message-Id;
        b=3DjmyDqvFN0+Y0EC7lOie/7xjotuHCXGqKA3h7gzxywhd/q8gA5/2/12mbQVUM3gp=
ut
         A00oSe0ETXAeRbkNvydMsFznrhI0AmBlYVsH4iAr9nUHC9xKIHo0Ch5p5xZiUvoBGB
         5MvDefAU0A7bjxjwjmxKvp9vfwjRn6iByOIg8e2I=3D
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary=3D"_----------=3D_133762598614638=
0"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Mon, 21 May 2012 19:46:26 +0100
From: fred.bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=3D45=
2B07FA-A375-11E1-8718-8FA968FC6771>
To: John Smith <john.smith@sample.net>
Message-ID: <20120521184627.050AD154809F@admin1.example.co.uk>
X-RMX-ID: 20120521-204637-q4LIkb1K000686-0@mailin02
X-RMX-TRACE: 2012-05-21 20:46:54 Meta2011@mailin02/mailcc23 [4.4s] 20120521=
-204637-q4LIkb1K000686-0@mailin02 0:00:04
X-RMX-TRACE: 2012-05-21 20:46:43 RmxMSI@mailin02/mailcc01 [0.4s] 20120521-2=
04637-q4LIkb1K000686-0@mailin02 0:00:06
X-RMX-TRACE: 2012-05-21 20:46:43 RmxDf@mailin02/mailcc14 [5.8s] 20120521-20=
4637-q4LIkb1K000686-0@mailin02 0:00:05
X-RMX-RQ: 100
X-RMX-RC: 4
X-RMX-ADVCFG-PRG: Meta2011Program.00298@2012-05-11
X-RMX-Spam: Gauge=3DXXI, Probability=3D21%, Report=3D'
 IMGSPAM_BODY! 1.0, SUSPECT_LIST_HEADERS! 0.8, IMGSPAM_BODY_1! 0.3, HTML_70=
_90! 0.2, BAYES_40_49! 0, RMX_RQ_100_LOW+ 0, BODYTEXTH_SIZE_10000_LESS 0, L=
INK_TO_IMAGE 0, PDF_ATTACHED 0, PDF_ATTACHED_2 0, SPF_PASS 0, __ANY_URI 0, =
__CANPHARM_UNSUB_LINK 0, __CT 0, __CTE 0, __CTYPE_HAS_BOUNDARY 0, __CTYPE_M=
ULTIPART 0, __EXTRA_MPART_TYPE_N1 0, __HAS_HTML 0, __HAS_LIST_HEADER 0, __H=
AS_LIST_UNSUBSCRIBE 0, __HAS_MSGID 0, __HAS_X_MAILER 0, __IMGSPAM_BODY 0, _=
_IMGSPAM_BODY_1 0, __MIME_HTML 0, __MIME_VERSION 0, __SANE_MSGID 0, __SUBJ_=
ALPHA_END 0, __TAG_EXISTS_BODY 0, __TAG_EXISTS_HTML 0, __TO_MALFORMED_2 0, =
__URI_NO_MAILTO 0, __URI_NS , __XMAILER_MIME_LITE 0, __bl.spamcop.net_ERROR=
 , __dnsbl.njabl.org_ERROR , __dnsbl.sorbs.net_ERROR , __ix.dnsbl.manitu.ne=
t_ERROR , __virbl.dnsbl.bit.nl_ERROR '
Return-Path:
 automated-bounces+452B07FA-A375-11E1-8718-8FA968FC6771@email.example.com


--8301eb61-02a2-4e89-8bc7-511e98c6cd16
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html>
<Head></head><body>
<p><b><font color=3D"#000066" size=3D"3" face=3D"Arial">This message wasn't=
 delivered to anyone because it's too large. The limit is 14 MB. This messa=
ge is 18 MB.</font></b></p>
<font color=3D"#000000" size=3D"2" face=3D"Tahoma"><p><a href=3D"mailto:wil=
liam.j.miller@sample.net">John Smith (john.smith@sample.net)</a=
><br>
</font>
<font color=3D"#000000" size=3D"3" face=3D"Arial">This message won't be sen=
t because it's too large.</font>
<font color=3D"#000000" size=3D"2" face=3D"Tahoma"><br>
</p>
</font>
<br><br><br><br><br><br>
<font color=3D"#808080" size=3D"2" face=3D"Tahoma"><p><b>Diagnostic informa=
tion for administrators:</b></p>
<p>Generating server: internal.sample.net</p>
<p>john.smith@sample.net<br>
 #550 5.2.3 RESOLVER.RST.SendSizeLimit.Org; message too large for this orga=
nization ##</p>
<p>Original message headers:</p>
<pre>Received: from kdout02.retarus.de (172.31.115.1) by DDE2ERLMV01E.res.t=
ld
 (172.31.74.244) with Microsoft SMTP Server id 14.1.355.2; Mon, 21 May 2012
 20:46:59 +0200
Received: from [172.19.17.2] (HELO mailin02.retarus.de)  by kdout02.retarus=
.de
 (CommuniGate Pro SMTP 5.2.0 _community_)  with ESMTPS id 829880041 for
 john.smith@sample.net; Mon, 21 May 2012 20:46:55 +0200
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])	=
by
 mailin02.retarus.de (8.14.5/8.14.2/retarus.custom) with ESMTP id
 q4LIkb1K000686	for &lt;john.smith@sample.net&gt;; Mon, 21 May 2012 =
20:46:37
 +0200
Received: by admin1.example.co.uk (Postfix, from userid 507)	id 050AD154809=
F;
 Mon, 21 May 2012 19:46:26 +0100 (BST)
DKIM-Signature: v=3D1; a=3Drsa-sha256; c=3Drelaxed/relaxed; d=3Demail.diano=
mi.com;
	s=3Ddefault10; t=3D1337625987;
	bh=3DqzUop7WCbFQyE0hjGM2a5b9G6Jn86Gj3lQ3ToIgyW8k=3D;
	h=3DMIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=3DjmyDqvFN0+Y0EC7lOie/7xjotuHCXGqKA3h7gzxywhd/q8gA5/2/12mbQVUM3gput
	 A00oSe0ETXAeRbkNvydMsFznrhI0AmBlYVsH4iAr9nUHC9xKIHo0Ch5p5xZiUvoBGB
	 5MvDefAU0A7bjxjwjmxKvp9vfwjRn6iByOIg8e2I=3D
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary=3D&quot;_----------=3D_1337625986=
146380&quot;
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Mon, 21 May 2012 19:46:26 +0100
From: fred.bloggs &lt;fred.bloggs@email.example.com&gt;
Subject: foo
List-Unsubscribe: &lt;http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=
=3D452B07FA-A375-11E1-8718-8FA968FC6771&gt;
To: John Smith &lt;john.smith@sample.net&gt;
Message-ID: &lt;20120521184627.050AD154809F@admin1.example.co.uk&gt;
X-RMX-ID: 20120521-204637-q4LIkb1K000686-0@mailin02
X-RMX-TRACE: 2012-05-21 20:46:54 Meta2011@mailin02/mailcc23 [4.4s] 20120521=
-204637-q4LIkb1K000686-0@mailin02 0:00:04
X-RMX-TRACE: 2012-05-21 20:46:43 RmxMSI@mailin02/mailcc01 [0.4s] 20120521-2=
04637-q4LIkb1K000686-0@mailin02 0:00:06
X-RMX-TRACE: 2012-05-21 20:46:43 RmxDf@mailin02/mailcc14 [5.8s] 20120521-20=
4637-q4LIkb1K000686-0@mailin02 0:00:05
X-RMX-RQ: 100
X-RMX-RC: 4
X-RMX-ADVCFG-PRG: Meta2011Program.00298@2012-05-11
X-RMX-Spam: Gauge=3DXXI, Probability=3D21%, Report=3D'
 IMGSPAM_BODY! 1.0, SUSPECT_LIST_HEADERS! 0.8, IMGSPAM_BODY_1! 0.3, HTML_70=
_90! 0.2, BAYES_40_49! 0, RMX_RQ_100_LOW+ 0, BODYTEXTH_SIZE_10000_LESS 0, L=
INK_TO_IMAGE 0, PDF_ATTACHED 0, PDF_ATTACHED_2 0, SPF_PASS 0, __ANY_URI 0, =
__CANPHARM_UNSUB_LINK 0, __CT 0, __CTE 0, __CTYPE_HAS_BOUNDARY 0, __CTYPE_M=
ULTIPART 0, __EXTRA_MPART_TYPE_N1 0, __HAS_HTML 0, __HAS_LIST_HEADER 0, __H=
AS_LIST_UNSUBSCRIBE 0, __HAS_MSGID 0, __HAS_X_MAILER 0, __IMGSPAM_BODY 0, _=
_IMGSPAM_BODY_1 0, __MIME_HTML 0, __MIME_VERSION 0, __SANE_MSGID 0, __SUBJ_=
ALPHA_END 0, __TAG_EXISTS_BODY 0, __TAG_EXISTS_HTML 0, __TO_MALFORMED_2 0, =
__URI_NO_MAILTO 0, __URI_NS , __XMAILER_MIME_LITE 0, __bl.spamcop.net_ERROR=
 , __dnsbl.njabl.org_ERROR , __dnsbl.sorbs.net_ERROR , __ix.dnsbl.manitu.ne=
t_ERROR , __virbl.dnsbl.bit.nl_ERROR '
Return-Path:
 automated-bounces+452B07FA-A375-11E1-8718-8FA968FC6771@email.example.com
</pre>
</font>
</body>
</html>=

--8301eb61-02a2-4e89-8bc7-511e98c6cd16--

--750e84e3-a127-4bd8-800c-aee48611c03e
Content-Type: message/delivery-status

Reporting-MTA: dns;internal.sample.net
Received-From-MTA: dns;kdout02.retarus.de
Arrival-Date: Mon, 21 May 2012 18:46:59 +0000

Final-Recipient: rfc822;john.smith@sample.net
Action: failed
Status: 5.2.3
Diagnostic-Code: smtp;550 5.2.3 RESOLVER.RST.SendSizeLimit.Org; message too large for this organization
X-Display-Name: John Smith


--750e84e3-a127-4bd8-800c-aee48611c03e
Content-Type: text/rfc822-headers

Received: from kdout02.retarus.de (172.31.115.1) by DDE2ERLMV01E.res.tld
 (172.31.74.244) with Microsoft SMTP Server id 14.1.355.2; Mon, 21 May 2012
 20:46:59 +0200
Received: from [172.19.17.2] (HELO mailin02.retarus.de)  by kdout02.retarus.de
 (CommuniGate Pro SMTP 5.2.0 _community_)  with ESMTPS id 829880041 for
 john.smith@sample.net; Mon, 21 May 2012 20:46:55 +0200
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])	by
 mailin02.retarus.de (8.14.5/8.14.2/retarus.custom) with ESMTP id
 q4LIkb1K000686	for <john.smith@sample.net>; Mon, 21 May 2012 20:46:37
 +0200
Received: by admin1.example.co.uk (Postfix, from userid 507)	id 050AD154809F;
 Mon, 21 May 2012 19:46:26 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1337625986146380"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Mon, 21 May 2012 19:46:26 +0100
From: fred.bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=452B07FA-A375-11E1-8718-8FA968FC6771>
To: John Smith <john.smith@sample.net>
Message-ID: <20120521184627.050AD154809F@admin1.example.co.uk>
X-RMX-ID: 20120521-204637-q4LIkb1K000686-0@mailin02
X-RMX-TRACE: 2012-05-21 20:46:54 Meta2011@mailin02/mailcc23 [4.4s] 20120521-204637-q4LIkb1K000686-0@mailin02 0:00:04
X-RMX-TRACE: 2012-05-21 20:46:43 RmxMSI@mailin02/mailcc01 [0.4s] 20120521-204637-q4LIkb1K000686-0@mailin02 0:00:06
X-RMX-TRACE: 2012-05-21 20:46:43 RmxDf@mailin02/mailcc14 [5.8s] 20120521-204637-q4LIkb1K000686-0@mailin02 0:00:05
X-RMX-RQ: 100
X-RMX-RC: 4
X-RMX-ADVCFG-PRG: Meta2011Program.00298@2012-05-11
X-RMX-Spam: Gauge=XXI, Probability=21%, Report='
 IMGSPAM_BODY! 1.0, SUSPECT_LIST_HEADERS! 0.8, IMGSPAM_BODY_1! 0.3, HTML_70_90! 0.2, BAYES_40_49! 0, RMX_RQ_100_LOW+ 0, BODYTEXTH_SIZE_10000_LESS 0, LINK_TO_IMAGE 0, PDF_ATTACHED 0, PDF_ATTACHED_2 0, SPF_PASS 0, __ANY_URI 0, __CANPHARM_UNSUB_LINK 0, __CT 0, __CTE 0, __CTYPE_HAS_BOUNDARY 0, __CTYPE_MULTIPART 0, __EXTRA_MPART_TYPE_N1 0, __HAS_HTML 0, __HAS_LIST_HEADER 0, __HAS_LIST_UNSUBSCRIBE 0, __HAS_MSGID 0, __HAS_X_MAILER 0, __IMGSPAM_BODY 0, __IMGSPAM_BODY_1 0, __MIME_HTML 0, __MIME_VERSION 0, __SANE_MSGID 0, __SUBJ_ALPHA_END 0, __TAG_EXISTS_BODY 0, __TAG_EXISTS_HTML 0, __TO_MALFORMED_2 0, __URI_NO_MAILTO 0, __URI_NS , __XMAILER_MIME_LITE 0, __bl.spamcop.net_ERROR , __dnsbl.njabl.org_ERROR , __dnsbl.sorbs.net_ERROR , __ix.dnsbl.manitu.net_ERROR , __virbl.dnsbl.bit.nl_ERROR '
Return-Path:
 automated-bounces+452B07FA-A375-11E1-8718-8FA968FC6771@email.example.com
X-MS-Exchange-Organization-OriginalArrivalTime: 21 May 2012 18:46:59.3304
 (UTC)
X-MS-Exchange-Forest-ArrivalHubServer: DDE2ERLMI02E.res.tld
X-MS-Exchange-Organization-OriginalClientIPAddress: 172.31.115.1
X-MS-Exchange-Organization-OriginalServerIPAddress: 172.31.74.244
X-MS-Exchange-Organization-AuthSource: DDE2ERLMI02E.res.tld
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-Exchange-Organization-Cross-Premises-Headers-Processed:
 DDE2ERLMI02E.res.tld
X-MS-Exchange-Organization-OriginalSize: 18877220
X-MS-Exchange-Forest-MessageScope: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Organization-MessageScope: 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Organization-HygienePolicy: Standard

--750e84e3-a127-4bd8-800c-aee48611c03e--
