Delivered-To: automated-bounces+8c55289c-b151-11e1-ac6a-ccb6c6f8f3bb@email.sample.com
Received: by 10.52.101.202 with SMTP id fi10csp7070vdb;
        Fri, 8 Jun 2012 03:07:16 -0700 (PDT)
Received: by 10.224.111.139 with SMTP id s11mr5838291qap.78.1339150035870;
        Fri, 08 Jun 2012 03:07:15 -0700 (PDT)
Return-Path: <>
Received: from admin1.sample.co.uk (admin1.sample.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id n13si9475927wee.27.2012.06.08.03.07.15;
        Fri, 08 Jun 2012 03:07:15 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.sample.co.uk (Postfix)
	id 04B996512B6; Fri,  8 Jun 2012 11:07:15 +0100 (BST)
Date: Fri,  8 Jun 2012 11:07:15 +0100 (BST)
From: MAILER-DAEMON@admin1.sample.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+8C55289C-B151-11E1-AC6A-CCB6C6F8F3BB@email.sample.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="257DF6512BF.1339150035/admin1.sample.co.uk"
Message-Id: <20120608100715.04B996512B6@admin1.sample.co.uk>

This is a MIME-encapsulated message.

--257DF6512BF.1339150035/admin1.sample.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.sample.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.com>: host
    cust1793-1.in.mailcontrol.com[208.87.233.190] said: 554 5.7.1 Message
    Rejected Class=size limit=15728640 Subclass=reject size=18571048 (in reply
    to end of DATA command)

--257DF6512BF.1339150035/admin1.sample.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.sample.co.uk
X-Postfix-Queue-ID: 257DF6512BF
X-Postfix-Sender: rfc822; automated-bounces+8C55289C-B151-11E1-AC6A-CCB6C6F8F3BB@email.sample.com
Arrival-Date: Fri,  8 Jun 2012 11:06:00 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.com
Action: failed
Status: 5.7.1
Remote-MTA: dns; cust1793-1.in.mailcontrol.com
Diagnostic-Code: smtp; 554 5.7.1 Message Rejected Class=size limit=15728640
    Subclass=reject size=18571048

--257DF6512BF.1339150035/admin1.sample.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by admin1.sample.co.uk (Postfix, from userid 507)
	id 257DF6512BF; Fri,  8 Jun 2012 11:06:01 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1339149960108080"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Fri, 8 Jun 2012 11:06:00 +0100
From: Fred Bloggs <fred.bloggs@email.sample.com>
Subject: foo
List-Unsubscribe: <http://www.sampleoffers.co.uk/unsubscribe.epl?uuid=8C55289C-B151-11E1-AC6A-CCB6C6F8F3BB>
To: john smith <john.smith@example.com>
Message-Id: <20120608100601.257DF6512BF@admin1.sample.co.uk>

--257DF6512BF.1339150035/admin1.sample.co.uk--
