Delivered-To: automated-bounces+e5b90666-008e-11e1-92d6-b479a014a16e@email.example.com
Received: by 10.142.82.8 with SMTP id f8cs11309wfb;
        Thu, 27 Oct 2011 04:29:38 -0700 (PDT)
Received: by 10.227.206.147 with SMTP id fu19mr15819020wbb.22.1319714976734;
        Thu, 27 Oct 2011 04:29:36 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id m11si3780449wbh.29.2011.10.27.04.29.36;
        Thu, 27 Oct 2011 04:29:36 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id E615F650E76; Thu, 27 Oct 2011 12:29:35 +0100 (BST)
Date: Thu, 27 Oct 2011 12:29:35 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+E5B90666-008E-11E1-92D6-B479A014A16E@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="34B07651008.1319714975/admin1.example.co.uk"
Message-Id: <20111027112935.E615F650E76@admin1.example.co.uk>

This is a MIME-encapsulated message.

--34B07651008.1319714975/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.net>: message size 18876259 exceeds size
    limit 10485760 of server cluster.thor.test.co[82.197.78.148]

--34B07651008.1319714975/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 34B07651008
X-Postfix-Sender: rfc822; automated-bounces+E5B90666-008E-11E1-92D6-B479A014A16E@email.example.com
Arrival-Date: Thu, 27 Oct 2011 12:29:13 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.net
Action: failed
Status: 5.3.4
Diagnostic-Code: X-Postfix; message size 18876259 exceeds size limit 10485760
    of server cluster.thor.test.co[82.197.78.148]

--34B07651008.1319714975/admin1.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 34B07651008; Thu, 27 Oct 2011 12:29:14 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1319714953162080"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Thu, 27 Oct 2011 12:29:13 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
To: John Smith <john.smith@example.net>
Message-Id: <20111027112914.34B07651008@admin1.example.co.uk>

--34B07651008.1319714975/admin1.example.co.uk--
