Delivered-To: automated-bounces+897027ba-3360-11df-87ee-dd12d3abc650@email.example.com
Received: by 10.216.178.78 with SMTP id e56cs182714wem;
        Tue, 23 Mar 2010 05:40:49 -0700 (PDT)
Received: by 10.86.126.33 with SMTP id y33mr2782277fgc.51.1269348047061;
        Tue, 23 Mar 2010 05:40:47 -0700 (PDT)
Return-Path: <>
Received: from coumta04.foo.co.uk (coumta04.foo.co.uk [95.130.76.115])
        by mx.google.com with ESMTP id 3si6774590fxm.66.2010.03.23.05.40.46;
        Tue, 23 Mar 2010 05:40:47 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of coumta04.foo.co.uk designates 95.130.76.115 as permitted sender) client-ip=95.130.76.115;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of coumta04.foo.co.uk designates 95.130.76.115 as permitted sender) smtp.mail=
Received: from mail by coumta04.foo.co.uk with local (NBT 4.61 23)
	id 1Nu3PW-0004hr-Lq
	for SRS0+4a3e275bf5d1796dcf36+2403+email.example.com+automated-bounces+897027BA-3360-11DF-87EE-DD12D3ABC650@coumta04-124042.srs.foo.com; Tue, 23 Mar 2010 12:40:42 +0000
X-Failed-Recipients: john.b@b.c
Auto-Submitted: auto-replied
From: Mail Delivery System <Mailer-Daemon@foo.com>
To: SRS0+4a3e275bf5d1796dcf36+2403+email.example.com+automated-bounces+897027BA-3360-11DF-87EE-DD12D3ABC650@coumta04-124042.srs.foo.com
Subject: Mail delivery failed
Message-Id: <E1Nu3PW-0004hr-Lq@coumta04.foo.co.uk>
Date: Tue, 23 Mar 2010 12:40:42 +0000
X-SRS-Return: DSN routed via coumta04.foo.co.uk.

This message was created automatically by mail delivery software.

A message sent by

  <automated-bounces+897027BA-3360-11DF-87EE-DD12D3ABC650@email.example.com>

could not be delivered to one or more of its recipients. The following
address(es) failed:

  john.b@b.c
    (ultimately generated from john@b.co.uk)
    all hosts have been failing for a long time and were last tried after this message arrived

------ This is a copy of the message, including all the headers. ------
------ The body of the message is 5384741 characters long; only the first
------ 106496 or so are included here.

Return-path: <automated-bounces+897027BA-3360-11DF-87EE-DD12D3ABC650@email.example.com>
Received: from server2.example.co.uk ([94.236.45.210]:40514)
	by coumta04.foo.co.uk with esmtp (NBT 4.61 23)
	id 1Nscpp-0003Yd-JD
	for john@b.co.uk; Fri, 19 Mar 2010 14:05:59 +0000
Received: by server2.example.co.uk (Postfix, from userid 507)
	id 2EEB4B58176; Fri, 19 Mar 2010 14:05:56 +0000 (GMT)
Received-SPF: pass (coumta04.foo.co.uk: domain of email.example.com designates 94.236.45.210 as permitted sender) client-ip=94.236.45.210; envelope-from=automated-bounces+897027BA-3360-11DF-87EE-DD12D3ABC650@email.example.com; helo=server2.example.co.uk;
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1269007556;
	bh=D8gt0ZsbZE4W7jmrWd/V2OtE0LUDbgreceDPsg5OqOM=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=kpBELggf3iXJdtx0+dO+jfyBi9DoINl6jUXtJ5igMeLN+Z5I4Zv0eDVjAKchd0m2J
	 DRESD39bLez8KfUTj5+60ORO3H5sd1Sd3DmmUl1xdSjAaff8RVbUT6wzHQvLX7Z6oP
	 4zAf7AWbiAMSh+tqMADt7zgfoWOAfFdMTfvM/22A=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1269007556254940"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Fri, 19 Mar 2010 14:05:56 +0000
From: Customer Services <customerservices@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.example.co.uk/unsubscribe.epl?uuid=897027BA-3360-11DF-87EE-DD12D3ABC650>
To: foo bar <john@b.co.uk>
Message-Id: <20100319140556.2EEB4B58176@server2.example.co.uk>
X-NB-Virus-Scan: virus-free

This is a multi-part message in MIME format.

--_----------=_1269007556254940
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here

--_----------=_1269007556254940
Content-Disposition: inline; filename="jupiter.pdf"
Content-Transfer-Encoding: base64
Content-Type: application/pdf; name="jupiter.pdf"

pdf stripped
