Delivered-To: automated-bounces+b3375476-aabe-11df-a3cd-b4ab787e7c68@email.example.com
Received: by 10.220.199.3 with SMTP id eq3cs129654vcb;
        Wed, 18 Aug 2010 04:49:50 -0700 (PDT)
Received: by 10.227.156.85 with SMTP id v21mr6878825wbw.157.1282132189462;
        Wed, 18 Aug 2010 04:49:49 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id n2si246696wba.48.2010.08.18.04.49.49;
        Wed, 18 Aug 2010 04:49:49 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id EB83D1658211; Wed, 18 Aug 2010 12:49:48 +0100 (BST)
Date: Wed, 18 Aug 2010 12:49:48 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+B3375476-AABE-11DF-A3CD-B4AB787E7C68@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="45F63165820B.1282132188/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100818114948.EB83D1658211@server4.example.co.uk>

This is a MIME-encapsulated message.

--45F63165820B.1282132188/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mail.example.net[139.142.139.12] said: 550 No such
    domain at this location (recipient@example.net) (in reply to RCPT TO command)

--45F63165820B.1282132188/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 45F63165820B
X-Postfix-Sender: rfc822; automated-bounces+B3375476-AABE-11DF-A3CD-B4AB787E7C68@email.example.com
Arrival-Date: Wed, 18 Aug 2010 12:49:47 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.example.net
Diagnostic-Code: smtp; 550 No such domain at this location (recipient@example.net)

--45F63165820B.1282132188/server4.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 505)
	id 45F63165820B; Wed, 18 Aug 2010 12:49:47 +0100 (BST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1282132187;
	bh=r5dj0Ta2P6a/2v06Xyd6TN1FV/fmDVp0T0VRyKgH3LQ=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=Ik3XNJFrOpybKLcGRcy4Ym6UJy0EKUchleNrlpvU8Jf2UX6hnoWGSWJTVcFQzMXnF
	 ZF0AKpJLahpA7AhjxMy91SQsuxiJ0rAxZ/7L8WqfuiLHTJi8OFoB39+3D1M5EQEbJz
	 Pmj7BPbsnrkXdTrd03AxTsjplW1nQPiskH/ittFQ=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_128213218720884467"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 18 Aug 2010 12:49:47 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100720.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=B3375476-AABE-11DF-A3CD-B4AB787E7C68>
To: Recipient <recipient@example.net>
Message-Id: <20100818114947.45F63165820B@server4.example.co.uk>

--45F63165820B.1282132188/server4.example.co.uk--
