X-Spam-Checker-Version: SpamAssassin 3.1.3 (2006-06-01) on 
	bacchus.thegestalt.org
X-Spam-Level: 
X-Spam-Status: No, score=0.1 required=5.0 tests=AWL,NO_RELAYS autolearn=ham 
	version=3.1.3
Received: from mailnull by bacchus.thegestalt.org with local (Exim 4.61 (FreeBSD))
	id 1G5JKH-0008xD-3e
	for london.food-bounce@thegestalt.org; Tue, 25 Jul 2006 10:35:41 +0100
X-Failed-Recipients: hbsdpphvfex@blackwebportal.com
Auto-Submitted: auto-replied
Old-From: Mail Delivery System <Mailer-Daemon@bacchus.thegestalt.org>
To: london.food-bounce@thegestalt.org
Old-Subject: Mail delivery failed: returning message to sender
Message-Id: <E1G5JKH-0008xD-3e@bacchus.thegestalt.org>
Date: Tue, 25 Jul 2006 10:35:41 +0100
Subject:  Mail delivery failed: returning message to sender
From:  Mail Delivery System <Mailer-Daemon@bacchus.thegestalt.org>
Status: RO
Content-Length: 1666
Lines: 39

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  hbsdpphvfex@blackwebportal.com
    SMTP error from remote mail server after RCPT TO:<hbsdpphvfex@blackwebportal.com>:
    host sitemail.everyone.net [209.249.170.32]: 550 Recipient Rejected:
    No account by that name here

------ This is a copy of the message, including all the headers. ------

Return-path: <london.food-bounce@thegestalt.org>
Received: from [82.138.248.236] (helo=bacchus.thegestalt.org)
	by bacchus.thegestalt.org with esmtp (Exim 4.61 (FreeBSD))
	(envelope-from <london.food-bounce@thegestalt.org>)
	id 1G5JKG-0008xA-3G
	for hbsdpphvfex@blackwebportal.com; Tue, 25 Jul 2006 10:35:40 +0100
Received: (from mailnull@localhost)
	by bacchus.thegestalt.org (8.13.6/8.13.6/Submit) id k6P9Zdos034419
	for hbsdpphvfex@blackwebportal.com; Tue, 25 Jul 2006 10:35:39 +0100 (BST)
	(envelope-from london.food-bounce@thegestalt.org)
Date: Tue, 25 Jul 2006 10:35:39 +0100 (BST)
Message-Id: <200607250935.k6P9Zdos034419@bacchus.thegestalt.org>
X-Authentication-Warning: bacchus.thegestalt.org: mailnull set sender to london.food-bounce@thegestalt.org using -f
To: hbsdpphvfex@blackwebportal.com
From: london.food-bounce@thegestalt.org
Subject: Re: Erection problems can be fixed Lionel
In-Reply-To: 
 <30598324.7175598017554.JavaMail.vmail@service3.colo.realestatemail.net> 

Hi,

Non-member posting is disabled for this list, and you don't
appear to be a subscriber.

Your message is now held in an approval queue.

- Siesta::Plugin::MembersOnly

