Delivered-To: automated-bounces@example.com
Received: by 10.204.118.69 with SMTP id u5cs148749bkq;
        Mon, 6 Jul 2009 16:38:24 -0700 (PDT)
Received: by 10.210.28.4 with SMTP id b4mr2647360ebb.86.1246923504545;
        Mon, 06 Jul 2009 16:38:24 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [212.100.234.46])
        by mx.google.com with ESMTP id 21si14048331ewy.18.2009.07.06.16.38.24;
        Mon, 06 Jul 2009 16:38:24 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) client-ip=212.100.234.46;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 4F08171C4EC; Tue,  7 Jul 2009 00:38:24 +0100 (BST)
Date: Tue,  7 Jul 2009 00:38:24 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces@example.com
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="25E4471C4EB.1246923504/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20090706233824.4F08171C4EC@server4.example.co.uk>

This is a MIME-encapsulated message.

--25E4471C4EB.1246923504/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain

This is the Postfix program at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

			The Postfix program

<a@example.com>: host cluster3.eu.examplelabs.com[85.158.139.67]
    said: 553-you are trying to use me [server-9.tower-181.examplelabs
    553-.com] as a relay, but I have not been configured to let 553-you
    [212.100.234.46, server4.example.co.uk] do this. 553-Please visit
    www.examplelabs.com/support for more 553-details about this error message
    and instructions to 553 resolve this issue. (#5.7.1) (in reply to RCPT TO
    command)

--25E4471C4EB.1246923504/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 25E4471C4EB
X-Postfix-Sender: rfc822; automated-bounces@example.com
Arrival-Date: Tue,  7 Jul 2009 00:38:24 +0100 (BST)

Final-Recipient: rfc822; a@example.com
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; host cluster3.eu.examplelabs.com[85.158.139.67]
    said: 553-you are trying to use me [server-9.tower-181.examplelabs
    553-.com] as a relay, but I have not been configured to let 553-you
    [212.100.234.46, server4.example.co.uk] do this. 553-Please visit
    www.examplelabs.com/support for more 553-details about this error message
    and instructions to 553 resolve this issue. (#5.7.1) (in reply to RCPT TO
    command)

--25E4471C4EB.1246923504/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 25E4471C4EB; Tue,  7 Jul 2009 00:38:24 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/mixed; boundary="_----------=_124692350417198206"
X-Mailer: MIME::Lite 3.021 (F2.73; T1.22; A2.04; B3.08; Q3.08)
Date: Tue, 7 Jul 2009 00:38:24 +0100
From: sales@example.co.uk
To: a@example.com
Subject: BLEH
Message-Id: <20090706233824.25E4471C4EB@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_124692350417198206
Content-Disposition: inline
Content-Length: 35
Content-Transfer-Encoding: binary
Content-Type: text/plain

bleh
--_----------=_124692350417198206--


--25E4471C4EB.1246923504/server4.example.co.uk--
