From MAILER-DAEMON@somehost.example.com Tue Sep 26 11:34:02 2006
Return-Path: <MAILER-DAEMON@somehost.example.com>
Received: from simba2.k12.example.net (simba2.k12.example.net [204.14.13.133])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k8QIY1E8023292
	for <sender@somehost.example.com>; Tue, 26 Sep 2006 11:34:02 -0700
Received: from SMSD_Groupwise_Domain-MTA by simba2.k12.example.net
	with Novell_GroupWise; Tue, 26 Sep 2006 14:34:00 -0400
Message-Id: <s5193a58.029@simba2.k12.example.net>
X-Mailer: Novell GroupWise Internet Agent 7.0.1 
Date: Tue, 26 Sep 2006 14:34:00 -0400
From: Mailer-Daemon@simba2.k12.example.net
To: sender@somehost.example.com
Subject: Message status - undeliverable
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="=__PartCEEA9F88.0__="

This is a MIME message. If you are reading this text, you may want to 
consider changing to a mail reader or gateway that understands how to 
properly handle MIME multipart messages.

--=__PartCEEA9F88.0__=
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

The message that you sent was undeliverable to the following:

	recipient@example.net (user not found)


--=__PartCEEA9F88.0__=--
