From MAILER-DAEMON@somehost.example.com Tue Sep 26 13:01:29 2006
Return-Path: <MAILER-DAEMON@somehost.example.com>
Received: from somehost.example.com (somehost.example.com [192.168.120.115])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k8QK1TIS002744
	(version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-SHA bits=256 verify=NO)
	for <sender@somehost.example.com>; Tue, 26 Sep 2006 13:01:29 -0700
Received: from somehost.example.com (somehost.example.com [192.168.120.49])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k8QK1TWx023527
	for <sender@somehost.example.com>; Tue, 26 Sep 2006 13:01:29 -0700
Received: from mx1.medicine.example.net (mx1.phhp.example.net [159.178.36.244])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k8QK1SZI002735
	for <sender@somehost.example.com>; Tue, 26 Sep 2006 13:01:28 -0700
X-ASG-Debug-ID: 1159300887-487100660000-toEkdS
X-Barracuda-URL: http://mx1.phhp.example.net:8000/cgi-bin/mark.cgi
X-Barracuda-Connect: gw1.phhp.example.net[159.178.36.251]
X-Barracuda-Start-Time: 1159300887
X-ASG-Whitelist:  Client
Received: from gw1.phhp.example.net (gw1.phhp.example.net [159.178.36.251])
	by mx1.medicine.example.net (Spam Firewall) with ESMTP id D6C36B7E12
	for <sender@somehost.example.com>; Tue, 26 Sep 2006 16:01:27 -0400 (EDT)
Received: from HPDom-MTA by gw1.phhp.example.net
	with Novell_GroupWise; Tue, 26 Sep 2006 16:01:27 -0400
Message-Id: <s5194ed7.051@gw1.phhp.example.net>
X-Mailer: Novell GroupWise Internet Agent 6.5.7 
Date: Tue, 26 Sep 2006 16:01:27 -0400
From: Mailer-Daemon@gw1.phhp.example.net
To: sender@somehost.example.com
X-ASG-Orig-Subj: Message status - undeliverable
Subject: Message status - undeliverable
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="=__PartB490E507.0__="
X-Barracuda-Virus-Scanned: by PHHP Barracuda Spam Firewall at medicine.example.net
X-Barracuda-Spam-Score: 0.00
X-Barracuda-Spam-Status: No, SCORE=0.00 using global scores of TAG_LEVEL=2.9 QUARANTINE_LEVEL=3.4 KILL_LEVEL=7.0 

This is a MIME message. If you are reading this text, you may want to 
consider changing to a mail reader or gateway that understands how to 
properly handle MIME multipart messages.

--=__PartB490E507.0__=
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

The message that you sent was undeliverable to the following:

	recipient (User account is expired)


--=__PartB490E507.0__=--
