Delivered-To: michael.stevens@example.com
Received: by 10.227.128.85 with SMTP id j21cs69400wbs;
        Thu, 19 Aug 2010 07:06:45 -0700 (PDT)
Received: by 10.223.113.65 with SMTP id z1mr9436823fap.38.1282226803554;
        Thu, 19 Aug 2010 07:06:43 -0700 (PDT)
Return-Path: <example10@wp.pl>
Received: from mx3.wp.pl (mx3.wp.pl [212.77.101.7])
        by mx.google.com with ESMTP id r6si1666058faq.15.2010.08.19.07.06.43;
        Thu, 19 Aug 2010 07:06:43 -0700 (PDT)
Received-SPF: pass (google.com: domain of example10@wp.pl designates 212.77.101.7 as permitted sender) client-ip=212.77.101.7;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of example10@wp.pl designates 212.77.101.7 as permitted sender) smtp.mail=example10@wp.pl
Received: (wp-smtpd 16293 invoked by uid 100); 19 Aug 2010 16:06:43 +0200
Message-ID: <20100819140643.16292.qmail@smtp.wp.pl>
Date: 19 Aug 2010 16:06:43 +0200
Delivered-To: example10@wp.pl (example10)
Precedence: junk
To: michael.stevens@example.com
From: Dianomi Dianomi <example10@wp.pl>
Subject: [Automatyczna =?iso-8859-2?Q?odpowied=BC?=] test
MIME-version: 1.0
Content-type: text/plain; charset=iso-8859-2
Content-transfer-encoding: 8BIT

the cat sat on the mat. The quick brown fox jumped over the lazy dog. The rain in Spain falls mainly on the plain. Lorem ipsum lorem ipsum.
