Delivered-To: automated-bounces+9c4b1faa-a54f-11df-b987-b61b687dad41@email.example.com
Received: by 10.220.190.129 with SMTP id di1cs85429vcb;
        Wed, 11 Aug 2010 06:52:02 -0700 (PDT)
Received: by 10.227.141.84 with SMTP id l20mr16801498wbu.119.1281534721326;
        Wed, 11 Aug 2010 06:52:01 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id a22si60552wba.7.2010.08.11.06.52.00;
        Wed, 11 Aug 2010 06:52:01 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id B83EB16582F4; Wed, 11 Aug 2010 14:52:00 +0100 (BST)
Date: Wed, 11 Aug 2010 14:52:00 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+9C4B1FAA-A54F-11DF-B987-B61B687DAD41@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="BCB3B1658217.1281534720/server4.example.co.uk"
Message-Id: <20100811135200.B83EB16582F4@server4.example.co.uk>

This is a MIME-encapsulated message.

--BCB3B1658217.1281534720/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mx.example.net[217.74.65.64] said: 550 5.2.1
    Mailbox not available / Konto niedostepne (in reply to RCPT TO command)

--BCB3B1658217.1281534720/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: BCB3B1658217
X-Postfix-Sender: rfc822; automated-bounces+9C4B1FAA-A54F-11DF-B987-B61B687DAD41@email.example.com
Arrival-Date: Wed, 11 Aug 2010 14:51:58 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.2.1
Remote-MTA: dns; mx.example.net
Diagnostic-Code: smtp; 550 5.2.1 Mailbox not available / Konto niedostepne

--BCB3B1658217.1281534720/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by server4.example.co.uk (Postfix, from userid 505)
	id BCB3B1658217; Wed, 11 Aug 2010 14:51:58 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_12815347181457332"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 11 Aug 2010 14:51:58 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100129.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=9C4B1FAA-A54F-11DF-B987-B61B687DAD41>
To: John Smith <recipient@example.net>
Message-Id: <20100811135158.BCB3B1658217@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_12815347181457332
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_12815347181457332--


--BCB3B1658217.1281534720/server4.example.co.uk--
