Delivered-To: automated-bounces@example.com
Received: by 10.211.177.6 with SMTP id e6cs533610ebp;
        Mon, 27 Jul 2009 07:25:08 -0700 (PDT)
Received: by 10.211.166.2 with SMTP id t2mr2049396ebo.96.1248704708374;
        Mon, 27 Jul 2009 07:25:08 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [212.100.234.46])
        by mx.google.com with ESMTP id 24si12917050ewy.104.2009.07.27.07.25.06;
        Mon, 27 Jul 2009 07:25:07 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) client-ip=212.100.234.46;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 00C7B71C2AF; Mon, 27 Jul 2009 15:25:06 +0100 (BST)
Date: Mon, 27 Jul 2009 15:25:06 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces@example.com
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="9C28C71C2AE.1248704706/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20090727142506.00C7B71C2AF@server4.example.co.uk>

This is a MIME-encapsulated message.

--9C28C71C2AE.1248704706/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain

This is the Postfix program at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

			The Postfix program

<exampleuser@yyahoo.com>: Name service error for name=yyahoo.com type=MX:
    Malformed name server reply

--9C28C71C2AE.1248704706/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 9C28C71C2AE
X-Postfix-Sender: rfc822; automated-bounces@example.com
Arrival-Date: Mon, 27 Jul 2009 15:25:04 +0100 (BST)

Final-Recipient: rfc822; exampleuser@yyahoo.com
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; Name service error for name=yyahoo.com type=MX:
    Malformed name server reply

--9C28C71C2AE.1248704706/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 9C28C71C2AE; Mon, 27 Jul 2009 15:25:04 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_124870470445471"
X-Mailer: MIME::Lite 3.021 (F2.73; T1.22; A2.04; B3.08; Q3.08)
Date: Mon, 27 Jul 2009 15:25:04 +0100
From: Customer Services <customerservices@example.co.uk>
To: exampleuser@yyahoo.com
Subject: BLAH
Message-Id: <42@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_124870470445471
Content-Disposition: inline
Content-Length: 30417
Content-Transfer-Encoding: binary
Content-Type: text/html

Original message body
--_----------=_124870470445471--


--9C28C71C2AE.1248704706/server4.example.co.uk--
