Return-Path: <>
Received: (qmail 14202 invoked from network); 25 Mar 2009 02:30:04 -0000
Date: Wed, 25 Mar 2009 13:32:48 +1100 (EST)
From: MAILER-DAEMON@somehost.example.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: sender@domain-2.org
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
    boundary="21A374ED31.1237948368/somehost.example.com"
Message-Id: <20090325023248.A797D4ED45@somehost.example.com>

This is a MIME-encapsulated message.

--21A374ED31.1237948368/somehost.example.com
Content-Description: Notification
Content-Type: text/plain

This is the Postfix program at host somehost.example.com.

I'm sorry to have to inform you that your message could not be
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

            The Postfix program

<bounce@dest.example.com>: [dest.example.com]: Name or service not known

--21A374ED31.1237948368/somehost.example.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; somehost.example.com
X-Postfix-Queue-ID: 21A374ED31
X-Postfix-Sender: rfc822; sender@domain-2.org
Arrival-Date: Wed, 25 Mar 2009 13:32:48 +1100 (EST)

Final-Recipient: rfc822; bounce@dest.example.com
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; [dest.example.com]: Name or service not known

--21A374ED31.1237948368/somehost.example.com
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: from somehost.example.com (somehost.example.com [202.76.250.254])
    by somehost.example.com (Postfix) with ESMTP id 21A374ED31
    for <bounce@dest.example.com>; Wed, 25 Mar 2009 13:32:48 +1100 (EST)
Received: by somehost.example.com (Postfix, from userid 2202)
    id 1C29AC5C98; Wed, 25 Mar 2009 13:29:55 +1100 (EST)
From: Ricardo SIGNES <sender@domain-2.org>
To: bounce@dest.example.com
Subject: asdf
Message-Id: <20090325022955.1C29AC5C98@somehost.example.com>
Date: Wed, 25 Mar 2009 13:29:55 +1100 (EST)

test
--
sender

--21A374ED31.1237948368/somehost.example.com--

