From MAILER-DAEMON@somehost.example.com Mon Aug 28 13:37:48 2006
Return-Path: <MAILER-DAEMON@somehost.example.com>
Received: from mail1.coqui.net (mail1.coqui.net [196.28.61.210])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k7SKbl2w014660
	for <sender@somehost.example.com>; Mon, 28 Aug 2006 13:37:48 -0700
Message-Id: <200608282037.k7SKbl2w014660@somehost.example.com>
Received: (qmail 7513 invoked for bounce); 28 Aug 2006 16:38:02 -0400
Date: 28 Aug 2006 16:38:02 -0400
From: MAILER-DAEMON@mail1.coqui.net
To: sender@somehost.example.com
Subject: failure notice

Hi. This is the qmail-send program at mail1.coqui.net.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<recipient@example.net>:
Sorry, no mailbox here by that name. (#5.1.1)

--- Below this line is a copy of the message.

Return-Path: <sender@somehost.example.com>
Received: (qmail 7496 invoked from network); 28 Aug 2006 16:38:01 -0400
Received: from avas5.coqui.net ([196.28.61.131])
          (envelope-sender <sender@somehost.example.com>)
          by mail1.coqui.net (qmail-ldap-1.03) with SMTP
          for <recipient@example.net>; 28 Aug 2006 16:38:01 -0400
Received: from somehost.example.com ([64.156.13.103])
  by avas5.coqui.net with ESMTP; 28 Aug 2006 16:37:27 -0400
Received: from somehost.example.com (localhost [127.0.0.1])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k7SKYZYD007776
	for <recipient@example.net>; Mon, 28 Aug 2006 13:37:26 -0700
Received: (from sender@localhost)
	by somehost.example.com (8.12.11.20060308/8.12.11/Submit) id k7SK8Bbu032023
	for recipient@example.net; Mon, 28 Aug 2006 13:08:11 -0700
Date: Mon, 28 Aug 2006 13:08:11 -0700
Message-Id: <200608282008.k7SK8Bbu032023@somehost.example.com>
Content-Type: multipart/alternative;
 boundary="----------=_1156795691-26218-2900"
Content-Transfer-Encoding: binary
MIME-Version: 1.0
X-Mailer: MIME-tools 5.415 (Entity 5.415)
From: Sender Address <sender@example.com>
To: Sender Address <sender@example.com>
Subject: Test Bounce Message

This is a multi-part message in MIME format...

------------=_1156795691-26218-2900
Content-Type: text/plain
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

Plaintext part here.

------------=_1156795691-26218-2900
Content-Type: text/html
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd"><html>
  <head>
 <title>Test Bounce Message</title>

<body>
<b>Test HTML part here.</b>
</body>
</html>

------------=_1156795691-26218-2900--
