Delivered-To: automated-bounces+8e913424-9b31-11e1-b8bb-d5cab207567c@email.example.com
Received: by 10.52.34.101 with SMTP id y5csp138640vdi;
        Thu, 10 May 2012 23:21:42 -0700 (PDT)
Received: by 10.50.85.196 with SMTP id j4mr921494igz.30.1336717302454;
        Thu, 10 May 2012 23:21:42 -0700 (PDT)
Return-Path: <>
Received: from brian.anythingemail.com (brian.anythingemail.com. [74.208.148.17])
        by mx.google.com with ESMTP id r10si3938658igl.53.2012.05.10.23.21.42;
        Thu, 10 May 2012 23:21:42 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of brian.anythingemail.com designates 74.208.148.17 as permitted sender) client-ip=74.208.148.17;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of brian.anythingemail.com designates 74.208.148.17 as permitted sender) smtp.mail=
Received: from m1.anythingemail.com (unknown [75.101.133.168])
	by brian.anythingemail.com (Postfix) with ESMTP id C9A178BFE91B
	for <automated-bounces+8E913424-9B31-11E1-B8BB-D5CAB207567C@email.example.com>; Fri, 11 May 2012 02:21:41 -0400 (EDT)
Received: by m1.anythingemail.com (Postfix)
	id 7515160174FC; Fri, 11 May 2012 02:21:41 -0400 (EDT)
Date: Fri, 11 May 2012 02:21:41 -0400 (EDT)
From: MAILER-DAEMON@m1.anythingemail.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+8E913424-9B31-11E1-B8BB-D5CAB207567C@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="08EE6601677C.1336717301/m1.anythingemail.com"
Message-Id: <20120511062141.7515160174FC@m1.anythingemail.com>

This is a MIME-encapsulated message.

--08EE6601677C.1336717301/m1.anythingemail.com
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host m1.anythingemail.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@sample.com>: permission denied. Command output: The recipient mailbox
    has exceeded its disk space limit.

--08EE6601677C.1336717301/m1.anythingemail.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; m1.anythingemail.com
X-Postfix-Queue-ID: 08EE6601677C
X-Postfix-Sender: rfc822; automated-bounces+8E913424-9B31-11E1-B8BB-D5CAB207567C@email.example.com
Arrival-Date: Fri, 11 May 2012 02:21:35 -0400 (EDT)

Final-Recipient: rfc822; john.smith@sample.com
Original-Recipient: rfc822;john.smith@sample.com
Action: failed
Status: 5.7.0
Diagnostic-Code: x-unix; The recipient mailbox has exceeded its disk space
    limit.

--08EE6601677C.1336717301/m1.anythingemail.com
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
	by m1.anythingemail.com (Postfix) with ESMTP id 08EE6601677C
	for <john.smith@sample.com>; Fri, 11 May 2012 02:21:35 -0400 (EDT)
Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 8C566651314; Fri, 11 May 2012 07:21:34 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_133671729415038101"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Fri, 11 May 2012 07:21:34 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=8E913424-9B31-11E1-B8BB-D5CAB207567C>
To: John Smith <john.smith@sample.com>
Message-Id: <20120511062134.8C566651314@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_133671729415038101
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_133671729415038101--


--08EE6601677C.1336717301/m1.anythingemail.com--
