Delivered-To: automated-bounces+c2b5cbec-7d16-11df-a646-3670dd31f8f5@email.example.com
Received: by 10.216.157.72 with SMTP id n50cs81067wek;
        Mon, 21 Jun 2010 02:24:25 -0700 (PDT)
Received: by 10.142.248.38 with SMTP id v38mr3076079wfh.246.1277112263976;
        Mon, 21 Jun 2010 02:24:23 -0700 (PDT)
Return-Path: <>
Received: from a.b.c (mail1.a.b.c [202.123.2.106])
        by mx.google.com with ESMTP id r12si30676105wac.152.2010.06.21.02.24.21;
        Mon, 21 Jun 2010 02:24:22 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of a.b.c designates 202.123.2.106 as permitted sender) client-ip=202.123.2.106;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of a.b.c designates 202.123.2.106 as permitted sender) smtp.mail=
Subject: Undeliverable mail: Dear Mr Ramchurn, did you find the Online trading you were looking for?
From: <MAILER-DAEMON@a.b.c>
To: <automated-bounces+C2B5CBEC-7D16-11DF-A646-3670DD31F8F5@email.example.com>
Date: Mon, 21 Jun 2010 13:24:19 +0400
Message-ID: <receipt-118431788@a.b.c>
X-MAPI-Message-Class: REPORT.IPM.Note.NDR
MIME-Version: 1.0
Content-Type: multipart/report; report-type="delivery-status"; boundary="_===118431788====a.b.c===_"


--_===118431788====a.b.c===_
Content-Type: text/plain; charset="utf-8"

Failed to deliver to '<f.b@a.b.c>'
LOCAL module(account f.b) reports:
 account is full (quota exceeded)


--_===118431788====a.b.c===_
Content-Type: message/delivery-status

Reporting-MTA: dns; a.b.c

Original-Recipient: rfc822;<f.b@a.b.c>
Final-Recipient: LOCAL;<f.b>
Action: failed
Status: 5.0.0

--_===118431788====a.b.c===_
Content-Type: text/rfc822-headers

Received: from [192.168.14.5] (HELO iron1ldap.intnet.mu)
  by a.b.c (CommuniGate Pro SMTP 5.2.19)
  with ESMTP id 118431787 for f.b@a.b.c; Mon, 21 Jun 2010 13:24:19 +0400
X-IronPort-Anti-Spam-Filtered: true
X-IronPort-Anti-Spam-Result: ApkFAJPIHkxe7C3UgWdsb2JhbACBQxCGGpZDWhUBARYiIrIqAY1zBYJfgjw
Received: from server4.example.co.uk ([94.236.45.212])
  by iron.intnet.mu with ESMTP; 21 Jun 2010 13:24:18 +0400
Received: by server4.example.co.uk (Postfix, from userid 507)
	id 64D1416585F1; Mon, 21 Jun 2010 10:24:15 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_127711225513166123"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 21 Jun 2010 10:24:15 +0100
From: Fred Bloggs <julia.stevens@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=C2B5CBEC-7D16-11DF-A646-3670DD31F8F5>
To: John Smith <f.b@a.b.c>
Message-Id: <20100621092415.64D1416585F1@server4.example.co.uk>

--_===118431788====a.b.c===_--
