Delivered-To: automated-bounces+3edf86bc-2138-11df-93a3-90ddb02edadf@example.com
Received: by 10.216.173.129 with SMTP id v1cs182578wel;
        Wed, 24 Feb 2010 03:32:23 -0800 (PST)
Received: by 10.204.34.81 with SMTP id k17mr3406966bkd.78.1267011142935;
        Wed, 24 Feb 2010 03:32:22 -0800 (PST)
Return-Path: <>
Received: from odin.b.c (odin.b.c [212.30.8.67])
        by mx.google.com with ESMTP id 10si13393419bwz.68.2010.02.24.03.32.22;
        Wed, 24 Feb 2010 03:32:22 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of odin.b.c designates 212.30.8.67 as permitted sender) client-ip=212.30.8.67;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of odin.b.c designates 212.30.8.67 as permitted sender) smtp.mail=
Received: from localhost (unknown [127.0.0.1])
	by odin.b.c (Postfix) with ESMTP id 8934DD80B18
	for <automated-bounces+3EDF86BC-2138-11DF-93A3-90DDB02EDADF@example.com>; Wed, 24 Feb 2010 11:32:22 +0000 (GMT)
Received: from odin.b.c ([127.0.0.1])
	by localhost (odin.b.c [127.0.0.1]) (amavisd-new, port 10024)
	with LMTP id mjJnKfSTLwJs
	for <automated-bounces+3EDF86BC-2138-11DF-93A3-90DDB02EDADF@example.com>;
	Wed, 24 Feb 2010 11:32:17 +0000 (GMT)
Received: from mail.b.c (unknown [100.0.0.212])
	by odin.b.c (Postfix) with ESMTP id B6C32D8148C
	for <automated-bounces+3EDF86BC-2138-11DF-93A3-90DDB02EDADF@example.com>; Wed, 24 Feb 2010 11:32:17 +0000 (GMT)
Date:     Wed, 24 Feb 2010 11:30:12 +0000
Message-Id: <11002241130.AA45656@b.c>
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
From:     "Postmaster" <postmaster@b.c>
Sender:   <postmaster@b.c>
To:       <automated-bounces+3EDF86BC-2138-11DF-93A3-90DDB02EDADF@example.com>
Subject: Undeliverable Mail
X-Mailer: <SMTP32 v10.0>

User mailbox exceeds allowed size: a@b.c


Original message follows.

Received: from mail.b.c [192.168.69.68] by b.c with ESMTP
  (SMTPD-10.0) id ADC40D9C; Wed, 24 Feb 2010 11:30:12 +0000
Received: from localhost (unknown [127.0.0.1])
	by mail.b.c (Postfix) with ESMTP id 12BAE74FD4C
	for <a@b.c>; Wed, 24 Feb 2010 11:32:17 +0000 (GMT)
Received: from mail.b.c ([127.0.0.1])
	by localhost (mail.b.c [127.0.0.1]) (amavisd-new, port 10024)
	with LMTP id aWj8vGi4KGvJ for <a@b.c>;
	Wed, 24 Feb 2010 11:32:10 +0000 (GMT)
Received: from mx3.b.c (mx3.b.c [212.30.16.251])
	by mail.b.c (Postfix) with ESMTP id 79A3A74E379
	for <a@b.c>; Wed, 24 Feb 2010 11:32:10 +0000 (GMT)
Received: from server4.example.com (server4.example.com [94.236.45.212])
	by mx3.b.c (Postfix) with ESMTP id 59F1F3B0076
	for <a@b.c>; Wed, 24 Feb 2010 11:32:10 +0000 (GMT)
Received: by server4.example.com (Postfix, from userid 505)
	id 2BEAE16581EF; Wed, 24 Feb 2010 11:32:10 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=example.com;
	s=default10; t=1267011130;
	bh=wpmvJxMe0RUOHEL2J1FHHgwdqQroxMr1a482qhbFzf8=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=uOLMabLcgwACL5q3QCCkJBxBPwtYbEN8c7OfYAF/LfFD5jsbECpJqSrUzDY3ARpQy
	 NaZDX6594b2xyDLqWbK+LQVOc9hNeYvK+clDJ37Zt7M4ihDXcJc9ulbsAaB/PniUJa
	 Npr/f45q8cUO9nv+3CxOiWj7WM7fiOor+1ImrzxM=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_12670111302218415"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 24 Feb 2010 11:32:10 +0000
From: Julia Stevens <julia.stevens@example.com>
Subject: subject
To: Fred Bloggs <a@b.c>
Message-Id: <20100224113210.2BEAE16581EF@server4.example.com>

[message truncated]
