Delivered-To: automated-bounces+45e14a44-32a0-11df-997c-88ff3c6d9c12@email.example.com
Received: by 10.216.178.78 with SMTP id e56cs190459wem;
        Tue, 23 Mar 2010 08:11:50 -0700 (PDT)
Received: by 10.204.23.6 with SMTP id p6mr5599916bkb.67.1269357109876;
        Tue, 23 Mar 2010 08:11:49 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id p14si14911552bkd.51.2010.03.23.08.11.49;
        Tue, 23 Mar 2010 08:11:49 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 6CEB916581C5; Tue, 23 Mar 2010 15:11:49 +0000 (GMT)
Date: Tue, 23 Mar 2010 15:11:49 +0000 (GMT)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+45E14A44-32A0-11DF-997C-88FF3C6D9C12@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="4C2ACC302AD.1269357109/server4.example.co.uk"
Message-Id: <20100323151149.6CEB916581C5@server4.example.co.uk>

This is a MIME-encapsulated message.

--4C2ACC302AD.1269357109/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<junkmail@b.c>: host a.d.e[65.61.209.19] said: 452
    <junkmail@b.c> Mailbox size limit exceeded (in reply to RCPT
    TO command)

--4C2ACC302AD.1269357109/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 4C2ACC302AD
X-Postfix-Sender: rfc822; automated-bounces+45E14A44-32A0-11DF-997C-88FF3C6D9C12@email.example.com
Arrival-Date: Thu, 18 Mar 2010 15:09:39 +0000 (GMT)

Final-Recipient: rfc822; junkmail@b.c
Action: failed
Status: 4.0.0
Remote-MTA: dns; a.d.e
Diagnostic-Code: smtp; 452 <junkmail@b.c> Mailbox size limit
    exceeded

--4C2ACC302AD.1269357109/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by server4.example.co.uk (Postfix, from userid 505)
	id 4C2ACC302AD; Thu, 18 Mar 2010 15:09:39 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1268924979;
	bh=PvBeqlgwhtS+D7uysuw6BXUN2jai7vWzT5i5MpsViHw=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=JR618/DBjWobkpwDR+0Zi/BE3YmacasHafQ4raBTbfaHu/KoW3AZKDTfPpKtPVHID
	 9ThNE4cLynCViAxfOOroSlu/rPCHwG/LFv5HyWOXUsbO9QT8qwCZMjOGaRjJL0jaeB
	 6FP5n8QQZ6WY5Jsw9rBol+WJU/Xy2zOK6eP6QeqQ=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_126892497929411967"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Thu, 18 Mar 2010 15:09:39 +0000
From: John Smith <john.smith@email.example.com>
Subject: xx
X-Campaignid: dianomi20100129.2
To: John Smith <junkmail@b.c>
Message-Id: <20100318150939.4C2ACC302AD@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_126892497929411967
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML here

--_----------=_126892497929411967--


--4C2ACC302AD.1269357109/server4.example.co.uk--
