Delivered-To: automated-bounces+402fa706-9a58-11df-8050-eeb63452e676@email.example.com
Received: by 10.227.154.195 with SMTP id p3cs24903wbw;
        Wed, 28 Jul 2010 07:56:45 -0700 (PDT)
Received: by 10.216.178.80 with SMTP id e58mr10378081wem.108.1280329005454;
        Wed, 28 Jul 2010 07:56:45 -0700 (PDT)
Return-Path: <>
Received: from server2.example.co.uk (server2.example.co.uk [94.236.45.210])
        by mx.google.com with ESMTP id k43si8955528weq.143.2010.07.28.07.56.45;
        Wed, 28 Jul 2010 07:56:45 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server2.example.co.uk designates 94.236.45.210 as permitted sender) client-ip=94.236.45.210;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server2.example.co.uk designates 94.236.45.210 as permitted sender) smtp.mail=
Received: by server2.example.co.uk (Postfix)
	id 30B4EB58162; Wed, 28 Jul 2010 15:56:45 +0100 (BST)
Date: Wed, 28 Jul 2010 15:56:45 +0100 (BST)
From: MAILER-DAEMON@server2.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+402FA706-9A58-11DF-8050-EEB63452E676@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="EAB68B58165.1280329005/server2.example.co.uk"
Message-Id: <20100728145645.30B4EB58162@server2.example.co.uk>

This is a MIME-encapsulated message.

--EAB68B58165.1280329005/server2.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server2.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mx1.example.net[213.8.161.228] said: 554 Rcpt
    <recipient@example.net> does not exist (in reply to end of DATA command)

--EAB68B58165.1280329005/server2.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server2.example.co.uk
X-Postfix-Queue-ID: EAB68B58165
X-Postfix-Sender: rfc822; automated-bounces+402FA706-9A58-11DF-8050-EEB63452E676@email.example.com
Arrival-Date: Wed, 28 Jul 2010 15:56:06 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx1.example.net
Diagnostic-Code: smtp; 554 Rcpt <recipient@example.net> does not exist

--EAB68B58165.1280329005/server2.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by server2.example.co.uk (Postfix, from userid 507)
	id EAB68B58165; Wed, 28 Jul 2010 15:56:06 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1280328966260510"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 28 Jul 2010 15:56:06 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=402FA706-9A58-11DF-8050-EEB63452E676>
To: John Smith <recipient@example.net>
Message-Id: <20100728145606.EAB68B58165@server2.example.co.uk>

--EAB68B58165.1280329005/server2.example.co.uk--
