Delivered-To: automated-bounces+cdd2fb74-94bf-11df-825d-f5a2c2e803c9@email.example.com
Received: by 10.224.45.67 with SMTP id d3cs201560qaf;
        Wed, 21 Jul 2010 05:02:18 -0700 (PDT)
Received: by 10.227.137.208 with SMTP id x16mr81690wbt.36.1279713736775;
        Wed, 21 Jul 2010 05:02:16 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id n9si9464343wba.103.2010.07.21.05.02.16;
        Wed, 21 Jul 2010 05:02:16 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 229B21658345; Wed, 21 Jul 2010 13:02:16 +0100 (BST)
Date: Wed, 21 Jul 2010 13:02:16 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+CDD2FB74-94BF-11DF-825D-F5A2C2E803C9@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="CF44B1658354.1279713736/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100721120216.229B21658345@server4.example.co.uk>

This is a MIME-encapsulated message.

--CF44B1658354.1279713736/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.com>: host mail.a.b.c[80.82.113.36] said: 553
    sorry, that domain isn't in my list of allowed rcpthosts (#5.7.1) (in reply
    to RCPT TO command)

--CF44B1658354.1279713736/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: CF44B1658354
X-Postfix-Sender: rfc822; automated-bounces+CDD2FB74-94BF-11DF-825D-F5A2C2E803C9@email.example.com
Arrival-Date: Wed, 21 Jul 2010 13:02:15 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.a.b.c
Diagnostic-Code: smtp; 553 sorry, that domain isn't in my list of allowed
    rcpthosts (#5.7.1)

--CF44B1658354.1279713736/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 505)
	id CF44B1658354; Wed, 21 Jul 2010 13:02:15 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_1279713735175451555"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 21 Jul 2010 13:02:15 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100720.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=CDD2FB74-94BF-11DF-825D-F5A2C2E803C9>
To: John Smith <john.smith@example.com>
Message-Id: <20100721120215.CF44B1658354@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1279713735175451555
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text
  
--_----------=_1279713735175451555
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_1279713735175451555--


--CF44B1658354.1279713736/server4.example.co.uk--
