Delivered-To: automated-bounces+2bf08d5e-d3bc-11de-978e-ed74dd31f8f5@email.example.com
Received: by 10.140.148.17 with SMTP id v17cs64573rvd;
        Tue, 17 Nov 2009 13:00:06 -0800 (PST)
Received: by 10.213.3.140 with SMTP id 12mr2718740ebn.20.1258491604493;
        Tue, 17 Nov 2009 13:00:04 -0800 (PST)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id 28si534296eyg.22.2009.11.17.13.00.03;
        Tue, 17 Nov 2009 13:00:04 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 92EE016581F2; Tue, 17 Nov 2009 21:00:03 +0000 (GMT)
Date: Tue, 17 Nov 2009 21:00:03 +0000 (GMT)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+2BF08D5E-D3BC-11DE-978E-ED74DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="4A2BA16581E5.1258491603/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20091117210003.92EE016581F2@server4.example.co.uk>

This is a MIME-encapsulated message.

--4A2BA16581E5.1258491603/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<a@example.com>: host ibmr.example2.com[213.123.26.151] said: 550
    <a@example.com>... Relaying denied (in reply to RCPT TO command)

--4A2BA16581E5.1258491603/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 4A2BA16581E5
X-Postfix-Sender: rfc822; automated-bounces+2BF08D5E-D3BC-11DE-978E-ED74DD31F8F5@email.example.com
Arrival-Date: Tue, 17 Nov 2009 21:00:01 +0000 (GMT)

Final-Recipient: rfc822; a@example.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; ibmr.example2.com
Diagnostic-Code: smtp; 550 <a@example.com>... Relaying denied

--4A2BA16581E5.1258491603/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 4A2BA16581E5; Tue, 17 Nov 2009 21:00:01 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_1258491601143730"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Tue, 17 Nov 2009 21:00:01 +0000
From: Customer Services <customerservices@example.co.uk>
To: a@example.com
Subject: BLEH
Message-Id: <20091117210001.4A2BA16581E5@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1258491601143730
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html

Hello

--_----------=_1258491601143730--


--4A2BA16581E5.1258491603/server4.example.co.uk--
