Delivered-To: automated-bounces+a0252e3a-03ef-11e2-b9d3-a8599e6038a7@email.example.com
Received: by 10.14.203.2 with SMTP id e2csp355013eeo;
        Fri, 21 Sep 2012 06:23:46 -0700 (PDT)
Received: by 10.216.201.7 with SMTP id a7mr2832673weo.84.1348233826098;
        Fri, 21 Sep 2012 06:23:46 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id p9si11769427wea.141.2012.09.21.06.23.45;
        Fri, 21 Sep 2012 06:23:45 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id D213B651335; Fri, 21 Sep 2012 14:23:45 +0100 (BST)
Date: Fri, 21 Sep 2012 14:23:45 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+A0252E3A-03EF-11E2-B9D3-A8599E6038A7@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="57056651330.1348233825/admin1.example.co.uk"
Message-Id: <20120921132345.D213B651335@admin1.example.co.uk>

This is a MIME-encapsulated message.

--57056651330.1348233825/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred.bloggs@sample.co.uk>: host mailhost.sample.co.uk[213.38.79.122]
    said: 550 5.7.1 Rejected - bulk email (in reply to end of DATA command)

--57056651330.1348233825/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 57056651330
X-Postfix-Sender: rfc822; automated-bounces+A0252E3A-03EF-11E2-B9D3-A8599E6038A7@email.example.com
Arrival-Date: Fri, 21 Sep 2012 14:23:44 +0100 (BST)

Final-Recipient: rfc822; fred.bloggs@sample.co.uk
Original-Recipient: rfc822;fred.bloggs@sample.co.uk
Action: failed
Status: 5.7.1
Remote-MTA: dns; mailhost.sample.co.uk
Diagnostic-Code: smtp; 550 5.7.1 Rejected - bulk email

--57056651330.1348233825/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: from cloudadmin1.localdomain (cloudadmin1 [10.177.197.82])
	by admin1.example.co.uk (Postfix) with ESMTP id 57056651330
	for <fred.bloggs@sample.co.uk>; Fri, 21 Sep 2012 14:23:44 +0100 (BST)
Authentication-Results: admin1.example.co.uk; dkim=pass (1024-bit key)
	header.i=@email.example.com; x-dkim-adsp=pass
Received: by cloudadmin1.localdomain (Postfix, from userid 507)
	id 72C461E809E; Fri, 21 Sep 2012 14:24:09 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_134823384926952527"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Fri, 21 Sep 2012 14:24:09 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=A0252E3A-03EF-11E2-B9D3-A8599E6038A7>
To: Fred Bloggs <fred.bloggs@sample.co.uk>
Message-Id: <20120921132409.72C461E809E@cloudadmin1.localdomain>

This is a multi-part message in MIME format.

--_----------=_134823384926952527
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

html goes here

--_----------=_134823384926952527--


--57056651330.1348233825/admin1.example.co.uk--
