Delivered-To: automated-bounces+a082d944-031e-11e2-a271-ce28aea58548@email.example.com
Received: by 10.14.203.2 with SMTP id e2csp190624eeo;
        Thu, 20 Sep 2012 05:28:21 -0700 (PDT)
Received: by 10.50.140.65 with SMTP id re1mr2185830igb.68.1348144100661;
        Thu, 20 Sep 2012 05:28:20 -0700 (PDT)
Return-Path: <>
Received: from mailforward.sample.com (mailforward.sample.com. [70.87.28.64])
        by mx.google.com with ESMTP id we2si23875998igb.44.2012.09.20.05.28.20;
        Thu, 20 Sep 2012 05:28:20 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of mailforward.sample.com designates 70.87.28.64 as permitted sender) client-ip=70.87.28.64;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of mailforward.sample.com designates 70.87.28.64 as permitted sender) smtp.mail=
Received: from mx1.sample.com (inbound-us2.sample.com [70.87.28.136])
	by mailforward.sample.com (Postfix) with ESMTP id 63D8F162B68E
	for <automated-bounces+A082D944-031E-11E2-A271-CE28AEA58548@email.example.com>; Thu, 20 Sep 2012 12:28:18 +0000 (GMT)
Received: by mx1.sample.com (Postfix)
	id 4ED4C3F00CF; Thu, 20 Sep 2012 12:28:18 +0000 (GMT)
Date: Thu, 20 Sep 2012 12:28:18 +0000 (GMT)
From: MAILER-DAEMON@mx1.sample.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+A082D944-031E-11E2-A271-CE28AEA58548@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="B4EEB3F00C0.1348144098/mx1.sample.com"
Message-Id: <20120920122818.4ED4C3F00CF@mx1.sample.com>
X-CTCH-Spam: Unknown
X-CTCH-VOD: Unknown
X-CTCH-RefID: str=0001.0A0B0209.505B0BE2.0109,ss=1,re=0.000,recu=0.000,reip=0.000,cl=1,cld=1,fgs=256

This is a MIME-encapsulated message.

--B4EEB3F00C0.1348144098/mx1.sample.com
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host mx1.sample.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred.bloggssample@gmail.com> (expanded from <fred.bloggs@sample2.com>): host
    70.87.28.164[70.87.28.164] said: 550-5.7.1 The message was rejected due to
    classification as Bulk mail. Please see
    http://support.sample.com/email-administrators-guide/error-codes 550
    5.7.1 Please see
    http://support.sample.com/email-administrators-guide/error-codes for
    explanation of the problem. (in reply to end of DATA command)

--B4EEB3F00C0.1348144098/mx1.sample.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; mx1.sample.com
X-Postfix-Queue-ID: B4EEB3F00C0
X-Postfix-Sender: rfc822; automated-bounces+A082D944-031E-11E2-A271-CE28AEA58548@email.example.com
Arrival-Date: Thu, 20 Sep 2012 12:28:16 +0000 (GMT)

Final-Recipient: rfc822; fred.bloggssample@gmail.com
Original-Recipient: rfc822;fred.bloggs@sample2.com
Action: failed
Status: 5.7.1
Remote-MTA: dns; 70.87.28.164
Diagnostic-Code: smtp; 550-5.7.1 The message was rejected due to classification
    as Bulk mail. Please see
    http://support.sample.com/email-administrators-guide/error-codes 550
    5.7.1 Please see
    http://support.sample.com/email-administrators-guide/error-codes for
    explanation of the problem.

--B4EEB3F00C0.1348144098/mx1.sample.com
Content-Description: Undelivered Message
Content-Type: message/rfc822

Return-Path: <automated-bounces+A082D944-031E-11E2-A271-CE28AEA58548@email.example.com>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
	by mx1.sample.com (Postfix) with ESMTP id B4EEB3F00C0
	for <fred.bloggs@sample2.com>; Thu, 20 Sep 2012 12:28:16 +0000 (GMT)
Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 2A6916512C9; Thu, 20 Sep 2012 13:28:05 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_134814408514735202"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Thu, 20 Sep 2012 13:28:05 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=A082D944-031E-11E2-A271-CE28AEA58548>
To: Fred Bloggs <fred.bloggs@sample2.com>
Message-Id: <20120920122805.2A6916512C9@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_134814408514735202
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_134814408514735202--


--B4EEB3F00C0.1348144098/mx1.sample.com--
