Delivered-To: automated-bounces+afbf2296-b337-11e1-806e-ae4632b3f250@email.sample.com
Received: by 10.52.101.202 with SMTP id fi10csp83463vdb;
        Sun, 10 Jun 2012 13:06:03 -0700 (PDT)
Received: by 10.216.211.209 with SMTP id w59mr4938283weo.160.1339358763065;
        Sun, 10 Jun 2012 13:06:03 -0700 (PDT)
Return-Path: <>
Received: from admin1.sample.co.uk (admin1.sample.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id ex1si12683213wib.21.2012.06.10.13.06.02;
        Sun, 10 Jun 2012 13:06:02 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.sample.co.uk (Postfix)
	id 6D58B651300; Sun, 10 Jun 2012 21:06:02 +0100 (BST)
Date: Sun, 10 Jun 2012 21:06:02 +0100 (BST)
From: MAILER-DAEMON@admin1.sample.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+AFBF2296-B337-11E1-806E-AE4632B3F250@email.sample.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="444C46512ED.1339358762/admin1.sample.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20120610200602.6D58B651300@admin1.sample.co.uk>

This is a MIME-encapsulated message.

--444C46512ED.1339358762/admin1.sample.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.sample.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.ac.uk>: host cleese.cent.example.ac.uk[130.209.16.34] said:
    550-This message scored 8.4 spam points and has been rejected. 550 Please
    contact mailsec1206@example.ac.uk for help.  Sorry (1339358762). (in reply to
    end of DATA command)

--444C46512ED.1339358762/admin1.sample.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.sample.co.uk
X-Postfix-Queue-ID: 444C46512ED
X-Postfix-Sender: rfc822; automated-bounces+AFBF2296-B337-11E1-806E-AE4632B3F250@email.sample.com
Arrival-Date: Sun, 10 Jun 2012 21:05:55 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.ac.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; cleese.cent.example.ac.uk
Diagnostic-Code: smtp; 550-This message scored 8.4 spam points and has been
    rejected. 550 Please contact mailsec1206@example.ac.uk for help.  Sorry
    (1339358762).

--444C46512ED.1339358762/admin1.sample.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by admin1.sample.co.uk (Postfix, from userid 507)
	id 444C46512ED; Sun, 10 Jun 2012 21:05:55 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_13393587558887130"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Sun, 10 Jun 2012 21:05:55 +0100
From: Fred Bloggs <fred.bloggs@email.sample.com>
Subject: foo
X-Campaignid: sample20110704.1
List-Unsubscribe: <http://www.sampleoffers.co.uk/unsubscribe.epl?uuid=AFBF2296-B337-11E1-806E-AE4632B3F250>
To: "John Smith" <john.smith@example.ac.uk>
Message-Id: <20120610200555.444C46512ED@admin1.sample.co.uk>

This is a multi-part message in MIME format.

--_----------=_13393587558887130
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text

--_----------=_13393587558887130
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_13393587558887130--


--444C46512ED.1339358762/admin1.sample.co.uk--
