Delivered-To: automated-bounces@example.com
Received: by 10.211.179.3 with SMTP id g3cs7167ebp;
        Thu, 16 Jul 2009 03:24:17 -0700 (PDT)
Received: by 10.210.109.19 with SMTP id h19mr9454940ebc.56.1247739857771;
        Thu, 16 Jul 2009 03:24:17 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [212.100.234.46])
        by mx.google.com with ESMTP id 25si18745528ewy.63.2009.07.16.03.24.17;
        Thu, 16 Jul 2009 03:24:17 -0700 (PDT)
Received-SPF: pass (google.com: domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) client-ip=212.100.234.46;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 773F571CAA8; Thu, 16 Jul 2009 11:24:17 +0100 (BST)
Date: Thu, 16 Jul 2009 11:24:17 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces@example.com
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="C4DA671CAA0.1247739857/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20090716102417.773F571CAA8@server4.example.co.uk>

This is a MIME-encapsulated message.

--C4DA671CAA0.1247739857/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain

This is the Postfix program at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

			The Postfix program

<a@example.com>: host spambouncer.turbodns.co.uk[81.21.76.58] said:
    554 SpamBouncer identified SPAM, message permanently rejected (#5.3.0) (in
    reply to end of DATA command)

--C4DA671CAA0.1247739857/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: C4DA671CAA0
X-Postfix-Sender: rfc822; automated-bounces@example.com
Arrival-Date: Thu, 16 Jul 2009 11:24:15 +0100 (BST)

Final-Recipient: rfc822; a@example.com
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; host spambouncer.turbodns.co.uk[81.21.76.58] said:
    554 SpamBouncer identified SPAM, message permanently rejected (#5.3.0) (in
    reply to end of DATA command)

--C4DA671CAA0.1247739857/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id C4DA671CAA0; Thu, 16 Jul 2009 11:24:15 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_1247739855164642857"
X-Mailer: MIME::Lite 3.021 (F2.73; T1.22; A2.04; B3.08; Q3.08)
Date: Thu, 16 Jul 2009 11:24:15 +0100
From: Customer Services <customerservices@example.co.uk>
To: a@example.com
Subject: bleh
List-Unsubscribe: <>
Message-Id: <20090716102415.C4DA671CAA0@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1247739855164642857
Content-Disposition: inline
Content-Length: 7390
Content-Transfer-Encoding: binary
Content-Type: text/html

Hello

--_----------=_1247739855164642857--


--C4DA671CAA0.1247739857/server4.example.co.uk--
