Delivered-To: automated-bounces+eaf5972c-d88c-11e0-889e-a83de810887e@email.example.com
Received: by 10.231.35.202 with SMTP id q10cs79640ibd;
        Tue, 6 Sep 2011 06:35:54 -0700 (PDT)
Received: by 10.216.180.82 with SMTP id i60mr899061wem.92.1315316153163;
        Tue, 06 Sep 2011 06:35:53 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id v21si6809197wec.41.2011.09.06.06.35.52;
        Tue, 06 Sep 2011 06:35:53 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id A45C165186A; Tue,  6 Sep 2011 14:35:52 +0100 (BST)
Date: Tue,  6 Sep 2011 14:35:52 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+EAF5972C-D88C-11E0-889E-A83DE810887E@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="09E8A651865.1315316152/admin1.example.co.uk"
Message-Id: <20110906133552.A45C165186A@admin1.example.co.uk>

This is a MIME-encapsulated message.

--09E8A651865.1315316152/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<sales@test.co.uk>: host mail.test2.net[217.194.212.245] said: 554
    Sending address not accepted due to spam filter (in reply to MAIL FROM
    command)

--09E8A651865.1315316152/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 09E8A651865
X-Postfix-Sender: rfc822; automated-bounces+EAF5972C-D88C-11E0-889E-A83DE810887E@email.example.com
Arrival-Date: Tue,  6 Sep 2011 14:34:17 +0100 (BST)

Final-Recipient: rfc822; sales@test.co.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.test2.net
Diagnostic-Code: smtp; 554 Sending address not accepted due to spam filter

--09E8A651865.1315316152/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 505)
	id 09E8A651865; Tue,  6 Sep 2011 14:34:17 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_131531605720931336"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Tue, 6 Sep 2011 14:34:17 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=EAF5972C-D88C-11E0-889E-A83DE810887E>
To: john smith <sales@test.co.uk>
Message-Id: <20110906133417.09E8A651865@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_131531605720931336
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_131531605720931336--


--09E8A651865.1315316152/admin1.example.co.uk--
