Delivered-To: automated-bounces+dbd27190-3092-11e0-a323-f8a354c7e16d@email.example.com
Received: by 10.100.190.1 with SMTP id n1cs31640anf;
        Fri, 4 Feb 2011 11:38:46 -0800 (PST)
Received: by 10.227.156.5 with SMTP id u5mr7408286wbw.28.1296848324426;
        Fri, 04 Feb 2011 11:38:44 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id d17si1961351wbd.43.2011.02.04.11.38.44;
        Fri, 04 Feb 2011 11:38:44 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id E04031548255; Fri,  4 Feb 2011 19:38:43 +0000 (GMT)
Date: Fri,  4 Feb 2011 19:38:43 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+DBD27190-3092-11E0-A323-F8A354C7E16D@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="574881548263.1296848323/admin1.example.co.uk"
Message-Id: <20110204193843.E04031548255@admin1.example.co.uk>

This is a MIME-encapsulated message.

--574881548263.1296848323/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred.bloggs@example2.co.uk>: host
    mailgate.example3.co.uk[62.49.248.250] said: 550 5.7.1 Your email
    breaches local URIBL policy. (in reply to end of DATA command)

--574881548263.1296848323/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 574881548263
X-Postfix-Sender: rfc822; automated-bounces+DBD27190-3092-11E0-A323-F8A354C7E16D@email.example.com
Arrival-Date: Fri,  4 Feb 2011 19:13:33 +0000 (GMT)

Final-Recipient: rfc822; fred.bloggs@example2.co.uk
Action: failed
Status: 5.7.1
Remote-MTA: dns; mailgate.example3.co.uk
Diagnostic-Code: smtp; 550 5.7.1 Your email breaches local URIBL policy.

--574881548263.1296848323/admin1.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 574881548263; Fri,  4 Feb 2011 19:13:33 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1296846813;
	bh=B+QkZsMeyuaBQ6+nOjRUtP8GhqMMtgpAzrZpmNu5Ihk=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=xtSQk5Gu+BCQUcnNtlW3KReQlaMV9/vb/IoKEFwoF4Qkf5fDKPuwYikxgXyFfEgPO
	 fCX+3KwR4lWMjcbonNkKtpV8a64pNVbE3uXBzgGt3UGhkAfUQ82rrfOt8c9V1uLuas
	 qupQ2NJ+d4mZJDg2H27GIJT9VFc1cngsUBVfttL0=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_12968468137131270"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Fri, 4 Feb 2011 19:13:33 +0000
From: Julia Stevens <julia.stevens@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=DBD27190-3092-11E0-A323-F8A354C7E16D>
To: Fred Bloggs <fred.bloggs@example2.co.uk>
Message-Id: <20110204191333.574881548263@admin1.example.co.uk>

--574881548263.1296848323/admin1.example.co.uk--
