X-Original-To: xyzzy@example.com
Delivered-To: xyzzy@example.com
Received: from lb-ob1.listbox.com (lb-ob1.int.icgroup.com [10.80.90.22])
	by arc1.listbox.com (Postfix) with ESMTP id 8DDA615579
	for <xyzzy@example.com>; Thu, 12 Mar 2015 10:52:04 -0400 (EDT)
Received: by lb-ob1.listbox.com (Postfix)
	id 3694E10A90; Thu, 12 Mar 2015 10:51:57 -0400 (EDT)
Date: Thu, 12 Mar 2015 10:51:57 -0400 (EDT)
From: MAILER-DAEMON@lb-ob1.listbox.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: xyzzy@example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="CA08D10991.1426171917/lb-ob1.listbox.com"
Message-Id: <20150312145157.3694E10A90@lb-ob1.listbox.com>

This is a MIME-encapsulated message.

--CA08D10991.1426171917/lb-ob1.listbox.com
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host lb-ob1.listbox.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<yourface@example.gov>: host example.gov[123.4.5.67] said:
    554 Service unavailable; Client host [208.72.237.4] blocked using
    bl.spamcop.net; Blocked - see http://www.spamcop.net/bl.shtml?208.72.237.4
    (in reply to RCPT TO command)

--CA08D10991.1426171917/lb-ob1.listbox.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; lb-ob1.listbox.com
X-Postfix-Queue-ID: CA08D10991
X-Postfix-Sender: rfc822; xyzzy@example.com
Arrival-Date: Thu, 12 Mar 2015 10:51:55 -0400 (EDT)

Final-Recipient: rfc822; yourface@example.gov
Original-Recipient: rfc822;yourface@example.gov
Action: failed
Status: 5.0.0
Remote-MTA: dns; example.gov
Diagnostic-Code: smtp; 554 Service unavailable; Client host [208.72.237.4]
    blocked using bl.spamcop.net; Blocked - see
    http://www.spamcop.net/bl.shtml?208.72.237.4

--CA08D10991.1426171917/lb-ob1.listbox.com
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Return-Path: <xyzzy@example.com>
Received: from lb-ob1.listbox.com (localhost [127.0.0.1])
	by lb-ob1.listbox.com (Postfix) with ESMTP id CA08D10991
	for <yourface@example.com>; Thu, 12 Mar 2015 10:51:55 -0400 (EDT)
Date: Thu, 12 Mar 2015 10:51:21 -0400
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="1426171881.A3d7c0.99000"
Message-Id: <F62F7D0E-C8C2-11E4-B132-EB6EAB8B1A2B@v3.composer.listbox.com>
Subject: Express Message
From: "Education" <education@example.gov>
To: "Your Face" <yourface@example.gov>
X-Listbox-Composer: Listbox2::Composer v3
Reply-To: education@example.gov
List-ID: <example-list@example.com>
List-Software: listbox.com v2.0
List-Help: <http://www.listbox.com/subscription-help.html>
Precedence: list
Errors-To: xyzzy@listbox.com

--CA08D10991.1426171917/lb-ob1.listbox.com--
