Delivered-To: automated-bounces+64dd736c-fb14-11e0-8fd4-e50a16514328@email.example.com
Received: by 10.229.184.67 with SMTP id cj3cs207864qcb;
        Thu, 20 Oct 2011 05:30:20 -0700 (PDT)
Received: by 10.216.138.221 with SMTP id a71mr4186633wej.102.1319113819652;
        Thu, 20 Oct 2011 05:30:19 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id z32si6804375weq.133.2011.10.20.05.30.19;
        Thu, 20 Oct 2011 05:30:19 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 40B8865108D; Thu, 20 Oct 2011 13:30:19 +0100 (BST)
Date: Thu, 20 Oct 2011 13:30:19 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+64DD736C-FB14-11E0-8FD4-E50A16514328@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="4B94C65106A.1319113819/admin1.example.co.uk"
Message-Id: <20111020123019.40B8865108D@admin1.example.co.uk>

This is a MIME-encapsulated message.

--4B94C65106A.1319113819/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred@example.net>: host a.mx.example.net[213.162.120.70] said: 550
    5.7.1 You're using a mass mailer, therefore you're bounced. (in reply to
    end of DATA command)

--4B94C65106A.1319113819/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 4B94C65106A
X-Postfix-Sender: rfc822; automated-bounces+64DD736C-FB14-11E0-8FD4-E50A16514328@email.example.com
Arrival-Date: Thu, 20 Oct 2011 13:09:43 +0100 (BST)

Final-Recipient: rfc822; fred@example.net
Action: failed
Status: 5.7.1
Remote-MTA: dns; a.mx.example.net
Diagnostic-Code: smtp; 550 5.7.1 You're using a mass mailer, therefore you're
    bounced.

--4B94C65106A.1319113819/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 4B94C65106A; Thu, 20 Oct 2011 13:09:43 +0100 (BST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=email.example.com;
	s=default10; t=1319112583;
	bh=nVOidzxGwLzWAOSa6+LP6YjsuvPGLgxKXHz6gSEhAN0=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=zB3lH1I+AIN4GuYta1GZ6zrgor5AnEToTuTPFwpr0oR6WCmPkohZysraPtfF6JTp1
	 LzcbD7p9+qpVqtpQUhnGBZABI0AwNjdZBg7Bjf8GUYSl3vVCSiqKsKUe3OMOrUBCo2
	 4I/5g7Z0paylPkm26sESl1YNrSWKxj5j1y6dbu5g=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1319112583110380"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Thu, 20 Oct 2011 13:09:43 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=64DD736C-FB14-11E0-8FD4-E50A16514328>
To: fred bloggs <fred@example.net>
Message-Id: <20111020120943.4B94C65106A@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1319112583110380
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_1319112583110380--


--4B94C65106A.1319113819/admin1.example.co.uk--
