Delivered-To: automated-bounces+52d7a428-b84b-11e0-8d18-a5f6cca7f7ec@email.example.com
Received: by 10.142.214.7 with SMTP id m7cs195321wfg;
        Wed, 27 Jul 2011 05:24:17 -0700 (PDT)
Received: by 10.227.178.134 with SMTP id bm6mr350968wbb.75.1311769455827;
        Wed, 27 Jul 2011 05:24:15 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id fe3si129344wbb.27.2011.07.27.05.24.14;
        Wed, 27 Jul 2011 05:24:14 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id C5F756510B3; Wed, 27 Jul 2011 13:24:13 +0100 (BST)
Date: Wed, 27 Jul 2011 13:24:13 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+52D7A428-B84B-11E0-8D18-A5F6CCA7F7EC@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="50F966510B0.1311769453/admin1.example.co.uk"
Message-Id: <20110727122413.C5F756510B3@admin1.example.co.uk>

This is a MIME-encapsulated message.

--50F966510B0.1311769453/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<j.bloggs@sample.net>: host renko.ucs.sample.net[129.215.13.3] said: 554 5.7.1 Spam
    score (12.878) too high: see http://www.sample.net/is/email/error (in reply
    to end of DATA command)

--50F966510B0.1311769453/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 50F966510B0
X-Postfix-Sender: rfc822; automated-bounces+52D7A428-B84B-11E0-8D18-A5F6CCA7F7EC@email.example.com
Arrival-Date: Wed, 27 Jul 2011 13:24:07 +0100 (BST)

Final-Recipient: rfc822; j.bloggs@sample.net
Action: failed
Status: 5.7.1
Remote-MTA: dns; renko.ucs.sample.net
Diagnostic-Code: smtp; 554 5.7.1 Spam score (12.878) too high: see
    http://www.sample.net/is/email/error

--50F966510B0.1311769453/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 50F966510B0; Wed, 27 Jul 2011 13:24:07 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_131176944712523624"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Wed, 27 Jul 2011 13:24:07 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=52D7A428-B84B-11E0-8D18-A5F6CCA7F7EC>
To: Joe Bloggs <j.bloggs@sample.net>
Message-Id: <20110727122407.50F966510B0@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_131176944712523624
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_131176944712523624--


--50F966510B0.1311769453/admin1.example.co.uk--
