Delivered-To: automated-bounces@email.example.com
Received: by 10.142.82.8 with SMTP id f8cs13791wfb;
        Sat, 22 Oct 2011 16:05:56 -0700 (PDT)
Received: by 10.227.19.203 with SMTP id c11mr7114016wbb.107.1319324754892;
        Sat, 22 Oct 2011 16:05:54 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id 18si2548262wbx.45.2011.10.22.16.05.54;
        Sat, 22 Oct 2011 16:05:54 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id ED21C651165; Sun, 23 Oct 2011 00:05:53 +0100 (BST)
Date: Sun, 23 Oct 2011 00:05:53 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="5822365117D.1319324753/admin1.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20111022230553.ED21C651165@admin1.example.co.uk>

This is a MIME-encapsulated message.

--5822365117D.1319324753/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<Fred.Bloggs@example.net>: host mailgate.test.com[217.158.5.8]
    said: 554 Spam email. Email Session ID: {4EA34C51-0-5059ED9-FFFF} (in reply
    to end of DATA command)

--5822365117D.1319324753/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 5822365117D
X-Postfix-Sender: rfc822; automated-bounces@email.example.com
Arrival-Date: Sun, 23 Oct 2011 00:05:53 +0100 (BST)

Final-Recipient: rfc822; Fred.Bloggs@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mailgate.test.com
Diagnostic-Code: smtp; 554 Spam email. Email Session ID:
    {4EA34C51-0-5059ED9-FFFF}

--5822365117D.1319324753/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 5822365117D; Sun, 23 Oct 2011 00:05:53 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/alternative; boundary="_----------=_131932475319825307"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Sun, 23 Oct 2011 00:05:53 +0100
From: John Smith <john.smith@example.com>
To: Fred.Bloggs@example.net, ms@example.com
Subject: foo
Message-Id: <20111022230553.5822365117D@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_131932475319825307
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text

--_----------=_131932475319825307
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html

HTML

--_----------=_131932475319825307--


--5822365117D.1319324753/admin1.example.co.uk--
