Delivered-To: automated-bounces+a4fab39c-a39a-11df-8cc9-ee77dd31f8f5@email.example.com
Received: by 10.220.190.129 with SMTP id di1cs100929vcb;
        Mon, 9 Aug 2010 02:44:06 -0700 (PDT)
Received: by 10.216.9.3 with SMTP id 3mr13583021wes.66.1281347045553;
        Mon, 09 Aug 2010 02:44:05 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id f63si6704856wej.70.2010.08.09.02.44.04;
        Mon, 09 Aug 2010 02:44:05 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id DDC76165830A; Mon,  9 Aug 2010 10:44:04 +0100 (BST)
Date: Mon,  9 Aug 2010 10:44:04 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+A4FAB39C-A39A-11DF-8CC9-EE77DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="4607E1658308.1281347044/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100809094404.DDC76165830A@server4.example.co.uk>

This is a MIME-encapsulated message.

--4607E1658308.1281347044/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<a@b.c>: host mail.b.c[213.167.71.35] said:
    550 "Sorry, your message has triggered a SPAM block, please contact the
    postmaster" (in reply to end of DATA command)

--4607E1658308.1281347044/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 4607E1658308
X-Postfix-Sender: rfc822; automated-bounces+A4FAB39C-A39A-11DF-8CC9-EE77DD31F8F5@email.example.com
Arrival-Date: Mon,  9 Aug 2010 10:44:03 +0100 (BST)

Final-Recipient: rfc822; a@b.c
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.b.c
Diagnostic-Code: smtp; 550 "Sorry, your message has triggered a SPAM block,
    please contact the postmaster"

--4607E1658308.1281347044/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 4607E1658308; Mon,  9 Aug 2010 10:44:03 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_128134704315142705"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 9 Aug 2010 10:44:03 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=A4FAB39C-A39A-11DF-8CC9-EE77DD31F8F5>
To: John Smith <a@b.c>
Message-Id: <20100809094403.4607E1658308@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_128134704315142705
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html

hello

--_----------=_128134704315142705--


--4607E1658308.1281347044/server4.example.co.uk--
