Delivered-To: automated-bounces+7b498d02-12ec-11e2-9ae1-ad6ac6a83a92@email.example.com
Received: by 10.14.45.2 with SMTP id o2csp619772eeb;
        Wed, 10 Oct 2012 08:09:22 -0700 (PDT)
Received: by 10.216.195.229 with SMTP id p79mr13918829wen.163.1349881762104;
        Wed, 10 Oct 2012 08:09:22 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id d4si32914240wie.16.2012.10.10.08.09.22;
        Wed, 10 Oct 2012 08:09:22 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id EF90365131A; Wed, 10 Oct 2012 16:09:21 +0100 (BST)
Date: Wed, 10 Oct 2012 16:09:21 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+7B498D02-12EC-11E2-9AE1-AD6AC6A83A92@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="34FC0651304.1349881761/admin1.example.co.uk"
Message-Id: <20121010150921.EF90365131A@admin1.example.co.uk>

This is a MIME-encapsulated message.

--34FC0651304.1349881761/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred.bloggs@sample.co.uk>: host
    mail.sample.co.uk[213.120.102.43] said: 550 Error: SPAM NOT
    ACCEPTED (in reply to end of DATA command)

--34FC0651304.1349881761/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 34FC0651304
X-Postfix-Sender: rfc822; automated-bounces+7B498D02-12EC-11E2-9AE1-AD6AC6A83A92@email.example.com
Arrival-Date: Wed, 10 Oct 2012 16:09:14 +0100 (BST)

Final-Recipient: rfc822; fred.bloggs@sample.co.uk
Original-Recipient: rfc822;fred.bloggs@sample.co.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.sample.co.uk
Diagnostic-Code: smtp; 550 Error: SPAM NOT ACCEPTED

--34FC0651304.1349881761/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: from cloudadmin1.example.co.uk (cloudadmin1 [10.177.197.82])
	by admin1.example.co.uk (Postfix) with ESMTP id 34FC0651304;
	Wed, 10 Oct 2012 16:09:14 +0100 (BST)
Authentication-Results: admin1.example.co.uk; dkim=pass (1024-bit key)
	header.i=@email.example.com; x-dkim-adsp=pass
Received: by cloudadmin1.example.co.uk (Postfix, from userid 507)
	id 181E41E805E; Wed, 10 Oct 2012 16:09:27 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1349881766140110"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Wed, 10 Oct 2012 16:09:26 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=7B498D02-12EC-11E2-9AE1-AD6AC6A83A92>
To: Fred Bloggs <fred.bloggs@sample.co.uk>
Message-Id: <20121010150927.181E41E805E@cloudadmin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1349881766140110
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here.

--_----------=_1349881766140110--


--34FC0651304.1349881761/admin1.example.co.uk--
