Delivered-To: automated-bounces+079c63a6-a40c-11e1-8e57-fdc3357ce2f2@email.example.com
Received: by 10.52.101.202 with SMTP id fi10csp66229vdb;
        Tue, 22 May 2012 05:45:39 -0700 (PDT)
Received: by 10.180.100.230 with SMTP id fb6mr34277798wib.3.1337690738874;
        Tue, 22 May 2012 05:45:38 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id m18si23929914wee.2.2012.05.22.05.45.38;
        Tue, 22 May 2012 05:45:38 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 45FA1651327; Tue, 22 May 2012 13:45:38 +0100 (BST)
Date: Tue, 22 May 2012 13:45:38 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+079C63A6-A40C-11E1-8E57-FDC3357CE2F2@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="3B0D0651325.1337690738/admin1.example.co.uk"
Message-Id: <20120522124538.45FA1651327@admin1.example.co.uk>

This is a MIME-encapsulated message.

--3B0D0651325.1337690738/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@sample.com>: host smtp1.sample.com[160.83.90.10] said: 551 5.0.0 This
    message was classified as spam (in reply to end of DATA command)

--3B0D0651325.1337690738/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 3B0D0651325
X-Postfix-Sender: rfc822; automated-bounces+079C63A6-A40C-11E1-8E57-FDC3357CE2F2@email.example.com
Arrival-Date: Tue, 22 May 2012 13:45:37 +0100 (BST)

Final-Recipient: rfc822; recipient@sample.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; smtp1.sample.com
Diagnostic-Code: smtp; 551 5.0.0 This message was classified as spam

--3B0D0651325.1337690738/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 3B0D0651325; Tue, 22 May 2012 13:45:37 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1337690737822077"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Tue, 22 May 2012 13:45:37 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=079C63A6-A40C-11E1-8E57-FDC3357CE2F2>
To: john smith <recipient@sample.com>
Message-Id: <20120522124537.3B0D0651325@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1337690737822077
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_1337690737822077--


--3B0D0651325.1337690738/admin1.example.co.uk--
