Delivered-To: automated-bounces+f92ca4a0-2bef-11e1-927f-84fab919b2cb@email.example.com
Received: by 10.52.111.104 with SMTP id ih8cs22319vdb;
        Wed, 21 Dec 2011 08:22:33 -0800 (PST)
Received: by 10.180.83.69 with SMTP id o5mr15750550wiy.1.1324484551981;
        Wed, 21 Dec 2011 08:22:31 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id r58si3070623weq.43.2011.12.21.08.22.31;
        Wed, 21 Dec 2011 08:22:31 -0800 (PST)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 8A74D651990; Wed, 21 Dec 2011 16:22:31 +0000 (GMT)
Date: Wed, 21 Dec 2011 16:22:31 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+F92CA4A0-2BEF-11E1-927F-84FAB919B2CB@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="93DF065198D.1324484551/admin1.example.co.uk"
Message-Id: <20111221162231.8A74D651990@admin1.example.co.uk>

This is a MIME-encapsulated message.

--93DF065198D.1324484551/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example2.com>: host relay.example2.com[89.151.107.90] said: 554
    rejected due to spam content (in reply to end of DATA command)

--93DF065198D.1324484551/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 93DF065198D
X-Postfix-Sender: rfc822; automated-bounces+F92CA4A0-2BEF-11E1-927F-84FAB919B2CB@email.example.com
Arrival-Date: Wed, 21 Dec 2011 16:22:27 +0000 (GMT)

Final-Recipient: rfc822; john.smith@example2.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; relay.example2.com
Diagnostic-Code: smtp; 554 rejected due to spam content

--93DF065198D.1324484551/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 93DF065198D; Wed, 21 Dec 2011 16:22:27 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_132448454767310"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Wed, 21 Dec 2011 16:22:27 +0000
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=F92CA4A0-2BEF-11E1-927F-84FAB919B2CB>
To: John Smith <john.smith@example2.com>
Message-Id: <20111221162227.93DF065198D@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_132448454767310
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_132448454767310--


--93DF065198D.1324484551/admin1.example.co.uk--
