Delivered-To: automated-bounces+ca0cfcc8-e5a6-11df-a994-e859dd31f8f5@email.dianomi.com
Received: by 10.204.50.199 with SMTP id a7cs129629bkg;
        Mon, 1 Nov 2010 03:57:37 -0700 (PDT)
Received: by 10.216.142.131 with SMTP id i3mr2533849wej.5.1288609057497;
        Mon, 01 Nov 2010 03:57:37 -0700 (PDT)
Return-Path: <>
Received: from mail.apetito.co.uk (mail.apetito.co.uk [194.72.240.146])
        by mx.google.com with ESMTP id x80si8867099weq.80.2010.11.01.03.57.37;
        Mon, 01 Nov 2010 03:57:37 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of mail.apetito.co.uk designates 194.72.240.146 as permitted sender) client-ip=194.72.240.146;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of mail.apetito.co.uk designates 194.72.240.146 as permitted sender) smtp.mail=
MIME-Version: 1.0
From: MAILER-DAEMON
Message-ID: <20101101105716.2DC3A16581BC@server4.dianomi.co.uk>
Subject: **Message you sent blocked by our bulk email filter**
Content-Type: multipart/report; report-type=delivery-status;
 charset=utf-8;
 boundary="----------=_1288609057-11092-1"
To: <automated-bounces+CA0CFCC8-E5A6-11DF-A994-E859DD31F8F5@email.dianomi.com>
Date: Mon,  1 Nov 2010 10:57:37 +0000 (GMT)

This is a multi-part message in MIME format...

------------=_1288609057-11092-1
Content-Type: text/plain; charset="utf-8"
Content-Disposition: inline
Content-Transfer-Encoding: base64

WW91ciBtZXNzYWdlIHRvOiBSSUNIQVJELlJJTkdAQVBFVElUTy5DTy5VSw0K
d2FzIGJsb2NrZWQgYnkgb3VyIFNwYW0gJiBWaXJ1cyBGaXJld2FsbC4gVGhl
IGVtYWlsIHlvdSBzZW50IHdpdGggdGhlIGZvbGxvd2luZyBzdWJqZWN0IGhh
cyBOT1QgQkVFTiBERUxJVkVSRUQ6DQoNClN1YmplY3Q6IERlYXIgTXIgUmlu
ZywgZGlkIHlvdSBmaW5kIHRoZSBDYXIgeW91IHdlcmUgbG9va2luZyBmb3I/
DQoNClRoaXMgbWVzc2FnZSBoYXMgbm90IGJlZW4gZGVsZXRlZCwgaWYgeW91
IGJlbGlldmUgdGhpcyB3YXMgaW4gZXJyb3IsIHBsZWFzZSBmb3J3YXJkIHRo
ZSBvcmlnaW5hbCBtYWlsIHRvIGFudGlzcGFtQGFwZXRpdG8uY28udWsgd2hl
cmUgb3VyIElUIFNlcnZpY2UgdGVhbSB3aWxsIHJldmlldyB0aGUgbWVzc2Fn
ZS4NCg0KWW91cnMgcmVncmV0ZnVsbHkgDQoNCmFwZXRpdG8gSVQgU2Vydmlj
ZSBUZWFtDQpQaG9uZSAwMTIyNSA3NTYwOTIK

------------=_1288609057-11092-1
Content-Type: message/delivery-status
Content-Disposition: inline
Content-Transfer-Encoding: 7bit
Content-Description: Delivery error report

Reporting-MTA: dns; mail.apetito.co.uk
Received-From-MTA: smtp; mail.apetito.co.uk ([127.0.0.1])
Arrival-Date: Mon,  1 Nov 2010 10:57:29 +0000 (GMT)

Final-Recipient: rfc822; RICHARD.RING@APETITO.CO.UK
Action: failed
Status: 5.7.1
Diagnostic-Code: smtp; 550 5.7.1 Message content rejected, UBE, id=11092-02-101
Last-Attempt-Date: Mon,  1 Nov 2010 10:57:37 +0000 (GMT)

------------=_1288609057-11092-1
Content-Type: text/rfc822-headers
Content-Disposition: inline
Content-Transfer-Encoding: 7bit
Content-Description: Undelivered-message headers

Received: from server4.dianomi.co.uk (server4.dianomi.co.uk [94.236.45.212]) by mail.apetito.co.uk with ESMTP id cL9J3qViOY8BeYoU for <RICHARD.RING@APETITO.CO.UK>; Mon, 01 Nov 2010 10:57:17 +0000 (GMT)
Received: by server4.dianomi.co.uk (Postfix, from userid 507)
	id 2DC3A16581BC; Mon,  1 Nov 2010 10:57:16 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.dianomi.com;
	s=default10; t=1288609036;
	bh=U5u7yAkLcum42DgkpoVppfAD5xFJaqM592XWVSljB18=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=SM/JRPpvHs1nXMEZshaM1dD6PEOhfi6k1jucfMCmpYF6o7uicW7ZcX7PdlfqdFeAU
	 JjOo3s+h9GzFTMtWkETqEW0aY7x/W5dzS+YImjGf1UELtvv+kfTSp0c/u/WUO9XN4l
	 JGXz28j6Od80TkXqXI9owiav44o10RHVr/l79Fd4=
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_128860903674561092"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 1 Nov 2010 10:57:16 +0000
From: Julia Stevens <julia.stevens@email.dianomi.com>
Subject: Dear Mr Ring, did you find the Car you were looking for?
List-Unsubscribe: <http://www.dianomioffers.co.uk/unsubscribe.epl?uuid=CA0CFCC8-E5A6-11DF-A994-E859DD31F8F5>
To: RICHARD RING <RICHARD.RING@APETITO.CO.UK>
Message-Id: <20101101105716.2DC3A16581BC@server4.dianomi.co.uk>
X-Virus-Scanned: by bsmtpd at apetito.co.uk

------------=_1288609057-11092-1--
