Delivered-To: automated-bounces@example.com
Received: by 10.211.179.3 with SMTP id g3cs24102ebp;
        Thu, 16 Jul 2009 08:52:41 -0700 (PDT)
Received: by 10.210.82.2 with SMTP id f2mr1786123ebb.16.1247759561164;
        Thu, 16 Jul 2009 08:52:41 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [212.100.234.46])
        by mx.google.com with ESMTP id 6si324106ewy.30.2009.07.16.08.52.41;
        Thu, 16 Jul 2009 08:52:41 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) client-ip=212.100.234.46;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 006F971DEB3; Thu, 16 Jul 2009 16:52:41 +0100 (BST)
Date: Thu, 16 Jul 2009 16:52:41 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces@example.com
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="4754671DEA0.1247759561/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20090716155241.006F971DEB3@server4.example.co.uk>

This is a MIME-encapsulated message.

--4754671DEA0.1247759561/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain

This is the Postfix program at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

			The Postfix program

<exampleuser@exampleclient.com>: host mx.exampleclient.com[1.2.3.4] said: 550
    5.7.1 Blocked by SpamAssassin (in reply to end of DATA command)

--4754671DEA0.1247759561/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 4754671DEA0
X-Postfix-Sender: rfc822; automated-bounces@example.com
Arrival-Date: Thu, 16 Jul 2009 16:52:38 +0100 (BST)

Final-Recipient: rfc822; exampleuser@exampleclient.com
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; host mx.exampleclient.com[1.2.3.4] said: 550
    5.7.1 Blocked by SpamAssassin (in reply to end of DATA command)

--4754671DEA0.1247759561/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 4754671DEA0; Thu, 16 Jul 2009 16:52:38 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_1247759558130622758"
X-Mailer: MIME::Lite 3.021 (F2.73; T1.22; A2.04; B3.08; Q3.08)
Date: Thu, 16 Jul 2009 16:52:38 +0100
From: Customer Services <customerservices@example.co.uk>
To: exampleuser@exampleclient.com
Subject: BLEH
List-Unsubscribe: <>
Message-Id: <20090716155238.4754671DEA0@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1247759558130622758
Content-Disposition: inline
Content-Length: 3361
Content-Transfer-Encoding: binary
Content-Type: text/html

body
 --_----------=_1247759558130622758--


--4754671DEA0.1247759561/server4.example.co.uk--
