Delivered-To: automated-bounces+267ace36-b292-11e1-8573-aef4e4e96c2b@email.sample.com
Received: by 10.52.101.202 with SMTP id fi10csp52380vdb;
        Sat, 9 Jun 2012 20:49:46 -0700 (PDT)
Received: by 10.216.216.1 with SMTP id f1mr4144213wep.24.1339300185212;
        Sat, 09 Jun 2012 20:49:45 -0700 (PDT)
Return-Path: <>
Received: from admin1.sample.co.uk (admin1.sample.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id dr8si9587699wib.16.2012.06.09.20.49.44;
        Sat, 09 Jun 2012 20:49:45 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.sample.co.uk (Postfix)
	id 8960E6512E1; Sun, 10 Jun 2012 04:49:44 +0100 (BST)
Date: Sun, 10 Jun 2012 04:49:44 +0100 (BST)
From: MAILER-DAEMON@admin1.sample.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+267ACE36-B292-11E1-8573-AEF4E4E96C2B@email.sample.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="08CB26512B7.1339300184/admin1.sample.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20120610034944.8960E6512E1@admin1.sample.co.uk>

This is a MIME-encapsulated message.

--08CB26512B7.1339300184/admin1.sample.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.sample.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.com.au>: host globala.test.com.au[130.94.124.172]
    said: 554 5.7.1 554 5.7.1 Your email appears similar to spam we have
    received before.  We urge you to modify your message and resend it. (in
    reply to end of DATA command)

--08CB26512B7.1339300184/admin1.sample.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.sample.co.uk
X-Postfix-Queue-ID: 08CB26512B7
X-Postfix-Sender: rfc822; automated-bounces+267ACE36-B292-11E1-8573-AEF4E4E96C2B@email.sample.com
Arrival-Date: Sun, 10 Jun 2012 01:20:58 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.com.au
Action: failed
Status: 5.7.1
Remote-MTA: dns; globala.test.com.au
Diagnostic-Code: smtp; 554 5.7.1 554 5.7.1 Your email appears similar to spam
    we have received before.  We urge you to modify your message and resend it.

--08CB26512B7.1339300184/admin1.sample.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by admin1.sample.co.uk (Postfix, from userid 507)
	id 08CB26512B7; Sun, 10 Jun 2012 01:20:58 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_13392876582779110"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Sun, 10 Jun 2012 01:20:58 +0100
From: Fred Bloggs <fred.bloggs@email.sample.com>
Subject: foo
X-Campaignid: sample20110704.1
List-Unsubscribe: <http://www.sampleoffers.co.uk/unsubscribe.epl?uuid=267ACE36-B292-11E1-8573-AEF4E4E96C2B>
To: John Smith <john.smith@example.com.au>
Message-Id: <20120610002058.08CB26512B7@admin1.sample.co.uk>

This is a multi-part message in MIME format.

--_----------=_13392876582779110
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text goes here. 
  
--_----------=_13392876582779110
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here

--_----------=_13392876582779110--


--08CB26512B7.1339300184/admin1.sample.co.uk--
