Delivered-To: automated-bounces+7be1d472-4b2d-11e1-9e82-a342cb4aa966@email.example.com
Received: by 10.52.116.40 with SMTP id jt8cs206783vdb;
        Mon, 30 Jan 2012 02:50:22 -0800 (PST)
Received: by 10.180.14.105 with SMTP id o9mr21209595wic.11.1327920621651;
        Mon, 30 Jan 2012 02:50:21 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id i7si3760513wed.114.2012.01.30.02.50.21;
        Mon, 30 Jan 2012 02:50:21 -0800 (PST)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 2DB1D65126B; Mon, 30 Jan 2012 10:50:21 +0000 (GMT)
Date: Mon, 30 Jan 2012 10:50:21 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+7BE1D472-4B2D-11E1-9E82-A342CB4AA966@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="42C5A6512A6.1327920621/admin1.example.co.uk"
Message-Id: <20120130105021.2DB1D65126B@admin1.example.co.uk>

This is a MIME-encapsulated message.

--42C5A6512A6.1327920621/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@sample.co.uk>: host service101.mimecast.com[91.220.42.51] said: 554
    email rejected due to security policies - MCSpamSignature.sa.5.6 (in reply
    to end of DATA command)

--42C5A6512A6.1327920621/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 42C5A6512A6
X-Postfix-Sender: rfc822; automated-bounces+7BE1D472-4B2D-11E1-9E82-A342CB4AA966@email.example.com
Arrival-Date: Mon, 30 Jan 2012 10:30:52 +0000 (GMT)

Final-Recipient: rfc822; john.smith@sample.co.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; service101.mimecast.com
Diagnostic-Code: smtp; 554 email rejected due to security policies -
    MCSpamSignature.sa.5.6

--42C5A6512A6.1327920621/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 42C5A6512A6; Mon, 30 Jan 2012 10:30:52 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_13279194522009234"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Mon, 30 Jan 2012 10:30:52 +0000
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
To: John Smith <john.smith@sample.co.uk>
Message-Id: <20120130103052.42C5A6512A6@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_13279194522009234
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_13279194522009234--


--42C5A6512A6.1327920621/admin1.example.co.uk--
 FLAGS (\Seen)
