Delivered-To: automated-bounces+a850d73e-b2c4-11e1-9e53-ae85764d2566@email.example.com
Received: by 10.52.101.202 with SMTP id fi10csp56996vdb;
        Sat, 9 Jun 2012 23:22:41 -0700 (PDT)
Received: by 10.216.228.98 with SMTP id e76mr3917073weq.150.1339309360745;
        Sat, 09 Jun 2012 23:22:40 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id z9si9936975wiv.46.2012.06.09.23.22.40;
        Sat, 09 Jun 2012 23:22:40 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 30D2B6512C3; Sun, 10 Jun 2012 07:22:40 +0100 (BST)
Date: Sun, 10 Jun 2012 07:22:40 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+A850D73E-B2C4-11E1-9E53-AE85764D2566@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="82CF86512E1.1339309360/admin1.example.co.uk"
Message-Id: <20120610062240.30D2B6512C3@admin1.example.co.uk>

This is a MIME-encapsulated message.

--82CF86512E1.1339309360/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@sample.ac.uk>: host mailgateway.sample.ac.uk[194.66.96.7]
    said: 550 Message refused by MailMarshal SpamProfiler (in reply to end of
    DATA command)

--82CF86512E1.1339309360/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 82CF86512E1
X-Postfix-Sender: rfc822; automated-bounces+A850D73E-B2C4-11E1-9E53-AE85764D2566@email.example.com
Arrival-Date: Sun, 10 Jun 2012 07:22:30 +0100 (BST)

Final-Recipient: rfc822; john.smith@sample.ac.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; mailgateway.sample.ac.uk
Diagnostic-Code: smtp; 550 Message refused by MailMarshal SpamProfiler

--82CF86512E1.1339309360/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 82CF86512E1; Sun, 10 Jun 2012 07:22:30 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_13393093503185416"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Sun, 10 Jun 2012 07:22:30 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
To: John Smith <john.smith@sample.ac.uk>
Message-Id: <20120610062230.82CF86512E1@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_13393093503185416
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here

--_----------=_13393093503185416--


--82CF86512E1.1339309360/admin1.example.co.uk--
