Delivered-To: automated-bounces+ef6d04e6-f38c-11e0-854f-be0087d98979@email.example.com
Received: by 10.180.105.100 with SMTP id gl4cs124817wib;
        Mon, 10 Oct 2011 15:12:47 -0700 (PDT)
Received: by 10.227.200.146 with SMTP id ew18mr7056930wbb.16.1318284766356;
        Mon, 10 Oct 2011 15:12:46 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id fl17si14714845wbb.107.2011.10.10.15.12.46;
        Mon, 10 Oct 2011 15:12:46 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id EBB3B651198; Mon, 10 Oct 2011 23:12:45 +0100 (BST)
Date: Mon, 10 Oct 2011 23:12:45 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+EF6D04E6-F38C-11E0-854F-BE0087D98979@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="E8E46651197.1318284765/admin1.example.co.uk"
Message-Id: <20111010221245.EBB3B651198@admin1.example.co.uk>

This is a MIME-encapsulated message.

--E8E46651197.1318284765/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred.bloggs@test.co.ug>: host mail.broadbandcompany.ug[41.138.0.6] said:
    554 Failure Spam content matched. Fix using:
    http://test.co.ug/cgi/user.cgi?cmd=r&f=15436278 (in reply to end of
    DATA command)

--E8E46651197.1318284765/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: E8E46651197
X-Postfix-Sender: rfc822; automated-bounces+EF6D04E6-F38C-11E0-854F-BE0087D98979@email.example.com
Arrival-Date: Mon, 10 Oct 2011 23:12:25 +0100 (BST)

Final-Recipient: rfc822; fred.bloggs@test.co.ug
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.broadbandcompany.ug
Diagnostic-Code: smtp; 554 Failure Spam content matched. Fix using:
    http://test.co.ug/cgi/user.cgi?cmd=r&f=15436278

--E8E46651197.1318284765/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id E8E46651197; Mon, 10 Oct 2011 23:12:25 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_131828474589660"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Mon, 10 Oct 2011 23:12:25 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
X-Campaignid: example20100129.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=EF6D04E6-F38C-11E0-854F-BE0087D98979>
To: fred bloggs <fred.bloggs@test.co.ug>
Message-Id: <20111010221225.E8E46651197@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_131828474589660
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_131828474589660--


--E8E46651197.1318284765/admin1.example.co.uk--
