Delivered-To: automated-bounces+d8dbc0c0-f562-11de-958c-f50b0eb451e0@email.example.com
Return-Path: <>
Received-SPF: neutral (google.com: 212.137.44.177 is neither permitted nor denied by best guess record for domain of relay.b.c) client-ip=212.137.44.177;
Authentication-Results: mx.google.com; spf=neutral (google.com: 212.137.44.177 is neither permitted nor denied by best guess record for domain of relay.b.c) smtp.mail=
Received: from avas-checker
	by relay-outbound-6 with esmtp (Relay-Software 4.52)
	id 1NQ1gf-0001FN-K9
	for automated-bounces+D8DBC0C0-F562-11DE-958C-F50B0EB451E0@email.example.com; Wed, 30 Dec 2009 16:46:17 +0000
Received: from relay.b.c (rlmta11.swi.contact.secure-ops.net [192.168.129.11])
	by rlavas04.swi.contact.secure-ops.net (MOS 3.8.3-GA)
	with ESMTP id FBO47144;
	Wed, 30 Dec 2009 16:46:17 GMT
Received: from [10.16.38.123] (helo=a.b.c)
	by relay-inbound-11 with esmtp (Relay-Software 4.52)
	id 1NQ1gf-0004rl-Zo
	for automated-bounces+D8DBC0C0-F562-11DE-958C-F50B0EB451E0@email.example.com; Wed, 30 Dec 2009 16:46:17 +0000
Received: by a.b.c (Postfix)
	id E90A08E5041; Wed, 30 Dec 2009 16:43:22 +0000 (GMT)
Date: Wed, 30 Dec 2009 16:43:22 +0000 (GMT)
From: MAILER-DAEMON@a.b.c (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+D8DBC0C0-F562-11DE-958C-F50B0EB451E0@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="A0E518E5027.1262191402/a.b.c"
Message-Id: <20091230164322.E90A08E5041@a.b.c>

This is a MIME-encapsulated message.

--A0E518E5027.1262191402/a.b.c
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host a.b.c.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<a@b.c>: host 10.16.32.166[10.16.32.166] said: 500 Mail
    appears to be unsolicited -- report errors by telephoning the person you
    are emailing so they may add you to our whitelist or spammaster@b.c
    (in reply to end of DATA command)

--A0E518E5027.1262191402/a.b.c
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; a.b.c
X-Postfix-Queue-ID: A0E518E5027
X-Postfix-Sender: rfc822; automated-bounces+D8DBC0C0-F562-11DE-958C-F50B0EB451E0@email.example.com
Arrival-Date: Wed, 30 Dec 2009 16:43:22 +0000 (GMT)

Final-Recipient: rfc822; a@b.c
Original-Recipient: rfc822;a@b.c
Action: failed
Status: 5.0.0
Remote-MTA: dns; 10.16.32.166
Diagnostic-Code: smtp; 500 Mail appears to be unsolicited -- report errors by
    telephoning the person you are emailing so they may add you to our
    whitelist or spammaster@slam.nhs.uk

--A0E518E5027.1262191402/a.b.c
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: from relay.b.c (relay.b.c [194.62.42.123])
	by a.b.c (Postfix) with ESMTP id A0E518E5027
	for <a@b.c>; Wed, 30 Dec 2009 16:43:22 +0000 (GMT)
Received: from avas-checker
	by relay-outbound-3 with esmtp (Relay-Software 4.52)
	id 1NQ1ge-0007WS-Bs
	for a@b.c; Wed, 30 Dec 2009 16:46:16 +0000
Received: from relay.b.c (rlmta05.swi.contact.secure-ops.net [192.168.129.5])
	by rlavas07.swi.contact.secure-ops.net (MOS 3.8.3-GA)
	with ESMTP id FMZ76980;
	Wed, 30 Dec 2009 16:46:16 GMT
Received: from mail-hurdle
	by relay-inbound-5 with esmtp (Relay-Software 4.52)
	id 1NQ1ge-00077c-Hh
	for a@b.c; Wed, 30 Dec 2009 16:46:16 +0000
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
	by rlmh09.swi.contact.secure-ops.net (MOS 3.8.3-GA)
	with ESMTP id QPQ98307;
	Wed, 30 Dec 2009 16:46:16 GMT
Received: by server4.example.co.uk (Postfix, from userid 505)
	id 29FD116581D0; Wed, 30 Dec 2009 16:46:16 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_126219157699683942"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 30 Dec 2009 16:46:16 +0000
From: Customer Services <customerservices@example.co.uk>
To: a@b.c
Subject: stuff
Message-Id: <20091230164616.29FD116581D0@server4.example.co.uk>
X-Junkmail-Status: score=10/50, host=rlavas07.swi.contact.secure-ops.net
X-Junkmail-SD-Raw: score=unknown,
	refid=str=0001.0A0B0209.4B3B83D8.01F4:SCFSTAT10123249,ss=1,fgs=0,
	ip=94.236.45.212,
	so=2006-12-20 11:47:04,
	dmn=5.7.1/2009-08-27
X-Junkmail-IWF: false
X-Mirapoint-RAPID-Raw: score=unknown(0),
	refid=str=0001.0A0B0209.4B3B83D8.01F4:SCFSTAT10123249,ss=1,fgs=0,
	ip=94.236.45.212,
	so=2006-12-20 11:47:04,
	dmn=5.7.1/2009-08-27
X-Mirapoint-Loop-Id: 322ba3a4565edf5b11063d1c9df79a43

This is a multi-part message in MIME format.

--_----------=_126219157699683942
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

html here
--_----------=_126219157699683942--


--A0E518E5027.1262191402/a.b.c--
