Delivered-To: automated-bounces+583532c8-0e08-11e2-b2ad-5a4d5ff98e22@email.example.com
Received: by 10.14.45.2 with SMTP id o2csp109128eeb;
        Thu, 4 Oct 2012 02:44:45 -0700 (PDT)
Received: by 10.216.194.222 with SMTP id m72mr3198449wen.34.1349343885336;
        Thu, 04 Oct 2012 02:44:45 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id n48si7634772wea.157.2012.10.04.02.44.45;
        Thu, 04 Oct 2012 02:44:45 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id EF474651304; Thu,  4 Oct 2012 10:44:44 +0100 (BST)
Date: Thu,  4 Oct 2012 10:44:44 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+583532C8-0E08-11E2-B2AD-5A4D5FF98E22@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="DD942651198.1349343884/admin1.example.co.uk"
Message-Id: <20121004094444.EF474651304@admin1.example.co.uk>

This is a MIME-encapsulated message.

--DD942651198.1349343884/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<fred.bloggs@sample.uk.com>: host mail.sample.uk.com[188.220.16.176] said: 550
    5.7.1 Your message has been rejected because it appears to be SPAM. (in
    reply to end of DATA command)

--DD942651198.1349343884/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: DD942651198
X-Postfix-Sender: rfc822; automated-bounces+583532C8-0E08-11E2-B2AD-5A4D5FF98E22@email.example.com
Arrival-Date: Thu,  4 Oct 2012 10:44:31 +0100 (BST)

Final-Recipient: rfc822; fred.bloggs@sample.uk.com
Original-Recipient: rfc822;fred.bloggs@sample.uk.com
Action: failed
Status: 5.7.1
Remote-MTA: dns; mail.sample.uk.com
Diagnostic-Code: smtp; 550 5.7.1 Your message has been rejected because it
    appears to be SPAM.

--DD942651198.1349343884/admin1.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: from cloudadmin1.example.co.uk (cloudadmin1 [10.177.197.82])
	by admin1.example.co.uk (Postfix) with ESMTP id DD942651198;
	Thu,  4 Oct 2012 10:44:31 +0100 (BST)
Authentication-Results: admin1.example.co.uk; dkim=pass (1024-bit key)
	header.i=@email.example.com; x-dkim-adsp=pass
Received: by cloudadmin1.example.co.uk (Postfix, from userid 507)
	id DE3281E80A3; Thu,  4 Oct 2012 10:46:17 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_134934397796810"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Thu, 4 Oct 2012 10:46:17 +0100
From: John Smith <john.smith@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=583532C8-0E08-11E2-B2AD-5A4D5FF98E22>
To: Fred Bloggs <fred.bloggs@sample.uk.com>
Message-Id: <20121004094617.DE3281E80A3@cloudadmin1.example.co.uk>

--DD942651198.1349343884/admin1.example.co.uk--
