Delivered-To: automated-bounces+5de26bcc-9568-11e2-8887-7d00861e0127@email.example.com
Received: by 10.204.227.207 with SMTP id jb15csp58536bkb;
        Mon, 25 Mar 2013 09:23:54 -0700 (PDT)
X-Received: by 10.60.165.72 with SMTP id yw8mr11682274oeb.7.1364228633673;
        Mon, 25 Mar 2013 09:23:53 -0700 (PDT)
Return-Path: <>
Received: from salsa.example.local ([209.12.149.155])
        by mx.google.com with ESMTPS id cm4si10925042obc.20.2013.03.25.09.23.52
        (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
        Mon, 25 Mar 2013 09:23:53 -0700 (PDT)
Received-SPF: neutral (google.com: 209.12.149.155 is neither permitted nor denied by best guess record for domain of salsa.example.local) client-ip=209.12.149.155;
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 209.12.149.155 is neither permitted nor denied by best guess record for domain of salsa.example.local) smtp.mail=
Received: by salsa.example.local
	with XWall v3.47 ;
	Mon, 25 Mar 2013 10:24:26 -0600
From: System Administrator <postmaster@example.net>
To: "automated-bounces+5DE26BCC-9568-11E2-8887-7D00861E0127@email.example.com" <automated-bounces+5DE26BCC-9568-11E2-8887-7D00861E0127@email.example.com>
Subject: Non delivery report: 5.9.8 (Spam)
Date: Mon, 25 Mar 2013 10:24:26 -0600
X-Mailer: XWall v3.47
Message-ID: <606824666.274601305.2200@salsa.example.local>
Mime-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="_NextPart_1_00o1403flwFztPLyZJHFLDzNYRL"

This is a multi part MIME message.

--_NextPart_1_00o1403flwFztPLyZJHFLDzNYRL
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

Your message

=20From:	John Smith <john.smith@email.example.com>
=09(mail from:automated-bounces+5DE26BCC-9568-11E2-8887-7D00861E0127@email.d=
ianomi.com)

=20To:	Fred Bloggs <fred.bloggs@example.net>

=20Subj:	foo
=20Sent:	2013-03-25 10:23

has encountered a delivery problem.


Reason: Spam
The message seems to be spam and was not delivered to the recipient.

Additional info:
The heuristic spam value is: 34







---
Delivery status:
Date: Mon, 25 Mar 2013 10:24:26 -0600
Reporting-MTA: dns; salsa.example.local
Received-From-MTA: dns; admin1.example.com
Arrival-Date: Mon, 25 Mar 2013 10:24:26 -0600

Final-Recipient: rfc822; fred.bloggs@example.net
Original-Recipient: rfc822; rfc822;fred.bloggs@example.net
Action: failed
Status: 5.9.8
Diagnostic-Code: X-XWall; 5.9.8 Spam


--_NextPart_1_00o1403flwFztPLyZJHFLDzNYRL
Content-Type: message/xdelivery-status ; name="delivery-status.txt"

Date: Mon, 25 Mar 2013 10:24:26 -0600
Reporting-MTA: dns; salsa.example.local
Received-From-MTA: dns; admin1.example.com
Arrival-Date: Mon, 25 Mar 2013 10:24:26 -0600

Final-Recipient: rfc822; fred.bloggs@example.net
Original-Recipient: rfc822; rfc822;fred.bloggs@example.net
Action: failed
Status: 5.9.8
Diagnostic-Code: X-XWall; 5.9.8 Spam

--_NextPart_1_00o1403flwFztPLyZJHFLDzNYRL
Content-Type: text/plain; name="message-header.txt"
Content-Disposition: attachment; filename="message-header.txt"
Content-Transfer-Encoding: base64

UmVjZWl2ZWQ6IGZyb20gYWRtaW4xLmRpYW5vbWkuY28udWsgKFs5NC4yMzYuNDUuMjEyXSkNCgli
eSBzYWxzYS5idWVub2Zvb2RzLmxvY2FsDQoJd2l0aCBYV2FsbCB2My40NyA7DQoJTW9uLCAyNSBN
YXIgMjAxMyAxMDoyNDoyNSAtMDYwMA0KUmVjZWl2ZWQ6IGZyb20gY2xvdWRhZG1pbjEuZGlhbm9t
aS5jby51ayAodW5rbm93biBbMTAuMTc3LjE5Ny44Ml0pDQoJYnkgMzAzNjU2LXdlYjIuZGlhbm9t
aS5jby51ayAoUG9zdGZpeCkgd2l0aCBFU01UUCBpZCAyRTcyMDFBRTgyRjUNCglmb3IgPHdiZW5A
YnVlbm9mb29kcy5jb20+OyBNb24sIDI1IE1hciAyMDEzIDE2OjIzOjQ2ICswMDAwIChHTVQpDQpB
dXRoZW50aWNhdGlvbi1SZXN1bHRzOiAzMDM2NTYtd2ViMi5kaWFub21pLmNvLnVrOyBka2ltPXBh
c3MgKDEwMjQtYml0IGtleSkNCgloZWFkZXIuaT1AZW1haWwuZGlhbm9taS5jb207IHgtZGtpbS1h
ZHNwPXBhc3MNClJlY2VpdmVkOiBieSBjbG91ZGFkbWluMS5kaWFub21pLmNvLnVrIChQb3N0Zml4
LCBmcm9tIHVzZXJpZCA1MDcpDQoJaWQgMTY5RjQxRTgwQTI7IE1vbiwgMjUgTWFyIDIwMTMgMTY6
MjM6NDYgKzAwMDAgKEdNVCkNCkRLSU0tU2lnbmF0dXJlOiB2PTE7IGE9cnNhLXNoYTI1NjsgYz1z
aW1wbGUvc2ltcGxlOyBkPWVtYWlsLmRpYW5vbWkuY29tOw0KCXM9ZGVmYXVsdDEwOyB0PTEzNjQy
Mjg2MjY7DQoJYmg9VTQ1L0UwL01qaWhmY0k4c3VyaEhkMTllSnVYRkg0WlNxclhDWWh5azQ4ND07
DQoJaD1NSU1FLVZlcnNpb246Q29udGVudC1UcmFuc2Zlci1FbmNvZGluZzpDb250ZW50LVR5cGU6
RGF0ZTpGcm9tOg0KCSBTdWJqZWN0Okxpc3QtVW5zdWJzY3JpYmU6VG86TWVzc2FnZS1JZDsNCgli
PXpFc0JJTFNxT0lGcDhpeWU1dkV0M24xRmIrZ2FUMjN5TWtFdFlxd3ZORzhCWEF4NjhKMy83WkZJ
dmxHTEJiL0FwDQoJIDl3Z3BETVdjcWdsZEMyVE1ENVpXYndZK05UQVRtL2owd3dqY2o4a0krc0M5
c0F4ZFVLaGNqdnlnQzVEL1d1dCsxMg0KCSBnMmo4eUM5VG9ZUTd2Z3BXQ1dCcGMvbnl5Q1Q4MFhp
QnpqL3RFanhJPQ0KTUlNRS1WZXJzaW9uOiAxLjANCkNvbnRlbnQtVHJhbnNmZXItRW5jb2Rpbmc6
IDdiaXQNCkNvbnRlbnQtVHlwZTogbXVsdGlwYXJ0L3JlbGF0ZWQ7IGJvdW5kYXJ5PSJfLS0tLS0t
LS0tLT1fMTM2NDIyODYyNTE0MzE3OTM4Ig0KWC1NYWlsZXI6IE1JTUU6OkxpdGUgMy4wMjcgKEYy
Ljc4OyBUMS4zMTsgQTIuMDg7IEIzLjEzOyBRMy4xMykNCkRhdGU6IE1vbiwgMjUgTWFyIDIwMTMg
MTY6MjM6NDUgKzAwMDANCkZyb206IEp1bGlhIFN0ZXZlbnMgPGp1bGlhLnN0ZXZlbnNAZW1haWwu
ZGlhbm9taS5jb20+DQpTdWJqZWN0OiBEZWFyIE1yIFdpbHNvbiwgMyBTa2lsbHMgWW91IE5lZWQg
dG8gQmVjb21lIGEgRm9yZXggVHJhZGVyIHwgRG93bmxvYWQgRlhDTSdzIEZyZWUgR3VpZGUNCkxp
c3QtVW5zdWJzY3JpYmU6IDxodHRwOi8vd3d3LmRpYW5vbWlvZmZlcnMuY28udWsvdW5zdWJzY3Jp
YmUuZXBsP3V1aWQ9NURFMjZCQ0MtOTU2OC0xMUUyLTg4ODctN0QwMDg2MUUwMTI3Pg0KVG86IEJl
bmphbWluIFdpbHNvbiA8d2JlbkBidWVub2Zvb2RzLmNvbT4NCk1lc3NhZ2UtSWQ6IDwyMDEzMDMy
NTE2MjM0Ni4xNjlGNDFFODBBMkBjbG91ZGFkbWluMS5kaWFub21pLmNvLnVrPg0K

--_NextPart_1_00o1403flwFztPLyZJHFLDzNYRL
Content-Type: message/rfc822

Received: from admin1.example.com ([94.236.45.212])
	by salsa.example.local
	with XWall v3.47 ;
	Mon, 25 Mar 2013 10:24:25 -0600
Received: from cloudadmin1.example.com (unknown [10.177.197.82])
	by 303656-web2.example.com (Postfix) with ESMTP id 2E7201AE82F5
	for <fred.bloggs@example.net>; Mon, 25 Mar 2013 16:23:46 +0000 (GMT)
Authentication-Results: 303656-web2.example.com; dkim=pass (1024-bit key)
	header.i=@email.example.com; x-dkim-adsp=pass
Received: by cloudadmin1.example.com (Postfix, from userid 507)
	id 169F41E80A2; Mon, 25 Mar 2013 16:23:46 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_136422862514317938"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Mon, 25 Mar 2013 16:23:45 +0000
From: John Smith <john.smith@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.example.com/unsubscribe.epl?uuid=5DE26BCC-9568-11E2-8887-7D00861E0127>
To: Fred Bloggs <fred.bloggs@example.net>
Message-Id: <20130325162346.169F41E80A2@cloudadmin1.example.com>

This is a multi-part message in MIME format.

--_----------=_136422862514317938
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_136422862514317938--

--_NextPart_1_00o1403flwFztPLyZJHFLDzNYRL--
