Delivered-To: automated-bounces+d4d36948-7eaa-11df-a95c-e489dd31f8f5@email.example.com
Received: by 10.216.157.72 with SMTP id n50cs186330wek;
        Wed, 23 Jun 2010 02:37:32 -0700 (PDT)
Received: by 10.216.160.130 with SMTP id u2mr2263718wek.73.1277285852167;
        Wed, 23 Jun 2010 02:37:32 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id x83si14572879wei.146.2010.06.23.02.37.32;
        Wed, 23 Jun 2010 02:37:32 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id EEB4A1658630; Wed, 23 Jun 2010 10:37:31 +0100 (BST)
Date: Wed, 23 Jun 2010 10:37:31 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+D4D36948-7EAA-11DF-A95C-E489DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="76638165862B.1277285851/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100623093731.EEB4A1658630@server4.example.co.uk>

This is a MIME-encapsulated message.

--76638165862B.1277285851/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<a@b.c>: host remote.ho.st[1.2.3.4] said: 554 Sorry,
    message looks like SPAM to me (in reply to end of DATA command)

--76638165862B.1277285851/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 76638165862B
X-Postfix-Sender: rfc822; automated-bounces+D4D36948-7EAA-11DF-A95C-E489DD31F8F5@email.example.com
Arrival-Date: Wed, 23 Jun 2010 10:36:42 +0100 (BST)

Final-Recipient: rfc822; a@b.c
Action: failed
Status: 5.0.0
Remote-MTA: dns; remote.ho.st
Diagnostic-Code: smtp; 554 Sorry, message looks like SPAM to me

--76638165862B.1277285851/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 76638165862B; Wed, 23 Jun 2010 10:36:42 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_127728580219740490"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 23 Jun 2010 10:36:42 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=D4D36948-7EAA-11DF-A95C-E489DD31F8F5>
To: John Smith <a@b.c>
Message-Id: <20100623093642.76638165862B@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_127728580219740490
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html

HTML here
--_----------=_127728580219740490--


--76638165862B.1277285851/server4.example.co.uk--
