Delivered-To: automated-bounces+cda1ff80-c98e-11de-b9fe-8d86dd31f8f5@example.com
Received: by 10.140.148.17 with SMTP id v17cs114127rvd;
        Wed, 4 Nov 2009 14:10:18 -0800 (PST)
Received: by 10.213.23.75 with SMTP id q11mr1423802ebb.74.1257372617050;
        Wed, 04 Nov 2009 14:10:17 -0800 (PST)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id 9si3454439ewy.7.2009.11.04.14.10.16;
        Wed, 04 Nov 2009 14:10:17 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 5148C16581C9; Wed,  4 Nov 2009 22:10:16 +0000 (GMT)
Date: Wed,  4 Nov 2009 22:10:16 +0000 (GMT)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+CDA1FF80-C98E-11DE-B9FE-8D86DD31F8F5@example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="0EDE91658210.1257372616/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20091104221016.5148C16581C9@server4.example.co.uk>

This is a MIME-encapsulated message.

--0EDE91658210.1257372616/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<exampleuser@exampledomain.co.uk>: host mail2.example.co.uk[1.2.3.4] said: 554
    5.7.1 Message cannot be accepted, spam rejection (in reply to end of DATA
    command)

--0EDE91658210.1257372616/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 0EDE91658210
X-Postfix-Sender: rfc822; automated-bounces+CDA1FF80-C98E-11DE-B9FE-8D86DD31F8F5@example.com
Arrival-Date: Wed,  4 Nov 2009 22:10:04 +0000 (GMT)

Final-Recipient: rfc822; exampleuser@exampledomain.co.uk
Action: failed
Status: 5.7.1
Remote-MTA: dns; mail2.example.co.uk
Diagnostic-Code: smtp; 554 5.7.1 Message cannot be accepted, spam rejection

--0EDE91658210.1257372616/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 0EDE91658210; Wed,  4 Nov 2009 22:10:04 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_1257372604188851"
X-Mailer: MIME::Lite 3.025 (F2.77; T1.27; A2.04; B3.08; Q3.08)
Date: Wed, 4 Nov 2009 22:10:04 +0000
From: Customer Services <customerservices@example.co.uk>
To: exampleuser@exampledomain.co.uk
Subject: BLAH
Message-Id: <20091104221004.0EDE91658210@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1257372604188851
Content-Disposition: inline
Content-Length: 32023
Content-Transfer-Encoding: binary
Content-Type: text/html

message body

--0EDE91658210.1257372616/server4.example.co.uk--
