Delivered-To: automated-bounces+1991163a-a934-11df-918b-0c67dd31f8f5@email.example.com
Received: by 10.220.199.3 with SMTP id eq3cs14123vcb;
        Mon, 16 Aug 2010 05:45:13 -0700 (PDT)
Received: by 10.227.146.149 with SMTP id h21mr4389027wbv.153.1281962713051;
        Mon, 16 Aug 2010 05:45:13 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id d11si8447273wbb.67.2010.08.16.05.45.12;
        Mon, 16 Aug 2010 05:45:12 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 6328B1658233; Mon, 16 Aug 2010 13:45:12 +0100 (BST)
Date: Mon, 16 Aug 2010 13:45:12 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+1991163A-A934-11DF-918B-0C67DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="CF14A16582FA.1281962712/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100816124512.6328B1658233@server4.example.co.uk>

This is a MIME-encapsulated message.

--CF14A16582FA.1281962712/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mx.ya.com[62.36.20.73] said: 550 Spam detected (in reply
    to end of DATA command)

--CF14A16582FA.1281962712/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: CF14A16582FA
X-Postfix-Sender: rfc822; automated-bounces+1991163A-A934-11DF-918B-0C67DD31F8F5@email.example.com
Arrival-Date: Mon, 16 Aug 2010 13:45:07 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx.ya.com
Diagnostic-Code: smtp; 550 Spam detected

--CF14A16582FA.1281962712/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id CF14A16582FA; Mon, 16 Aug 2010 13:45:07 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_12819627071082012"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 16 Aug 2010 13:45:07 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=1991163A-A934-11DF-918B-0C67DD31F8F5>
To: John Smith <recipient@example.net>
Message-Id: <20100816124508.CF14A16582FA@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_12819627071082012
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html







html

--_----------=_12819627071082012--


--CF14A16582FA.1281962712/server4.example.co.uk--
