Delivered-To: automated-bounces+34df9a6a-2531-11df-8a35-bde1fcd165a0@email.example.com
Received: by 10.216.173.129 with SMTP id v1cs468060wel;
        Mon, 1 Mar 2010 04:52:23 -0800 (PST)
Received: by 10.220.127.93 with SMTP id f29mr3159170vcs.61.1267447943120;
        Mon, 01 Mar 2010 04:52:23 -0800 (PST)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id 29si10430469vws.37.2010.03.01.04.52.22;
        Mon, 01 Mar 2010 04:52:22 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id C9AD916581FC; Mon,  1 Mar 2010 12:52:21 +0000 (GMT)
Date: Mon,  1 Mar 2010 12:52:21 +0000 (GMT)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+34DF9A6A-2531-11DF-8A35-BDE1FCD165A0@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="7FD0D16581BB.1267447941/server4.example.co.uk"
Message-Id: <20100301125221.C9AD916581FC@server4.example.co.uk>

This is a MIME-encapsulated message.

--7FD0D16581BB.1267447941/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<aaa@b.c>: host mx01.b.c[194.14.211.245] said: 550
    5.7.1 Message rejected as spam by Content Filtering. (in reply to end of
    DATA command)

--7FD0D16581BB.1267447941/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 7FD0D16581BB
X-Postfix-Sender: rfc822; automated-bounces+34DF9A6A-2531-11DF-8A35-BDE1FCD165A0@email.example.com
Arrival-Date: Mon,  1 Mar 2010 12:51:51 +0000 (GMT)

Final-Recipient: rfc822; aaa@b.c
Action: failed
Status: 5.7.1
Remote-MTA: dns; mx01.b.c
Diagnostic-Code: smtp; 550 5.7.1 Message rejected as spam by Content Filtering.

--7FD0D16581BB.1267447941/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by server4.example.co.uk (Postfix, from userid 505)
	id 7FD0D16581BB; Mon,  1 Mar 2010 12:51:51 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.example.com;
	s=default10; t=1267447911;
	bh=FW+DIO7nSsjqe7IUlXrYT1gxRp84EAVtHbm/rchvLic=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=OvAIWr1Twlnu3eGyK5HgQt+2aJo0Nkn1Lj7moNe7xwxeNgLy7VWh4Um1hqRHKMvIz
	 T1UHHewEAaxa1hyzzWzZzPqINy8GVwMUJA0S7XY+WtSn171qmYsvfXgYdMdnGJuX4q
	 n1kHayojDPCbhS1ThjKpcqUSwyICbjD896ROCxbQ=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_12674479112835980"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 1 Mar 2010 12:51:51 +0000
From: Customer Services <customer.services@email.example.com>
Subject: test
To: Test <aaa@b.c>
Message-Id: <20100301125151.7FD0D16581BB@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_12674479112835980
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here.

--_----------=_12674479112835980--


--7FD0D16581BB.1267447941/server4.example.co.uk--
