Delivered-To: automated-bounces+7f927056-da33-11e0-b766-b42e2e334e9c@email.sample.com
Received: by 10.231.35.202 with SMTP id q10cs23785ibd;
        Thu, 8 Sep 2011 08:59:18 -0700 (PDT)
Received: by 10.227.113.73 with SMTP id z9mr934843wbp.8.1315497557355;
        Thu, 08 Sep 2011 08:59:17 -0700 (PDT)
Return-Path: <>
Received: from admin1.sample.co.uk (admin1.sample.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id b5si3902025wbh.103.2011.09.08.08.59.15;
        Thu, 08 Sep 2011 08:59:16 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.sample.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.sample.co.uk (Postfix)
	id A641D65102B; Thu,  8 Sep 2011 16:59:15 +0100 (BST)
Date: Thu,  8 Sep 2011 16:59:15 +0100 (BST)
From: MAILER-DAEMON@admin1.sample.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+7F927056-DA33-11E0-B766-B42E2E334E9C@email.sample.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="F1C1A65102F.1315497555/admin1.sample.co.uk"
Message-Id: <20110908155915.A641D65102B@admin1.sample.co.uk>

This is a MIME-encapsulated message.

--F1C1A65102F.1315497555/admin1.sample.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.sample.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.org.uk>: host ncmail2.sample3.com[205.139.105.11]
    said: 554 5.7.1 Message cannot be accepted, content filter rejection
    bbSpamReject>7.5 (in reply to end of DATA command)

--F1C1A65102F.1315497555/admin1.sample.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.sample.co.uk
X-Postfix-Queue-ID: F1C1A65102F
X-Postfix-Sender: rfc822; automated-bounces+7F927056-DA33-11E0-B766-B42E2E334E9C@email.sample.com
Arrival-Date: Thu,  8 Sep 2011 16:59:13 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.org.uk
Action: failed
Status: 5.7.1
Remote-MTA: dns; ncmail2.sample3.com
Diagnostic-Code: smtp; 554 5.7.1 Message cannot be accepted, content filter
    rejection bbSpamReject>7.5

--F1C1A65102F.1315497555/admin1.sample.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.sample.co.uk (Postfix, from userid 505)
	id F1C1A65102F; Thu,  8 Sep 2011 16:59:13 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_131549755384674958"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Thu, 8 Sep 2011 16:59:13 +0100
From: Fred Bloggs <fred.bloggs@email.sample.com>
Subject: foo
X-Campaignid: sample20100819.2
List-Unsubscribe: <http://www.sampleoffers.co.uk/unsubscribe.epl?uuid=7F927056-DA33-11E0-B766-B42E2E334E9C>
To: Thomas Loeffler <john.smith@example.org.uk>
Message-Id: <20110908155913.F1C1A65102F@admin1.sample.co.uk>

This is a multi-part message in MIME format.

--_----------=_131549755384674958
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here.

--_----------=_131549755384674958--


--F1C1A65102F.1315497555/admin1.sample.co.uk--
