Delivered-To: automated-bounces+3276f092-8d59-11e1-baf5-e5fbb3a3ec94@email.example.com
Received: by 10.52.34.101 with SMTP id y5csp149205vdi;
        Mon, 23 Apr 2012 08:30:05 -0700 (PDT)
Received: by 10.180.104.231 with SMTP id gh7mr22339417wib.10.1335195004699;
        Mon, 23 Apr 2012 08:30:04 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id n58si5931805wee.9.2012.04.23.08.30.04;
        Mon, 23 Apr 2012 08:30:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 0E703651307; Mon, 23 Apr 2012 16:30:04 +0100 (BST)
Date: Mon, 23 Apr 2012 16:30:04 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+3276F092-8D59-11E1-BAF5-E5FBB3A3EC94@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="9DE17651306.1335195004/admin1.example.co.uk"
Message-Id: <20120423153004.0E703651307@admin1.example.co.uk>

This is a MIME-encapsulated message.

--9DE17651306.1335195004/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example2.com>: host fwd2.hosts.co.uk[85.233.160.24] said: 550 Spamming
    not allowed (in reply to end of DATA command)

--9DE17651306.1335195004/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 9DE17651306
X-Postfix-Sender: rfc822; automated-bounces+3276F092-8D59-11E1-BAF5-E5FBB3A3EC94@email.example.com
Arrival-Date: Mon, 23 Apr 2012 16:30:03 +0100 (BST)

Final-Recipient: rfc822; john.smith@example2.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; fwd2.hosts.co.uk
Diagnostic-Code: smtp; 550 Spamming not allowed

--9DE17651306.1335195004/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 505)
	id 9DE17651306; Mon, 23 Apr 2012 16:30:03 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_133519500324673471"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Mon, 23 Apr 2012 16:30:03 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=3276F092-8D59-11E1-BAF5-E5FBB3A3EC94>
To: john smith <john.smith@example2.com>
Message-Id: <20120423153003.9DE17651306@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_133519500324673471
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_133519500324673471--


--9DE17651306.1335195004/admin1.example.co.uk--
