Delivered-To: automated-bounces+ae343e80-a9e2-11df-9acf-c5a8dd31f8f5@email.example.com
Received: by 10.220.199.3 with SMTP id eq3cs62820vcb;
        Tue, 17 Aug 2010 02:35:03 -0700 (PDT)
Received: by 10.227.157.4 with SMTP id z4mr5426397wbw.43.1282037702277;
        Tue, 17 Aug 2010 02:35:02 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id a22si9656795wba.33.2010.08.17.02.35.01;
        Tue, 17 Aug 2010 02:35:02 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id AF53316581D9; Tue, 17 Aug 2010 10:35:01 +0100 (BST)
Date: Tue, 17 Aug 2010 10:35:01 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+AE343E80-A9E2-11DF-9ACF-C5A8DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="7BAC516581D6.1282037701/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100817093501.AF53316581D9@server4.example.co.uk>

This is a MIME-encapsulated message.

--7BAC516581D6.1282037701/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host pop3.example.net[213.216.132.115] said: 554
    Failure Message looks like spam, sorry not wanted here q=2381882
    friend_rule (in reply to end of DATA command)

--7BAC516581D6.1282037701/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 7BAC516581D6
X-Postfix-Sender: rfc822; automated-bounces+AE343E80-A9E2-11DF-9ACF-C5A8DD31F8F5@email.example.com
Arrival-Date: Tue, 17 Aug 2010 10:34:49 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; pop3.example.net
Diagnostic-Code: smtp; 554 Failure Message looks like spam, sorry not wanted
    here q=2381882 friend_rule

--7BAC516581D6.1282037701/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 7BAC516581D6; Tue, 17 Aug 2010 10:34:49 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/related; boundary="_----------=_128203768927645433"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Tue, 17 Aug 2010 10:34:49 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=AE343E80-A9E2-11DF-9ACF-C5A8DD31F8F5>
To: John Smith <recipient@example.net>
Message-Id: <20100817093449.7BAC516581D6@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_128203768927645433
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html

HTML

--_----------=_128203768927645433--


--7BAC516581D6.1282037701/server4.example.co.uk--
