Delivered-To: automated-bounces+8a670368-4580-11e0-9852-ad185eea71ff@email.example.com
Received: by 10.151.98.16 with SMTP id a16cs4677ybm;
        Thu, 3 Mar 2011 02:25:59 -0800 (PST)
Received: by 10.227.155.11 with SMTP id q11mr734007wbw.130.1299147958355;
        Thu, 03 Mar 2011 02:25:58 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id m1si1691210wbc.61.2011.03.03.02.25.56;
        Thu, 03 Mar 2011 02:25:57 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 7945F6507EF; Thu,  3 Mar 2011 10:25:56 +0000 (GMT)
Date: Thu,  3 Mar 2011 10:25:56 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+8A670368-4580-11E0-9852-AD185EEA71FF@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="3B9C565074D.1299147956/admin1.example.co.uk"
Message-Id: <20110303102556.7945F6507EF@admin1.example.co.uk>

This is a MIME-encapsulated message.

--3B9C565074D.1299147956/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.com>: host sli.example.com[212.98.181.17] said: 550
    Error: SPAM-ID: h20030701-214001 Your email had spam-like header contents.
    Please contact your email service provider. (in reply to end of DATA
    command)

--3B9C565074D.1299147956/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 3B9C565074D
X-Postfix-Sender: rfc822; automated-bounces+8A670368-4580-11E0-9852-AD185EEA71FF@email.example.com
Arrival-Date: Thu,  3 Mar 2011 10:25:20 +0000 (GMT)

Final-Recipient: rfc822; john.smith@example.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; sli.example.com
Diagnostic-Code: smtp; 550 Error: SPAM-ID: h20030701-214001 Your email had
    spam-like header contents. Please contact your email service provider.

--3B9C565074D.1299147956/admin1.example.co.uk
Content-Description: Undelivered Message Headers
Content-Type: text/rfc822-headers

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 3B9C565074D; Thu,  3 Mar 2011 10:25:20 +0000 (GMT)
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_129914792072750"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Thu, 3 Mar 2011 10:25:20 +0000
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=8A670368-4580-11E0-9852-AD185EEA71FF>
To: John Smith <john.smith@example.com>
Message-Id: <20110303102520.3B9C565074D@admin1.example.co.uk>

--3B9C565074D.1299147956/admin1.example.co.uk--
