Delivered-To: automated-bounces+ecc7643a-5edf-11e0-ae51-f10855b8ee0b@email.example.com
Received: by 10.236.108.11 with SMTP id p11cs68139yhg;
        Mon, 4 Apr 2011 10:21:12 -0700 (PDT)
Received: by 10.227.12.13 with SMTP id v13mr4823961wbv.134.1301937670972;
        Mon, 04 Apr 2011 10:21:10 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id t19si10461552wbg.26.2011.04.04.10.21.10;
        Mon, 04 Apr 2011 10:21:10 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 0E07B651086; Mon,  4 Apr 2011 18:21:10 +0100 (BST)
Date: Mon,  4 Apr 2011 18:21:10 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+ECC7643A-5EDF-11E0-AE51-F10855B8EE0B@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="1A73F651087.1301937670/admin1.example.co.uk"
Message-Id: <20110404172110.0E07B651086@admin1.example.co.uk>

This is a MIME-encapsulated message.

--1A73F651087.1301937670/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mail.example.net[196.28.227.118] said: 550
    Denied due to spam list (in reply to RCPT TO command)

--1A73F651087.1301937670/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 1A73F651087
X-Postfix-Sender: rfc822; automated-bounces+ECC7643A-5EDF-11E0-AE51-F10855B8EE0B@email.example.com
Arrival-Date: Mon,  4 Apr 2011 18:21:08 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail.example.net
Diagnostic-Code: smtp; 550 Denied due to spam list

--1A73F651087.1301937670/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 1A73F651087; Mon,  4 Apr 2011 18:21:08 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1301937668257070"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Mon, 4 Apr 2011 18:21:08 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=ECC7643A-5EDF-11E0-AE51-F10855B8EE0B>
To: John Smith <recipient@example.net>
Message-Id: <20110404172108.1A73F651087@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1301937668257070
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_1301937668257070--


--1A73F651087.1301937670/admin1.example.co.uk--
