Delivered-To: automated-bounces+5cab89e0-5717-11e1-a4a8-a4bc391b88f3@email.example.com
Received: by 10.52.112.97 with SMTP id ip1cs132681vdb;
        Tue, 14 Feb 2012 06:22:52 -0800 (PST)
Received: by 10.216.137.129 with SMTP id y1mr912594wei.59.1329229371937;
        Tue, 14 Feb 2012 06:22:51 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id f58si12536290wed.83.2012.02.14.06.22.51;
        Tue, 14 Feb 2012 06:22:51 -0800 (PST)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 5AFAF65126B; Tue, 14 Feb 2012 14:22:51 +0000 (GMT)
Date: Tue, 14 Feb 2012 14:22:51 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+5CAB89E0-5717-11E1-A4A8-A4BC391B88F3@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="63F08651262.1329229371/admin1.example.co.uk"
Message-Id: <20120214142251.5AFAF65126B@admin1.example.co.uk>

This is a MIME-encapsulated message.

--63F08651262.1329229371/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@bar.ac.uk>: host mailhub2.bar.ac.uk[143.117.14.19] said: 550 This
    message has been identified as spam (in reply to end of DATA command)

--63F08651262.1329229371/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 63F08651262
X-Postfix-Sender: rfc822; automated-bounces+5CAB89E0-5717-11E1-A4A8-A4BC391B88F3@email.example.com
Arrival-Date: Tue, 14 Feb 2012 14:22:45 +0000 (GMT)

Final-Recipient: rfc822; john.smith@bar.ac.uk
Action: failed
Status: 5.0.0
Remote-MTA: dns; mailhub2.bar.ac.uk
Diagnostic-Code: smtp; 550 This message has been identified as spam

--63F08651262.1329229371/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 63F08651262; Tue, 14 Feb 2012 14:22:45 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_132922936574210"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.08; B3.13; Q3.13)
Date: Tue, 14 Feb 2012 14:22:45 +0000
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=5CAB89E0-5717-11E1-A4A8-A4BC391B88F3>
To: John Smith <john.smith@bar.ac.uk>
Message-Id: <20120214142245.63F08651262@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_132922936574210
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_132922936574210--


--63F08651262.1329229371/admin1.example.co.uk--
