Return-Path: <spammer@example.net>
Received: from 61.187.98.10 ([201.229.132.227])
	by somehost.example.com (8.12.11.20060308/8.12.11) with ESMTP id k7GKq9CD025423
	for <recipient@somehost.example.com>; Wed, 16 Aug 2006 13:52:10 -0700
Message-Id: <200608162052.k7GKq9CD025423@somehost.example.com>
From: "Ilene Riggs" <spammer@example.net>
To: <recipient@somehost.example.com>
Subject: Hey baby, found this site and wanted you to check it out first
Date: Wed, 16 Aug 2006 20:52:12 +0360
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_006A_01C6C143.8EB0F850"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 6.00.2800.1106
X-MimeOLE: Produced By Microsoft MimeOLE V6.00.2800.1106

This is a multi-part message in MIME format.

------=_NextPart_000_006A_01C6C143.8EB0F850
Content-Type: text/plain;
	charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable


Hey bro! Nice talking to you the other day!

   Thought you would want to check this out, I got some for myself cause=20
they were on sale, you should check out the site, I added the link=20
below.

   

Steel P@&#241;k@ge:

 10 P@tches reg $79.95 Now $49.95 ! Fri: shipping t00!

   
S!lver P@ck@ge: 25 P@t(hes reg $129.95, N0w $99.95! Fri: shipping & fri:=20
exercise m@nual included!

   
G01d P@ckage:

 40 P@tches reg $189.95, Now $149.95! Fri: shipping & free exercise=20
m@nual  inc1uded!

   
Platinum P@ckage:

  65 P@tchesreg $259.95, Now $199.95! Fri: shipping & free exercise=20
m@nual  include (Best  V@lue!)

I kn0vv l!ke 10 guys wh0 have already st0(ked up on these. Here's the=20
link to (heck out br0 L|NK
Talk to you soon!
T0 $top g0 |-|ere!


------=_NextPart_000_006A_01C6C143.8EB0F850
Content-Type: text/html;
	charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv=Content-Type content="text/html; charset=Windows-1252">
<META content="MSHTML 6.00.2800.1106" name=GENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY><html>
<body bgcolor=3D"#FFFFFF">
<font size=3D"4" color=3D"cc0066">
<center>
<b>
<i>
Hey bro! Nice talking to you the other day!
</i>
</b>
</center>
</font>
<br>
&nbsp;  Thought you would want to check this out, I got some for myself=20
cause they were on sale, you should check out the site, I added the link=20
below.
<br>
<br>
   
<font size=3D"3" color=3D"66ccff">
<i>
<b>
Steel P@&#241;k@ge:
</font>
</i>
</b>
 10 P@tches reg $79.95 Now $49.95 ! Fri: shipping t00!
<br>
<br>
   <font size=3D"3" color=3D"Silver">
<i>
<b>
S!lver P@ck@ge:</font></i></b> 25 P@t(hes reg $129.95, N0w $99.95! Fri:=20
shipping & fri: exercise m@nual included!<br><br>

   <font size=3D"3" color=3D"ffcc00">
<i>
<b>
G01d P@ckage:
</font>
</i>
</b>
 40 P@tches reg $189.95, Now $149.95! Fri: shipping & free exercise=20
m@nual  inc1uded!
<br>
<br>
   
<font size=3D"3" color=3D"#8695ae">
<i><b>Platinum P@ckage:
</font>
</i>
</b>
  65 P@tchesreg $259.95, Now $199.95! Fri: shipping & free exercise=20
m@nual  include (Best  V@lue!)
<br>
<br>
<b>
<center>
<a href=3D"http://www.searsba.com/a/?90&jgfhDghDsdg7dfGHHG34GJHFG783s">
I kn0vv l!ke 10 guys wh0 have already st0(ked up on these. Here's the=20
link to (heck out br0 L|NK
</a>
<br>
<br>
<font size=3D"4" color=3D"cc0066">
<center>
<i>Talk to you soon!</i>
</font>
</center>
</b>
<br>
<br>
<br>
<br>
<font size=3D"2">
T0 $top g0 <a href=3D"http://www.searsba.com/u.php">|-|ere!
</a>
</font>
<br>
<br>
</center>
</body>
</html></BODY></HTML>

------=_NextPart_000_006A_01C6C143.8EB0F850--

