Delivered-To: automated-bounces+ca616b18-7a99-11e0-9137-b6e182a371be@email.example.com
Received: by 10.204.122.204 with SMTP id m12cs106554bkr;
        Mon, 9 May 2011 17:09:40 -0700 (PDT)
Received: by 10.227.7.146 with SMTP id d18mr4785673wbd.96.1304986180166;
        Mon, 09 May 2011 17:09:40 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id y20si17683363wbh.0.2011.05.09.17.09.38;
        Mon, 09 May 2011 17:09:39 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id A92D665106E; Tue, 10 May 2011 01:09:38 +0100 (BST)
Date: Tue, 10 May 2011 01:09:38 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+CA616B18-7A99-11E0-9137-B6E182A371BE@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="82FE9651062.1304986178/admin1.example.co.uk"
Message-Id: <20110510000938.A92D665106E@admin1.example.co.uk>

This is a MIME-encapsulated message.

--82FE9651062.1304986178/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mailb.example.net[195.248.90.32] said: 554 5.7.1 Mail
    (13049-38149) appears to be unsolicited - Score (59) over
    MessageScoringUpperLimit (50) - send error reports to postmaster@example.net
    (in reply to end of DATA command)

--82FE9651062.1304986178/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 82FE9651062
X-Postfix-Sender: rfc822; automated-bounces+CA616B18-7A99-11E0-9137-B6E182A371BE@email.example.com
Arrival-Date: Tue, 10 May 2011 01:09:36 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.7.1
Remote-MTA: dns; mailb.example.net
Diagnostic-Code: smtp; 554 5.7.1 Mail (13049-38149) appears to be unsolicited -
    Score (59) over MessageScoringUpperLimit (50) - send error reports to
    postmaster@example.net

--82FE9651062.1304986178/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 82FE9651062; Tue, 10 May 2011 01:09:36 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_13049861762689733"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Tue, 10 May 2011 01:09:36 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20101019.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=CA616B18-7A99-11E0-9137-B6E182A371BE>
To: John Smith <recipient@example.net>
Message-Id: <20110510000936.82FE9651062@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_13049861762689733
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_13049861762689733--


--82FE9651062.1304986178/admin1.example.co.uk--
