Delivered-To: automated-bounces+5f3c8d9e-b852-11e0-a0dd-d22393a91d63@email.example.com
Received: by 10.142.214.7 with SMTP id m7cs197072wfg;
        Wed, 27 Jul 2011 06:14:40 -0700 (PDT)
Received: by 10.216.229.86 with SMTP id g64mr2792952weq.50.1311772478844;
        Wed, 27 Jul 2011 06:14:38 -0700 (PDT)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id i48si208064wed.60.2011.07.27.06.14.37;
        Wed, 27 Jul 2011 06:14:37 -0700 (PDT)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id CFE8A651069; Wed, 27 Jul 2011 14:14:36 +0100 (BST)
Date: Wed, 27 Jul 2011 14:14:36 +0100 (BST)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+5F3C8D9E-B852-11E0-A0DD-D22393A91D63@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="9317465105F.1311772476/admin1.example.co.uk"
Message-Id: <20110727131436.CFE8A651069@admin1.example.co.uk>

This is a MIME-encapsulated message.

--9317465105F.1311772476/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<ws@sample.net>: host inbound.registeredsite.com[66.97.46.122] said:
    554 5.7.1 The message from
    (<automated-bounces+5F3C8D9E-B852-11E0-A0DD-D22393A91D63@email.example.com>)
    with the subject of (foo) matches a profile
    the Internet community may consider spam. Please revise your message before
    resending. (in reply to end of DATA command)

--9317465105F.1311772476/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: 9317465105F
X-Postfix-Sender: rfc822; automated-bounces+5F3C8D9E-B852-11E0-A0DD-D22393A91D63@email.example.com
Arrival-Date: Wed, 27 Jul 2011 14:14:34 +0100 (BST)

Final-Recipient: rfc822; ws@sample.net
Action: failed
Status: 5.7.1
Remote-MTA: dns; inbound.registeredsite.com
Diagnostic-Code: smtp; 554 5.7.1 The message from
    (<automated-bounces+5F3C8D9E-B852-11E0-A0DD-D22393A91D63@email.example.com>)
    with the subject of (foo) matches a profile
    the Internet community may consider spam. Please revise your message before
    resending.

--9317465105F.1311772476/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id 9317465105F; Wed, 27 Jul 2011 14:14:34 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_131177247421185112"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Wed, 27 Jul 2011 14:14:34 +0100
From: Julia Stevens <julia.stevens@email.example.com>
Subject: foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=5F3C8D9E-B852-11E0-A0DD-D22393A91D63>
To: Fred Bloggs <ws@sample.net>
Message-Id: <20110727131434.9317465105F@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_131177247421185112
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_131177247421185112--


--9317465105F.1311772476/admin1.example.co.uk--
