Return-Path: <>
X-Original-To: sender@example.com
Delivered-To: sender@example.com
Received: from otherhost.example.com (localhost.localdomain [127.0.0.1])
	by otherhost.example.com (Postfix) with ESMTP id 91B1C1193F8
	for <sender@example.com>; Wed, 16 Aug 2006 05:01:27 -0500 (CDT)
Received: from mailfilter.somehost.example.net (mailfilter.example.net [99.99.49.123])
	by otherhost.example.com (Postfix) with ESMTP id 602941193E8
	for <sender@example.com>; Wed, 16 Aug 2006 05:01:27 -0500 (CDT)
X-SEF-Processed: 5_0_0_816__2006_08_16_05_01_26
X-SEF-NDR-7853D99-ADF1-478E-8894-213D316B8FFA: 1
X-SEF-7853D99-ADF1-478E-8894-213D316B8FFA: 1
Received: 
From: <>
To: <sender@example.com>
Date: Wed, 16 Aug 2006 05:01:24 -0600
Subject:  Subject line
X-Mailer: SurfControl E-mail Filter
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="--=_NextPart_ST_05_01_24_Wednesday_August_16_2006_16202"
Message-Id: <20060816100127.602941193E8@otherhost.example.com>
X-Virus-Scanned: ClamAV using ClamSMTP


----=_NextPart_ST_05_01_24_Wednesday_August_16_2006_16202
Content-Type: text/plain;

Your message could not be sent.
A transcript of the attempts to send the message follows.
The number of attempts made: 1
Addressed To: recipient@example.net

Wed, 16 Aug 2006 05:01:24 -0500
Failed to send to identified host,
recipient@example.net: [99.99.49.50], 554 Service currently unavailable
--- Message non-deliverable.



----=_NextPart_ST_05_01_24_Wednesday_August_16_2006_16202
Content-Type: message/delivery-status;


Action: failed
Final-Recipient: rfc822;recipient@example.net
Diagnostic-Code: smtp; 554 Service currently unavailable
Status: 5.0.0




----=_NextPart_ST_05_01_24_Wednesday_August_16_2006_16202
Content-Type: message/rfc822;

X-SEF-Processed: 5_0_0_816__2006_08_16_05_01_23
X-SEF-7853D99-ADF1-478E-8894-213D316B8FFA: 1
Received: from Unknown [100.100.202.28] by mailfilter.somehost.example.net - SurfControl E-mail Filter ; Wed, 16 Aug 2006 05:01:22 -0500
Received: by bbx.example.com (Postfix, from userid 48)
	id CF938474458; Wed, 16 Aug 2006 05:01:17 -0500 (CDT)
Content-Transfer-Encoding: binary
Content-Type: multipart/alternative; boundary="_----------=_11557224771578060"
MIME-Version: 1.0
X-Mailer: MIME::Lite 3.01 (F2.73; A1.74; B3.01; Q3.01)
Date: Wed, 16 Aug 2006 10:01:17 UT
From: Sender <sender@example.com>
Reply-To: <sender@example.com>
To: recipient@example.net
Subject: Subject line
Message-Id: <20060816100117.CF938474458@bbx.example.com>

This is a multi-part message in MIME format.

--_----------=_11557224771578060
Content-Disposition: inline
Content-Transfer-Encoding: binary
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
X-Mailer: MIME::Lite 3.01 (F2.73; A1.74; B3.01; Q3.01)
Date: Wed, 16 Aug 2006 10:01:17 UT

Plain-text email message

--_----------=_11557224771578060
Content-Disposition: inline
Content-Transfer-Encoding: binary
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
X-Mailer: MIME::Lite 3.01 (F2.73; A1.74; B3.01; Q3.01)
Date: Wed, 16 Aug 2006 10:01:17 UT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
	<title></title>
	<style type="text/css" title="text/css">
<!--
-->
</style>
</head>
<body style="margin: 0; padding: 0em; font-family: sans-serif;">
HTML Email Message
</body>
</html>

--_----------=_11557224771578060--


----=_NextPart_ST_05_01_24_Wednesday_August_16_2006_16202--

