Delivered-To: automated-bounces+6db3c2be-4c9c-11e1-80d5-8f8518a70fd3@email.example.com
Received: by 10.52.116.40 with SMTP id jt8cs301101vdb;
        Tue, 31 Jan 2012 22:17:37 -0800 (PST)
Received: by 10.180.103.97 with SMTP id fv1mr39756064wib.17.1328077056472;
        Tue, 31 Jan 2012 22:17:36 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk. [94.236.45.212])
        by mx.google.com with ESMTP id n55si6082796weq.16.2012.01.31.22.17.36;
        Tue, 31 Jan 2012 22:17:36 -0800 (PST)
Received-SPF: pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id 1127D651218; Wed,  1 Feb 2012 06:17:36 +0000 (GMT)
Date: Wed,  1 Feb 2012 06:17:36 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+6DB3C2BE-4C9C-11E1-80D5-8F8518A70FD3@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="B1E00651215.1328077056/admin1.example.co.uk"
Message-Id: <20120201061736.1127D651218@admin1.example.co.uk>

This is a MIME-encapsulated message.

--B1E00651215.1328077056/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mailserv.sample.ac.uk[144.124.16.43] said: 550
    BAD_RECIPIENT - see
    http://www.mail.sample.ac.uk/undelivered.php?r=BAD_RECIPIENT&e=YXBwMDlAYWJlci5hYy51aw==
    (in reply to RCPT TO command)

--B1E00651215.1328077056/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: B1E00651215
X-Postfix-Sender: rfc822; automated-bounces+6DB3C2BE-4C9C-11E1-80D5-8F8518A70FD3@email.example.com
Arrival-Date: Wed,  1 Feb 2012 06:17:33 +0000 (GMT)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; mailserv.sample.ac.uk
Diagnostic-Code: smtp; 550 BAD_RECIPIENT - see
    http://www.mail.sample.ac.uk/undelivered.php?r=BAD_RECIPIENT&e=YXBwMDlAYWJlci5hYy51aw==

--B1E00651215.1328077056/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id B1E00651215; Wed,  1 Feb 2012 06:17:33 +0000 (GMT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=email.example.com;
	s=default10; t=1328077053;
	bh=JRg08kfVugR9Z2V004oe25JfyrnfIzpBXUj80fGomUw=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=mRzuW9hDQe9tS+nhw/M02fKrwp0u0YccBWfGDq6wbsvXrZ/Pc1Amgz2s0fVTP1qeF
	 m5NBw4oC/L3eDMTOhfw1eWupJrNCYncmnc4m5Ydl8Gq0R0xGIXPIYTCJ919wPi8l6R
	 mqG7k2z3xBSP0SLQo6gwGgQVpsZYvzlulBnS8Wc0=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1328077053279826"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Wed, 1 Feb 2012 06:17:33 +0000
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: Foo
X-Campaignid: example20100819.2
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=6DB3C2BE-4C9C-11E1-80D5-8F8518A70FD3>
To: John Smith <recipient@example.net>
Message-Id: <20120201061733.B1E00651215@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1328077053279826
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

FOO

--_----------=_1328077053279826--


--B1E00651215.1328077056/admin1.example.co.uk--
