Delivered-To: automated-bounces+a63e379a-e0f0-11df-a69d-ae0908fefdcc@email.example2.com
Received: by 10.227.156.7 with SMTP id u7cs312983wbw;
        Tue, 26 Oct 2010 04:03:25 -0700 (PDT)
Received: by 10.216.182.202 with SMTP id o52mr7457088wem.29.1288091005314;
        Tue, 26 Oct 2010 04:03:25 -0700 (PDT)
Return-Path: <>
Received: from server4.example2.co.uk (server4.example2.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id x13si12976457weq.185.2010.10.26.04.03.25;
        Tue, 26 Oct 2010 04:03:25 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example2.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example2.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example2.co.uk (Postfix)
	id 6CF6C16581CC; Tue, 26 Oct 2010 12:03:24 +0100 (BST)
Date: Tue, 26 Oct 2010 12:03:24 +0100 (BST)
From: MAILER-DAEMON@server4.example2.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+A63E379A-E0F0-11DF-A69D-AE0908FEFDCC@email.example2.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="19A1316581C7.1288091004/server4.example2.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20101026110324.6CF6C16581CC@server4.example2.co.uk>

This is a MIME-encapsulated message.

--19A1316581C7.1288091004/server4.example2.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example2.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host bill.example3.net[158.125.1.193] said: 550 Recipient does
    not exist on this system (in reply to RCPT TO command)

--19A1316581C7.1288091004/server4.example2.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example2.co.uk
X-Postfix-Queue-ID: 19A1316581C7
X-Postfix-Sender: rfc822; automated-bounces+A63E379A-E0F0-11DF-A69D-AE0908FEFDCC@email.example2.com
Arrival-Date: Tue, 26 Oct 2010 12:03:23 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.0.0
Remote-MTA: dns; bill.example3.net
Diagnostic-Code: smtp; 550 Recipient does not exist on this system

--19A1316581C7.1288091004/server4.example2.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example2.co.uk (Postfix, from userid 505)
	id 19A1316581C7; Tue, 26 Oct 2010 12:03:23 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_128809100330318354"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Tue, 26 Oct 2010 12:03:23 +0100
From: Fred Bloggs <fred.bloggs@email.example2.com>
Subject: foo
X-Campaignid: example220101008.1
List-Unsubscribe: <http://www.example2offers.co.uk/unsubscribe.epl?uuid=A63E379A-E0F0-11DF-A69D-AE0908FEFDCC>
To: John Smith <recipient@example.net>
Message-Id: <20101026110323.19A1316581C7@server4.example2.co.uk>

This is a multi-part message in MIME format.

--_----------=_128809100330318354
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text 
  
--_----------=_128809100330318354
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_128809100330318354--


--19A1316581C7.1288091004/server4.example2.co.uk--
