Delivered-To: automated-bounces+5b805f96-32a1-11e0-a4c9-eb3b278a9227@email.example.com
Received: by 10.100.190.1 with SMTP id n1cs37359anf;
        Mon, 7 Feb 2011 02:02:24 -0800 (PST)
Received: by 10.227.151.65 with SMTP id b1mr1642791wbw.163.1297072943515;
        Mon, 07 Feb 2011 02:02:23 -0800 (PST)
Return-Path: <>
Received: from admin1.example.co.uk (admin1.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id f25si6044788wbf.55.2011.02.07.02.02.23;
        Mon, 07 Feb 2011 02:02:23 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of admin1.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by admin1.example.co.uk (Postfix)
	id EF728650D72; Mon,  7 Feb 2011 10:02:22 +0000 (GMT)
Date: Mon,  7 Feb 2011 10:02:22 +0000 (GMT)
From: MAILER-DAEMON@admin1.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+5B805F96-32A1-11E0-A4C9-EB3B278A9227@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="C8039650D70.1297072942/admin1.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20110207100222.EF728650D72@admin1.example.co.uk>

This is a MIME-encapsulated message.

--C8039650D70.1297072942/admin1.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host admin1.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host aspmx.l.google.com[209.85.227.27] said: 550 5.2.1
    The email account that you tried to reach is disabled. t11si6005099wes.103
    (in reply to RCPT TO command)

--C8039650D70.1297072942/admin1.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; admin1.example.co.uk
X-Postfix-Queue-ID: C8039650D70
X-Postfix-Sender: rfc822; automated-bounces+5B805F96-32A1-11E0-A4C9-EB3B278A9227@email.example.com
Arrival-Date: Mon,  7 Feb 2011 10:02:22 +0000 (GMT)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.2.1
Remote-MTA: dns; aspmx.l.google.com
Diagnostic-Code: smtp; 550 5.2.1 The email account that you tried to reach is
    disabled. t11si6005099wes.103

--C8039650D70.1297072942/admin1.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by admin1.example.co.uk (Postfix, from userid 507)
	id C8039650D70; Mon,  7 Feb 2011 10:02:22 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_129707294257417"
X-Mailer: MIME::Lite 3.027 (F2.78; T1.31; A2.07; B3.13; Q3.13)
Date: Mon, 7 Feb 2011 10:02:22 +0000
From: Julia Stevens <julia.stevens@email.example.com>
Subject: test
X-Campaignid: example20101008.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=5B805F96-32A1-11E0-A4C9-EB3B278A9227>
To: Fred Bloggs <recipient@example.net>
Message-Id: <20110207100222.C8039650D70@admin1.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_129707294257417
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

Text

--_----------=_129707294257417
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_129707294257417--


--C8039650D70.1297072942/admin1.example.co.uk--
