Delivered-To: automated-bounces+bfab8114-900b-11df-8fb7-89d06df2b1bd@email.example.com
Received: by 10.224.28.133 with SMTP id m5cs238117qac;
        Thu, 15 Jul 2010 05:23:19 -0700 (PDT)
Received: by 10.227.128.5 with SMTP id i5mr17641668wbs.91.1279196599086;
        Thu, 15 Jul 2010 05:23:19 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id r55si150309weq.80.2010.07.15.05.23.18;
        Thu, 15 Jul 2010 05:23:19 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 82F63165835A; Thu, 15 Jul 2010 13:23:18 +0100 (BST)
Date: Thu, 15 Jul 2010 13:23:18 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+BFAB8114-900B-11DF-8FB7-89D06DF2B1BD@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="0A2ED1658350.1279196598/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20100715122318.82F63165835A@server4.example.co.uk>

This is a MIME-encapsulated message.

--0A2ED1658350.1279196598/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host mx.a.b.c[213.180.147.146] said:
    501 5.1.3 Odbiorca <recipient@example.net> nie istnieje / Recipient
    <recipient@example.net> does not exist (in reply to RCPT TO command)

--0A2ED1658350.1279196598/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 0A2ED1658350
X-Postfix-Sender: rfc822; automated-bounces+BFAB8114-900B-11DF-8FB7-89D06DF2B1BD@email.example.com
Arrival-Date: Thu, 15 Jul 2010 13:23:18 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.1.3
Remote-MTA: dns; mx.a.b.c
Diagnostic-Code: smtp; 501 5.1.3 Odbiorca <recipient@example.net> nie
    istnieje / Recipient <recipient@example.net> does not exist

--0A2ED1658350.1279196598/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 508)
	id 0A2ED1658350; Thu, 15 Jul 2010 13:23:18 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/alternative; boundary="_----------=_1279196598273011064"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Thu, 15 Jul 2010 13:23:18 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
X-Campaignid: example20100423.1
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=BFAB8114-900B-11DF-8FB7-89D06DF2B1BD>
To: John Smith <recipient@example.net>
Message-Id: <20100715122318.0A2ED1658350@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1279196598273011064
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

email_text

--_----------=_1279196598273011064
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

email html

--_----------=_1279196598273011064--


--0A2ED1658350.1279196598/server4.example.co.uk--
