Delivered-To: automated-bounces+7e135cce-41d5-11df-bf72-e235df39b594@email.dianomi.com
Received: by 10.213.7.77 with SMTP id c13cs238787ebc;
        Tue, 6 Apr 2010 16:39:04 -0700 (PDT)
Received: by 10.204.132.214 with SMTP id c22mr9018899bkt.60.1270597144132;
        Tue, 06 Apr 2010 16:39:04 -0700 (PDT)
Return-Path: <>
Received: from mhost02c.leeds.ac.uk (mhost02c.leeds.ac.uk [129.11.76.154])
        by mx.google.com with ESMTP id 20si29571660bwz.4.2010.04.06.16.39.03;
        Tue, 06 Apr 2010 16:39:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of mhost02c.leeds.ac.uk designates 129.11.76.154 as permitted sender) client-ip=129.11.76.154;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of mhost02c.leeds.ac.uk designates 129.11.76.154 as permitted sender) smtp.mail=
Received: from imap02c.leeds.ac.uk (imap02c.leeds.ac.uk [129.11.76.141])
	by mhost02c.leeds.ac.uk (8.14.3/8.14.3) with ESMTP id o36Nd3nQ017009
	for <automated-bounces+7E135CCE-41D5-11DF-BF72-E235DF39B594@email.dianomi.com>; Wed, 7 Apr 2010 00:39:03 +0100 (BST)
Received: from localhost (localhost)
	by imap02c.leeds.ac.uk (8.14.1/8.14.1) id o36Nd3rM000408;
	Wed, 7 Apr 2010 00:39:03 +0100 (BST)
Date: Wed, 7 Apr 2010 00:39:03 +0100 (BST)
From: Mail Delivery Subsystem <MAILER-DAEMON@imap02c.leeds.ac.uk>
Message-Id: <201004062339.o36Nd3rM000408@imap02c.leeds.ac.uk>
To: <automated-bounces+7E135CCE-41D5-11DF-BF72-E235DF39B594@email.dianomi.com>
Subject: Returned mail: see transcript for details
Auto-Submitted: auto-generated (failure)

The original message was received at Wed, 7 Apr 2010 00:39:02 +0100 (BST)
from mhost04c.leeds.ac.uk [129.11.76.187]

   ----- The following addresses had permanent fatal errors -----
<cn06ajt@mailgrp1.leeds.ac.uk>
    (reason: 552 5.2.2 Over quota)

   ----- Transcript of session follows -----
... while talking to localhost:
>>> DATA
<<< 552 5.2.2 Over quota
554 5.0.0 Service unavailable
<<< 503 5.5.1 No recipients

   ----- Message header follows -----

Return-Path: <automated-bounces+7E135CCE-41D5-11DF-BF72-E235DF39B594@email.dianomi.com>
Received: from mhost04c.leeds.ac.uk (mhost04c.leeds.ac.uk [129.11.76.187])
	by imap02c.leeds.ac.uk (8.14.1/8.14.1) with ESMTP id o36NcvrM000399
	for <cn06ajt@mailgrp1.leeds.ac.uk>; Wed, 7 Apr 2010 00:39:02 +0100 (BST)
Received: from server2.dianomi.co.uk (server2.dianomi.co.uk [94.236.45.210])
	by mhost04c.leeds.ac.uk (8.14.3/8.14.3) with ESMTP id o36NcPV5015957
	for <cn06ajt@leeds.ac.uk>; Wed, 7 Apr 2010 00:38:30 +0100 (BST)
Received: by server2.dianomi.co.uk (Postfix, from userid 507)
	id 78950B58223; Wed,  7 Apr 2010 00:38:24 +0100 (BST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=email.dianomi.com;
	s=default10; t=1270597104;
	bh=pgNLXZpJ59ib0JYUrmLPUVi3BU4Osyhjwie+9zIAhwU=;
	h=MIME-Version:Content-Transfer-Encoding:Content-Type:Date:From:
	 Subject:List-Unsubscribe:To:Message-Id;
	b=SHx1uaJZL2HirttZbRcYSdIBZ7tXKPby5sElypxKlUw1+srFI0NE8Lck+l7aBH7Gi
	 zFMiZzjT5DRloeZ6XUChH4hfTCTGgUlZIJdNrFWIcucsvUGYTKYzELnnfx2BuDCcFY
	 vovluNjlDSV6cTVvH6emV3YNsm8wxf5cpKZuLZcw=
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1270597104224051"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 7 Apr 2010 00:38:24 +0100
From: Customer Services <customerservices@email.dianomi.com>
Subject: Accendo Markets PDF
List-Unsubscribe: <http://www.dianomioffers.co.uk/unsubscribe.epl?uuid=7E135CCE-41D5-11DF-BF72-E235DF39B594>
To: Alex Thomas <cn06ajt@leeds.ac.uk>
Message-Id: <20100406233824.78950B58223@server2.dianomi.co.uk>
X-PMX-Version: 5.5.8.383112, Antispam-Engine: 2.7.2.376379, Antispam-Data: 2010.4.6.231832
X-PerlMx-Spam: Gauge=X, Probability=10%, Report='
 IMGSPAM_BODY 0.5, HTML_70_90 0.1, FRAUD_ATTACH 0.05, BODY_SIZE_10000_PLUS 0, LINK_TO_IMAGE 0, PDF_ATTACHED 0, PDF_ATTACHED_2 0, PDF_ENCRYPT_HASH 0, __CANPHARM_UNSUB_HREF 0, __CANPHARM_UNSUB_LINK 0, __CT 0, __CTE 0, __CTYPE_HAS_BOUNDARY 0, __CTYPE_MULTIPART 0, __EXTRA_MPART_TYPE_N1 0, __HAS_HTML 0, __HAS_LIST_HEADER 0, __HAS_LIST_UNSUBSCRIBE 0, __HAS_MSGID 0, __HAS_X_MAILER 0, __IMGSPAM_BODY 0, __MIME_HTML 0, __MIME_VERSION 0, __SANE_MSGID 0, __TAG_EXISTS_HTML 0, __TO_MALFORMED_2 0, __URI_NO_MAILTO 0, __URI_NS , __XMAILER_MIME_LITE 0'

   ----- Message body suppressed -----

