Delivered-To: automated-bounces@example.com
Received: by 10.204.118.69 with SMTP id u5cs147646bkq;
        Mon, 6 Jul 2009 16:12:13 -0700 (PDT)
Received: by 10.210.39.8 with SMTP id m8mr2403446ebm.84.1246921932861;
        Mon, 06 Jul 2009 16:12:12 -0700 (PDT)
Return-Path: <>
Received: from mail157.examplelabs.com (mail157.examplelabs.com [85.158.136.211])
        by mx.google.com with SMTP id 7si1117028eyg.27.2009.07.06.16.12.12;
        Mon, 06 Jul 2009 16:12:12 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of mail157.examplelabs.com designates 85.158.136.211 as permitted sender) client-ip=85.158.136.211;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of mail157.examplelabs.com designates 85.158.136.211 as permitted sender) smtp.mail=
X-VirusChecked: Checked
X-Msg-Ref: server-7.tower-157.examplelabs.com!1246921931!6134095!1
X-StarScan-Version: 6.0.0; banners=example.co.uk,-,-
X-Originating-IP: [193.200.176.133]
Received: (qmail 7744 invoked from network); 6 Jul 2009 23:12:11 -0000
From: postmaster@example.co.uk
To: automated-bounces@example.com
Date: Tue, 7 Jul 2009 00:12:11 +0100
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="9B095B5ADSN=_01C945D7F4A10BD000067B77awnexfe01.INV.AD"
X-DSNContext: 335a7efd - 4523 - 00000001 - 80040546
Message-ID: <HWToA3M9X0004b712@awnexfe01.INV.ADRoot.example>
Subject: Delivery Status Notification (Failure)

This is a MIME-formatted message.  
Portions of this message may be unreadable without a MIME-capable mail program.

--9B095B5ADSN=_01C945D7F4A10BD000067B77awnexfe01.INV.AD
Content-Type: text/plain; charset=unicode-1-1-utf-7

This is an automatically generated Delivery Status Notification.

Delivery to the following recipients failed.

       example@example.com





________________________________________________________________________
**** This email has come from the internet and has been scanned for all viruses and potentially offensive content by Messagelabs on behalf of Legal & General ****
--9B095B5ADSN=_01C945D7F4A10BD000067B77awnexfe01.INV.AD
Content-Type: message/delivery-status

Reporting-MTA: dns;example.INV.ADRoot.LGIM.COM
Received-From-MTA: dns;example.example.dmz
Arrival-Date: Tue, 7 Jul 2009 00:12:11 +0100

Original-Recipient: rfc822;example@example.com
Final-Recipient: rfc822;example@example.com
Action: failed
Status: 5.1.1

--9B095B5ADSN=_01C945D7F4A10BD000067B77awnexfe01.INV.AD
Content-Type: message/rfc822

Received: from example.example.dmz ([10.200.3.44]) by example.INV.ADRoot.example.COM with Microsoft SMTPSVC(6.0.3790.1830);
	 Tue, 7 Jul 2009 00:12:11 +0100
Received: from mail92.examplelabs.com (unverified) by example.example.dmz
 (Content Technologies SMTPRS 4.3.20) with SMTP id <T8f5ef6f4200ac8032c9cc@d01s-cn003.example.dmz>;
 Tue, 7 Jul 2009 00:12:45 +0100
X-VirusChecked: Checked
X-Env-Sender: automated-bounces@example.com
X-Msg-Ref: server-13.tower-92.examplelabs.com!1246921930!35669125!1
X-StarScan-Version: 6.0.0; banners=-,-,example.co.uk
X-Originating-IP: [212.100.234.46]
X-SpamReason: No, hits=0.0 required=7.0 tests=sa_preprocessor: 
  VHJ1c3RlZCBJUDogMjEyLjEwMC4yMzQuNDYgPT4gMTc2OTA=\n
Received: (qmail 18468 invoked from network); 6 Jul 2009 23:12:10 -0000
Received: from server4.example.co.uk (HELO server4.example.co.uk) (212.100.234.46)
  by server-13.tower-92.examplelabs.com with SMTP; 6 Jul 2009 23:12:10 -0000
Received: by server4.example.co.uk (Postfix, from userid 507)
	id 570C471C4D7; Tue,  7 Jul 2009 00:12:10 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/mixed; boundary="_----------=_12469219301719857"
X-Mailer: MIME::Lite 3.021 (F2.73; T1.22; A2.04; B3.08; Q3.08)
Date: Tue, 7 Jul 2009 00:12:10 +0100
From: sales@example.co.uk
To: example@example.com
Subject: BLEH
Message-Id: <20090706231210.570C471C4D7@server4.example.co.uk>
Return-Path: automated-bounces@example.com
X-OriginalArrivalTime: 06 Jul 2009 23:12:11.0555 (UTC) FILETIME=[312C8730:01C9FE8F]

This is a multi-part message in MIME format.

--_----------=_12469219301719857
Content-Disposition: inline
Content-Length: 35
Content-Transfer-Encoding: binary
Content-Type: text/plain

example content

________________________________________________________________________
*** This email has come from the internet and has been scanned for all viruses and potentially offensive content by Messagelabs on behalf of XXX. Please report unwanted spam email to x@example.com ***

Please consider the environment before printing this email.
--_----------=_12469219301719857--



--9B095B5ADSN=_01C945D7F4A10BD000067B77awnexfe01.INV.AD--
