Delivered-To: automated-bounces@example.com
Received: by 10.204.119.15 with SMTP id x15cs429315bkq;
        Thu, 15 Oct 2009 07:46:18 -0700 (PDT)
Received: by 10.211.146.18 with SMTP id y18mr9153987ebn.55.1255617977875;
        Thu, 15 Oct 2009 07:46:17 -0700 (PDT)
Return-Path: <>
Received: from MGWSL0203.b.c (mailo3.b.c [194.75.128.200])
        by mx.google.com with ESMTP id 23si626412ewy.24.2009.10.15.07.46.17;
        Thu, 15 Oct 2009 07:46:17 -0700 (PDT)
Received-SPF: pass (google.com: domain of MGWSL0203.b.c designates 194.75.128.200 as permitted sender) client-ip=194.75.128.200;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of MGWSL0203.b.c designates 194.75.128.200 as permitted sender) smtp.mail=
Message-Id: <4ad735b9.1767f10a.4970.ffffec15SMTPIN_ADDED@mx.google.com>
Received: from [10.160.80.180] by MGWSL0203.b.c with ESMTP (
 welcome. (Email Firewall v6.3.1)); Thu, 15 Oct 2009 15:46:06 +0100
X-Server-Uuid: 3ED97F32-7B0C-4EAB-8F2A-BF4FA3F24512
Received: from EXCHL0117.rtdom.com ([10.160.219.251]) by
 EXCHL0204.rtdom.com with Microsoft SMTPSVC(6.0.3790.3959); Thu, 15 Oct
 2009 15:46:04 +0100
From: postmaster@no.b.c
To: automated-bounces@example.com
Date: Thu, 15 Oct 2009 15:46:03 +0100
MIME-Version: 1.0
X-DSNContext: 7ce717b1 - 1158 - 00000002 - 00000000
Subject: Delivery Status Notification (Failure)
Return-Path: <>
X-OriginalArrivalTime: 15 Oct 2009 14:46:04.0383 (UTC)
 FILETIME=[38A68EF0:01CA4DA6]
X-WSS-ID: 66C9EA265C4480046-02-03
Content-Type: multipart/report;
 report-type=delivery-status;
 boundary="9B095B5ADSN=_01CA4D1DFD1EE57200009DD6EXCHL0117.rtdom."

This is a MIME-formatted message.  
Portions of this message may be unreadable without a MIME-capable mail program.

--9B095B5ADSN=_01CA4D1DFD1EE57200009DD6EXCHL0117.rtdom.
Content-Type: text/plain;
 charset=unicode-1-1-utf-7
Content-Transfer-Encoding: 7bit

This is an automatically generated Delivery Status Notification.

Delivery to the following recipients failed.

       a@b.c




 
-----------------------------------------------------------------------------------------------------
sigline

+AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9

--9B095B5ADSN=_01CA4D1DFD1EE57200009DD6EXCHL0117.rtdom.
Content-Type: message/delivery-status
Content-Transfer-Encoding: 7bit

Reporting-MTA: dns;EXCHL0117.rtdom.com
Received-From-MTA: dns;EXCHL0202.rtdom.com
Arrival-Date: Thu, 15 Oct 2009 15:46:03 +0100

Final-Recipient: rfc822;a@b.c
Action: failed
Status: 5.2.2
X-Display-Name: AAA


--9B095B5ADSN=_01CA4D1DFD1EE57200009DD6EXCHL0117.rtdom.
Content-Type: message/rfc822
Content-Transfer-Encoding: 7bit

Received: from EXCHL0202.rtdom.com ([10.160.83.117]) by
 EXCHL0117.rtdom.com with Microsoft SMTPSVC(6.0.3790.3959); Thu, 15 Oct
 2009 15:46:03 +0100
Received: from mgwsl0106.hbosplc.com ([10.216.38.6]) by
 EXCHL0202.rtdom.com with Microsoft SMTPSVC(6.0.3790.3959); Thu, 15 Oct
 2009 15:46:02 +0100
Received: from [207.126.144.185] by mgwsl0106.hbosplc.com with SMTP (
 welcome. (Email Firewall v6.3.1)); Thu, 15 Oct 2009 15:45:55 +0100
X-Server-Uuid: 4FEDCE28-AAA9-40A9-87BD-008BF9B812F7
Received: from source ([94.236.45.212]) by eu1sys200amx116.postini.com (
 [207.126.147.10]) with SMTP; Thu, 15 Oct 2009 14:45:56 UTC
Received: by server4.example.co.uk (Postfix, from userid 507) id
 B3D221659028; Thu, 15 Oct 2009 15:45:55 +0100 (BST)
MIME-Version: 1.0
Date: Thu, 15 Oct 2009 15:45:55 +0100
From: "Customer Services" <customerservices@example.co.uk>
To: a@b.c
Subject: AAA
List-Unsubscribe: <mailto:unsubscribe+218932+rh@example.com>,
 <http://www.dianomioffers.co.uk/unsubscribe.epl?uid=218932&email_type_id=1&code=rh&hex=58d6a9a32c63d5862bc2d2c07a669de3>
X-pstn-neptune: 0/0/0.00/0
X-pstn-levels: (S: 2.37279/99.90000 CV:99.9000 FC:95.5390 LC:95.5390
 R:95.9108 P:95.9108 M:97.0282 C:98.6951 )
X-pstn-settings: 2 (0.5000:0.5000) s cv fc lc gt3 gt2 gt1 ft lt r p m c
X-pstn-addresses: from <customerservices@example.co.uk> [db-null]
X-WSS-ID: 66C9EA283B03478272-01-01
Return-path: automated-bounces@example.com
X-OriginalArrivalTime: 15 Oct 2009 14:46:02.0533 (UTC)
 FILETIME=[378C4550:01CA4DA6]
Content-Transfer-Encoding: binary
Content-Type: multipart/related;
 boundary="_----------=_12556179558984794"

This is a multi-part message in MIME format.

--_----------=_12556179558984794
Content-Length: 13220
Content-Disposition: inline
Content-Transfer-Encoding: binary
Content-Type: text/html

HTML here

--_----------=_12556179558984794--

--9B095B5ADSN=_01CA4D1DFD1EE57200009DD6EXCHL0117.rtdom.--

