Delivered-To: automated-bounces@example.com
Received: by 10.204.118.69 with SMTP id u5cs196500bkq;
        Tue, 7 Jul 2009 16:34:56 -0700 (PDT)
Received: by 10.210.81.9 with SMTP id e9mr7838504ebb.42.1247009696163;
        Tue, 07 Jul 2009 16:34:56 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [212.100.234.46])
        by mx.google.com with ESMTP id 20si15991408ewy.65.2009.07.07.16.34.55;
        Tue, 07 Jul 2009 16:34:56 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) client-ip=212.100.234.46;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 212.100.234.46 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id BDA4871C4D9; Wed,  8 Jul 2009 00:34:55 +0100 (BST)
Date: Wed,  8 Jul 2009 00:34:55 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces@example.com
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="6434D71C4D7.1247009695/server4.example.co.uk"
Content-Transfer-Encoding: 8bit
Message-Id: <20090707233455.BDA4871C4D9@server4.example.co.uk>

This is a MIME-encapsulated message.

--6434D71C4D7.1247009695/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain

This is the Postfix program at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

			The Postfix program

<1@server4.example.co.uk> (expanded from <1>): unknown user: "1"

--6434D71C4D7.1247009695/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 6434D71C4D7
X-Postfix-Sender: rfc822; automated-bounces@example.com
Arrival-Date: Wed,  8 Jul 2009 00:34:54 +0100 (BST)

Final-Recipient: rfc822; 1@server4.example.co.uk
Original-Recipient: rfc822; 1
Action: failed
Status: 5.0.0
Diagnostic-Code: X-Postfix; unknown user: "1"

--6434D71C4D7.1247009695/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 6434D71C4D7; Wed,  8 Jul 2009 00:34:54 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/mixed; boundary="_----------=_124700969427088193"
X-Mailer: MIME::Lite 3.021 (F2.73; T1.22; A2.04; B3.08; Q3.08)
Date: Wed, 8 Jul 2009 00:34:54 +0100
From: sales@example.co.uk
To: 1@server4.example.co.uk
Subject: bleh
Message-Id: <20090707233454.6434D71C4D7@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_124700969427088193
Content-Disposition: attachment; filename="foo.CSV"
Content-Length: 638
Content-Transfer-Encoding: binary
Content-Type: text/plain; name="foo.CSV"

foo

--_----------=_124700969427088193
Content-Disposition: inline
Content-Length: 537
Content-Transfer-Encoding: binary
Content-Type: text/plain

Content.

------------------------------------------------------

--_----------=_124700969427088193--


--6434D71C4D7.1247009695/server4.example.co.uk--
