Delivered-To: automated-bounces+7da13c5c-f473-11de-b27e-96e7ff1b195c@email.dianomi.com
Received: by 10.216.171.205 with SMTP id r55cs187918wel;
        Tue, 29 Dec 2009 04:12:55 -0800 (PST)
Received: by 10.213.15.18 with SMTP id i18mr1107859eba.59.1262088775694;
        Tue, 29 Dec 2009 04:12:55 -0800 (PST)
Return-Path: <>
Received: from em1.cfs.co.uk ([194.75.171.100])
        by mx.google.com with ESMTP id 23si1448001ewy.64.2009.12.29.04.12.55;
        Tue, 29 Dec 2009 04:12:55 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of em1.cfs.co.uk designates 194.75.171.100 as permitted sender) client-ip=194.75.171.100;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of em1.cfs.co.uk designates 194.75.171.100 as permitted sender) smtp.mail=
X-Disclaimer: None
X-IronPort-AV: E=Sophos;i="4.47,468,1257120000"; 
   d="scan'208";a="81173580"
Received: from exim by newolympicmail with local (Exim 4.69)
	id 1NPawY-00030K-TS
	for automated-bounces+7DA13C5C-F473-11DE-B27E-96E7FF1B195C@email.dianomi.com; Tue, 29 Dec 2009 12:12:54 +0000
From: <>
To: automated-bounces+7DA13C5C-F473-11DE-B27E-96E7FF1B195C@email.dianomi.com
In-Reply-To: <20091229121253.615A116581D3@server4.dianomi.co.uk>
References: <20091229121253.615A116581D3@server4.dianomi.co.uk>
Auto-Submitted: auto-replied
Message-Id: <E1NPawY-00030K-TS@newolympicmail>
Date: Tue, 29 Dec 2009 12:12:54 +0000

You sent mail to sarah.darlington@cfs.coop. That's not a valid user here.
