Delivered-To: automated-bounces@email.example.com
Received: by 10.140.148.17 with SMTP id v17cs72121rvd;
        Tue, 17 Nov 2009 16:08:08 -0800 (PST)
Received: by 10.223.5.77 with SMTP id 13mr2452233fau.86.1258502887319;
        Tue, 17 Nov 2009 16:08:07 -0800 (PST)
Return-Path: <>
Received: from mail155.examplelabs.com (mail155.examplelabs.com [85.158.138.35])
        by mx.google.com with SMTP id 4si9822905bwz.2.2009.11.17.16.08.06;
        Tue, 17 Nov 2009 16:08:07 -0800 (PST)
Received-SPF: pass (google.com: best guess record for domain of mail155.examplelabs.com designates 85.158.138.35 as permitted sender) client-ip=85.158.138.35;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of mail155.examplelabs.com designates 85.158.138.35 as permitted sender) smtp.mail=
X-VirusChecked: Checked
X-Msg-Ref: server-14.tower-155.examplelabs.com!1258502885!21833181!1
X-StarScan-Version: 6.2.4; banners=example.co.uk,-,-
X-Originating-IP: [193.200.176.133]
Received: (qmail 17047 invoked from network); 18 Nov 2009 00:08:05 -0000
Received: from unknown (HELO d01s-cn004.example.dmz) (193.200.176.133)
  by server-14.tower-155.examplelabs.com with SMTP; 18 Nov 2009 00:08:05 -0000
Received: from awnexfe01.INV.ADRoot.example.com (unverified) by d01s-cn004.example.dmz
 (Content Technologies SMTPRS 4.3.20) with ESMTP id <T92110b11c00ac8032d5ac@d01s-cn004.example.dmz> for <automated-bounces@email.example.com>;
 Wed, 18 Nov 2009 00:12:43 +0000
From: postmaster@example.co.uk
To: automated-bounces@email.example.com
Date: Wed, 18 Nov 2009 00:08:05 +0000
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="9B095B5ADSN=_01CA33119A4F8526000227FDawnexfe01.INV.AD"
X-DSNContext: 335a7efd - 4523 - 00000001 - 80040546
Message-ID: <tsWhPmynn0001a8a3@awnexfe01.INV.ADRoot.example.com>
Subject: Delivery Status Notification (Failure)

This is a MIME-formatted message.  
Portions of this message may be unreadable without a MIME-capable mail program.

--9B095B5ADSN=_01CA33119A4F8526000227FDawnexfe01.INV.AD
Content-Type: text/plain; charset=unicode-1-1-utf-7

This is an automatically generated Delivery Status Notification.

Delivery to the following recipients failed.

			a@example.com
			b@example.com




________________________________________________________________________
**** This email has come from the internet and has been scanned for all viruses and potentially offensive content by examplelabs on behalf of XXX ****
--9B095B5ADSN=_01CA33119A4F8526000227FDawnexfe01.INV.AD
Content-Type: message/delivery-status

Reporting-MTA: dns;awnexfe01.INV.ADRoot.example.com
Received-From-MTA: dns;d01s-cn003.example.dmz
Arrival-Date: Wed, 18 Nov 2009 00:08:05 +0000

Original-Recipient: rfc822;a@example.co.uk
Final-Recipient: rfc822;b@example.co.uk
Action: failed
Status: 5.1.1

Original-Recipient: rfc822;c@example.co.uk
Final-Recipient: rfc822;c@example.co.uk
Action: failed
Status: 5.1.1

--9B095B5ADSN=_01CA33119A4F8526000227FDawnexfe01.INV.AD
Content-Type: message/rfc822

Received: from d01s-cn003.example.dmz ([10.200.3.44]) by awnexfe01.INV.ADRoot.example.com with Microsoft SMTPSVC(6.0.3790.3959);
	 Wed, 18 Nov 2009 00:08:05 +0000
Received: from mail155.examplelabs.com (unverified) by d01s-cn003.example.dmz
 (Content Technologies SMTPRS 4.3.20) with SMTP id <T921107f3c60ac8032cc94@d01s-cn003.example.dmz>;
 Wed, 18 Nov 2009 00:09:19 +0000
X-VirusChecked: Checked
X-Env-Sender: automated-bounces@email.example.com
X-Msg-Ref: server-5.tower-155.examplelabs.com!1258502883!20042795!1
X-StarScan-Version: 6.2.4; banners=-,-,example.co.uk
X-Originating-IP: [94.236.45.212]
X-SpamReason: No, hits=0.0 required=7.0 tests=sa_preprocessor: 
  VHJ1c3RlZCBJUDogOTQuMjM2LjQ1LjIxMiA9PiA5ODcy\n
Received: (qmail 26403 invoked from network); 18 Nov 2009 00:08:03 -0000
Received: from server4.example.co.uk (HELO server4.example.co.uk) (94.236.45.212)
  by server-5.tower-155.examplelabs.com with SMTP; 18 Nov 2009 00:08:03 -0000
Received: by server4.example.co.uk (Postfix, from userid 507)
	id F2D2516581E5; Wed, 18 Nov 2009 00:08:02 +0000 (GMT)
MIME-Version: 1.0
Content-Transfer-Encoding: binary
Content-Type: multipart/mixed; boundary="_----------=_12585028822638146"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 18 Nov 2009 00:08:02 +0000
From: sales@example.co.uk
To: a@example.com
Subject: bleh
Message-Id: <20091118000802.F2D2516581E5@server4.example.co.uk>
Return-Path: automated-bounces@email.example.com
X-OriginalArrivalTime: 18 Nov 2009 00:08:05.0120 (UTC) FILETIME=[33687000:01CA67E3]

This is a multi-part message in MIME format.

--_----------=_12585028822638146
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/plain

bleh

________________________________________________________________________
*** This email has come from the internet and has been scanned for all viruses and potentially offensive content by Examplelabs on behalf of XXX. Please report unwanted spam email to a@example.com ***

Please consider the environment before printing this email.
--_----------=_12585028822638146--



--9B095B5ADSN=_01CA33119A4F8526000227FDawnexfe01.INV.AD--
