Delivered-To: automated-bounces+891e111a-98d6-11df-8ed4-f18edd31f8f5@email.example.com
Received: by 10.229.236.212 with SMTP id kl20cs153253qcb;
        Mon, 26 Jul 2010 09:55:10 -0700 (PDT)
Received: by 10.216.81.195 with SMTP id m45mr7671143wee.23.1280163308304;
        Mon, 26 Jul 2010 09:55:08 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id r83si5332084weq.97.2010.07.26.09.55.05;
        Mon, 26 Jul 2010 09:55:08 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 0054B16582F0; Mon, 26 Jul 2010 17:55:05 +0100 (BST)
Date: Mon, 26 Jul 2010 17:55:05 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+891E111A-98D6-11DF-8ED4-F18EDD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="8A73C16582C5.1280163305/server4.example.co.uk"
Message-Id: <20100726165505.0054B16582F0@server4.example.co.uk>

This is a MIME-encapsulated message.

--8A73C16582C5.1280163305/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<john.smith@example.com>: host mail1.mailhostingservice.com[216.154.198.171]
    said: 550 Your server requires confirmation. Visit
    http://www.mailhostingservice.com/Whitelist.aspx?IP=94.236.45.212 to
    confirm this mail server. (in reply to RCPT TO command)

--8A73C16582C5.1280163305/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 8A73C16582C5
X-Postfix-Sender: rfc822; automated-bounces+891E111A-98D6-11DF-8ED4-F18EDD31F8F5@email.example.com
Arrival-Date: Mon, 26 Jul 2010 17:55:03 +0100 (BST)

Final-Recipient: rfc822; john.smith@example.com
Action: failed
Status: 5.0.0
Remote-MTA: dns; mail1.mailhostingservice.com
Diagnostic-Code: smtp; 550 Your server requires confirmation. Visit
    http://www.mailhostingservice.com/Whitelist.aspx?IP=94.236.45.212 to
    confirm this mail server.

--8A73C16582C5.1280163305/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 8A73C16582C5; Mon, 26 Jul 2010 17:55:03 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_1280163303210331"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Mon, 26 Jul 2010 17:55:03 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=891E111A-98D6-11DF-8ED4-F18EDD31F8F5>
To: John Smith <john.smith@example.com>
Message-Id: <20100726165503.8A73C16582C5@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_1280163303210331
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML

--_----------=_1280163303210331--


--8A73C16582C5.1280163305/server4.example.co.uk--
