Delivered-To: automated-bounces+9cd9a230-8f78-11df-95a5-8f60dd31f8f5@email.example.com
Received: by 10.224.28.133 with SMTP id m5cs199922qac;
        Wed, 14 Jul 2010 11:50:15 -0700 (PDT)
Received: by 10.216.145.194 with SMTP id p44mr5244451wej.82.1279133414282;
        Wed, 14 Jul 2010 11:50:14 -0700 (PDT)
Return-Path: <>
Received: from server4.example.co.uk (server4.example.co.uk [94.236.45.212])
        by mx.google.com with ESMTP id n51si7252384wej.137.2010.07.14.11.50.13;
        Wed, 14 Jul 2010 11:50:14 -0700 (PDT)
Received-SPF: pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) client-ip=94.236.45.212;
Authentication-Results: mx.google.com; spf=pass (google.com: best guess record for domain of server4.example.co.uk designates 94.236.45.212 as permitted sender) smtp.mail=
Received: by server4.example.co.uk (Postfix)
	id 967C316582F4; Wed, 14 Jul 2010 19:50:13 +0100 (BST)
Date: Wed, 14 Jul 2010 19:50:13 +0100 (BST)
From: MAILER-DAEMON@server4.example.co.uk (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: automated-bounces+9CD9A230-8F78-11DF-95A5-8F60DD31F8F5@email.example.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="7E8E816582B3.1279133413/server4.example.co.uk"
Message-Id: <20100714185013.967C316582F4@server4.example.co.uk>

This is a MIME-encapsulated message.

--7E8E816582B3.1279133413/server4.example.co.uk
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host server4.example.co.uk.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to <postmaster>

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@example.net>: host a.b.c[83.223.106.9] said: 553 5.3.0
    <recipient@example.net>... Address does not exist (in reply to RCPT TO
    command)

--7E8E816582B3.1279133413/server4.example.co.uk
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; server4.example.co.uk
X-Postfix-Queue-ID: 7E8E816582B3
X-Postfix-Sender: rfc822; automated-bounces+9CD9A230-8F78-11DF-95A5-8F60DD31F8F5@email.example.com
Arrival-Date: Wed, 14 Jul 2010 19:50:03 +0100 (BST)

Final-Recipient: rfc822; recipient@example.net
Action: failed
Status: 5.3.0
Remote-MTA: dns; a.b.c
Diagnostic-Code: smtp; 553 5.3.0 <recipient@example.net>... Address does not
    exist

--7E8E816582B3.1279133413/server4.example.co.uk
Content-Description: Undelivered Message
Content-Type: message/rfc822

Received: by server4.example.co.uk (Postfix, from userid 507)
	id 7E8E816582B3; Wed, 14 Jul 2010 19:50:03 +0100 (BST)
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Type: multipart/related; boundary="_----------=_127913340391591"
X-Mailer: MIME::Lite 3.027 (F2.77; T1.28; A2.04; B3.08; Q3.08)
Date: Wed, 14 Jul 2010 19:50:03 +0100
From: Fred Bloggs <fred.bloggs@email.example.com>
Subject: foo
List-Unsubscribe: <http://www.exampleoffers.co.uk/unsubscribe.epl?uuid=9CD9A230-8F78-11DF-95A5-8F60DD31F8F5>
To: john smith <recipient@example.net>
Message-Id: <20100714185003.7E8E816582B3@server4.example.co.uk>

This is a multi-part message in MIME format.

--_----------=_127913340391591
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html

HTML goes here

--_----------=_127913340391591--


--7E8E816582B3.1279133413/server4.example.co.uk--
